### ISSUE TITLE
Ajout d'un About ServerGRIS dans la menu File

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#100]
Il faut ajouter un «About ServerGRIS» dans la menu File (comme dans Cecilia par exemple).
Avec les crédits de la page couverture du manuel:

Version 1.0
Developed by the G.R.I.S. at Université de Montréal
(Groupe de Recherche en Immersion Spatiale)
Director:
Robert NORMANDEAU
Programmers:
Actual: Olivier BÉLANGER
Former: Vincent BERTHIAUME, Nicolas MASSON,Antoine MISSOUT
Assistants:
David LEDOUX, Christophe LENGELÉ, Vincent MONASTESSE

**Comment by Normandeau** [comment]
Si le «About» figure dans le menu Help, il faudrait alors ajouter dans l'affichage qu'un manuel complet est disponible sur SourceForge, non?
Sinon, ce n'est pas un Help très aidant...

**Comment by belangeo** [comment]
Je peux carrément intégrer le manuel dans le logiciel et ajouter une commande dans le menu help pour l'ouvrir avec le lecteur pdf par défaut sur le système. Intéressé?

**Comment by Normandeau** [comment]
V015
C'est fait. Je t'envoie la version finale du manuel avec les corrections du pink noise.
