### ISSUE TITLE
Numéros d'outputs affichés pour l'enregistrement

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#101]
Je suggère de créer une option permettant de choisir entre deux affichages des numéros correspondant à chaque VU-Mètre de sortie dans la zone Outputs + chaque HP dans la zone Speaker:
- Un affichage correspondant aux numéros de sortie de l'interface audio (comme c'est présentement le cas);
- Un affichage correspondant à l'identification physique des HP, comme c'est le cas lorsqu'on soumet un enregistrement multipiste débutant par la piste 1, 2, ... (comme ce fut le cas pour les Ultrasons - chacun devait déposer des fichiers stéréos dans le bon ordre, de 1 à 16).

En ce moment, on a d'autre choix que d'afficher les numéros correspondant à ceux de l'interface audio. Ce qui n'est pas vraiment un problème lorsqu'on utilise un système comme Dante, mais qui peut devenir mêlant si on ne peut avoir des numéros de sortie consécutive ou encore ne commençant pas par 1, comme c'est le cas dans le dôme du B-187, par exemple. On peut connaître le numéro de position correspondant à chaque HP selon leur configuration physique, mais bien souvent, ce chiffre ne correspond pas au numéro de sortie de l'interface. Dans le cas du B-187, les deux plus petits chiffres (5 et 6) correspondent aux subs. Puis, on saute à 31 pour tous les HP subséquent. Ça serait bien de pouvoir avoir l'option d'afficher soit le numéro d'identification du HP (dans l'espace physique), soit le numéro de sortie correspondant dans l'interface, non?

Idéalement cette option devrait demeurer accessible rapidement dans l'interface, comme un toggle.

Je suggère également de colorer le haut des Vu-mètres correspondant à des sorties directes en orange afin de les séparer visuellement du lot, sans pour autant prendre plus de place.

**Comment by led78** [comment]
Une raison d'avoir cette option est l'enregistrement stéréo ou HRTF. Bien qu'avec la version 0.1.4. l'enregistrement binaural fonctionne adéquatement, si notre Speaker setup ne contient pas les sorties 1-2, on ne voit pas les VU-mètres correspondant aux canaux d'enregistrement.

**Comment by Normandeau** [comment]
V014
Ou ajouter systématiquement les Sorties 1-2 avec les modes HRTF et Stereo? Au bout de la série des outputs? Si le setup contient déjà 1-2 ce serait un doublon visuel, mais pas audio. Si le setup ne contient pas 1-2 (comme c'est le cas dans le 187), ce serait un ajout.
Je ne sais pas si c'est une solution envisageable, et facile, mais ce serait vachement utile.
Ou tout simplement deux VU-mètres supplémentaires en permanence?

![servergris avec vu-metres 1-2](https://user-images.githubusercontent.com/8959779/35360952-73670fda-012d-11e8-8242-87f52ea7c45a.jpg)

**Comment by led78** [comment]
Ça me fait penser à autre chose - qui devrait probablement être identifier dans un billet distinct - au sujet de l'enregistrement : dans le Zirkonium, l'enregistrement peut à la fois créer un fichier stéréo binaural en plus des fichiers audio pour chaque sortie du speaker setup. Ce qui fait qu'on a pas besoin de faire deux enregistrements - donc faire jouer toute la durée d'une pièce deux fois - pour avoir et la version binaurale et la version multiphonique. Bien entendu, ce n'est pas toujours nécessaire d'enregistrer les deux en même temps, mais d'avoir l'option de le faire peut néanmoins permettre à l'utilisateur de sauver du temps.
Tout ça pour dire que j'aime bien l'idée d'avoir des canaux 1-2 dédiés à la stéréo (et à son enregistrement) et indépendant des canaux de sortie du speaker setup.

**Comment by led78** [comment]
Aussi, pour ces Vu-mètres d'enregistrement, je crois qu'il serait plus utile d'afficher les niveaux non pas en dB RMS, mais en valeur de crête. Je viens de faire un enregistrement stéréo de ma pièce avec un gain à 0.8 et les Vu-mètres 1-2 n'ont jamais semblé écrêter. Or, en l'ouvrant dans Twisted Wave, la forme d'onde dépasse fréquemment 0 dBFS, ce qui introduit du bruit d'écrêtage. Il est donc difficile d'évaluer à quel niveau on doit mettre le gain du Server afin de s'assurer de ne jamais dépasser le 0 dBFS. Ça serait quand même important d'ajuster cela rapidement; vivement des Vu-mètres séparés pour l'enregistrement alors.

**Comment by Normandeau** [comment]
David a écrit:
Je n'ai pas de problème à ce qu'on voit le setup VBAP employé pour le binaural, en autant que la stratégie est expliquée dans le manuel. Toutefois, afin d'être cohérent, et ce également pour tous les futurs speaker setup incluant les plus conventionnels (5.1, 7.1, 9.1, NHK, etc.), il faudrait que le mode choisit n'affiche que les hautparleurs de sortie, en plus des subs s'il y a lieu. Dans ce cas, le mode stéréo ne devrait afficher que deux hautparleurs et non le setup VBAP précédent, par exemple.

En fait, j'y pense depuis quelques temps, ne serait-ce pas préférable d'avoir une paire d'hautparleurs stéréo affichée en permanence? Il y a plusieurs raison pour cela, mais elles tournent tous autour de la même problématique. Je m'explique :
Lorsqu'on ouvre le Server, Jack prend possession de l'interface donc de toute sortie audio passant par celle-ci. Or, dans la logique où les outils GRIS se veulent intégrés au travail de composition habituel, cela restreint la pré-écoute de fichiers sons, en dehors du séquenceur. Il y a évidemment moyen de contourner le problème grâce à TotalMix, mais n'en demeure pas moins que ça crée un nouvel obstacle que l'on pourrait éviter à l'utilisateur, d'autant plus que ce n'est pas toutes les interfaces qui ont un TotalMix pour ce faire. Là où je veux en venir c'est que si l'on inclus par défaut une sortie stéréo direct qui emploi les deux hautparleurs les plus proche d'une position stéréo (frontal à +/- 30°), on aurait pas besoin d'ajouter des entrées additionnelles dans le Serveur et on aurait du son dès que l'on écoute un fichier audio à partir du Finder, par exemple, ou toute autre application que le DAW principal. Une fois le fichier audio désiré choisit, on l'importe alors dans le DAW.
En ce moment, je contourne cet obstacle en créant des entrées/sorties directes supplémentaires dans le Serveur, que j'assigne aux mêmes canaux que les hautparleurs frontaux (1-2 dans l'Hexa, 11-12 dans le B-187) dans TotalMix.

Qu'en pensez-vous?
