### ISSUE TITLE
Raccourci clavier pour le Pink Noise?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#102]
Dans le menu View: Alt-P?
Puisque tous les menus de View en ont un...

**Comment by belangeo** [comment]
J'aimerais mieux pas... Pour la simple raison qu'une erreur de raccourci ou le fait d'accrocher une touche peut nous balancer un pink noise dans les oreilles! C'est rude...

**Comment by Normandeau** [comment]
Ok bonne idée!!!

Envoyé de mon phoni
