### ISSUE TITLE
Pink Noise et niveau de sorties des hp: incompatibles

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#103]
J'ai eu un flash aujourd'hui. On s'est mis un Pink Noise dans le ServerGRIS et on s'est mis un niveau de gain ajustable par hp. La principale préoccupation derrière cela était d'offrir la possibilité de calibrer un dispositif de hp au moment du concert. Or cela n'est pas possible de la manière dont c'est configuré actuellement. Pour deux raisons:
- le pink noise ne passe pas par le contrôle de gain des hp. Le niveau de sortie du pink noise est fixe;
- lorsqu'on ouvre la fenêtre de configuration des hp, tout le son du Server est coupé  automatiquement (probablement pour de très bonnes raisons...).
Donc il faut trouver une solution à cela, car à quoi cela nous sert-il de mettre un bruit de référence si on n'est pas capable de s'en servir en situation réelle pour calibrer.
Suggestions.
1. Pink noise dans la fenêtre d'édition des hp
Mettre le Pink Noise directement dans la fenêtre de configuration des hp. On pourrait ainsi l'activer et ajuster le niveau de sortie de chaque hp au fur et à mesure. Il faudrait aussi que les gains de sortie se reflète dans les VU-mètres des hp. Possible? Le fait de le mettre dans la fenêtre des hp éviterait aussi de l'activer par erreur Il disparaîtrait du menu View).
2. Pink Noise dans la fenêtre principale et niveau de gain sur les outputs
Le Pink noise serait juste un bouton avec un niveau général qu'on activerait comme on active l’enregistrement par exemple. Cette solution est probablement plus compliquée car cela veut dire qu'il faut ajouter une valeur de gain sur chaque sortie. Et puis il y a toujours la possibilité d'accrocher le pink noise par mégarde...

**Comment by belangeo** [comment]
La solution numéro 1 me semble assez simple à mettre en place!

**Comment by Normandeau** [comment]
V015
Ça marche!
