### ISSUE TITLE
Décalage au passage de 180˚

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#104]
La source 5 «accroche» au passage de 180˚. Voir la vidéo expédiée par courriel. Le SpatGRIS a l'air de bouger linéairement, mais la source saute d'un pas en arrière ou d'un pas en avant selon la direction. Problème de SpatGRIS? De transmission OSC? De ServerGRIS?

**Comment by Normandeau** [comment]
En expérimentant davantage, ce sont toutes les sources qui «jumpent» au passage à 180˚. Problème graphique? Est-ce que ça répercute dans l'audio? À vérifier.

**Comment by Normandeau** [comment]
J'ai enregistré une trajectoire de pendule aujourd'hui qui oscille de part et d'autre du passage à 180˚. Le Server jumpe à ce passage, mais pas le SpatGRIS. Ni en enregistrement de la trajectoire, ni en lecture de celle-ci.

![capture d ecran 2018-02-03 a 16 18 13](https://user-images.githubusercontent.com/8959779/35771621-dfa6e36e-08fd-11e8-8225-bb6937599248.jpg)

**Comment by belangeo** [comment]
C'est réglé. Le problème est que le SpatGRIS envoit ses coordonnées dans un vieux format (je suppose que c'est pour être compatible avec le Zirkonium). Ces coordonnées (-1 à 1 en azimuth et 0 à 0.5 en zénith sur une adresse OSC "/pan/az") ne correspondent pas avec la nouvelle nomenclature, celle qui figure dans le manuel. La conversion dans le ServerGris était éronnée.

Il faudrait pouvoir spécifier directement dans le SpatGRIS où on veut envoyer les coordonnées et utiliser automatiquement le bon format. Pour l'instant, j'ai patché le ServerGris pour que ça fonctionne. On réécrira au propre quand on va re-travailler le SpatGRIS.

**Comment by Normandeau** [comment]
Oui on avant déjà évoqué cela, quand par exemple les gens du ZKM m'avait demandé d'ouvrir un menu déroulant avec différentes options de logiciels asservis, genre Zirkonium. ServerGRIS, etc. Ils pensaient plus spécifiquement à Wave1 Sonic Emotion WFS system (voir issue 155). On n'a jamais donné suite à cette demande de... 2016! On regardera cela effectivement au moment de la réécriture du SpatGRIS.
