### ISSUE TITLE
ServerGRIS lorsqu'utilisé comme mixeur de sorties

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#105]
La situation:
J'ai une pièce multicanal prévue pour un dôme de hp que je veux mixer en 8 pistes pour un concert. J'ai d'abord essayé de n'utiliser qu'un speaker setup plan octophonique, mais il manquait beaucoup d'informations provenant du haut du dôme. Alors je me suis dit que j'utiliserais un setup double-octo, la deuxième octophonie étant plus haute dans le dôme, décalée de 22,5˚ et récupérant ces informations. Je n'aurais eu ensuite qu'à mixer ces deux octophonies pour en faire une seule.
Puis je me suis dit que tant qu'à faire je pourrais me servir du ServerGRIS comme d'un mixeur en attribuant les mêmes numéros de sorties à l'octo du haut qu'à celle du bas. Bonne idée non? Ainsi je fais un mixage et je n'ai besoin d'enregistrer que huit sorties du premier coup. 
Grrrrit! Mauvaise touche! Dès que je fais Compute, le Server se plante. J'ai essayé trois fois, rien à faire. C'est donc une fonction impossible. Je propose alors qu'on interdise le double usage d'un même numéro de sortie lorsqu'on fait un speaker setup afin de prévenir ce genre de crash.
Et qu'on réfléchisse ensuite sur cette fonction, qui peut-être vachement intéressante. En effet, si on n'a qu'une octo chez soi, on pourrait mixer des pièces pas mal plus complexes de cette manière et les entendre.

Avant le crash:
![capture d ecran 2018-02-05 a 11 54 37](https://user-images.githubusercontent.com/8959779/35817442-5f98667e-0a6b-11e8-9c1a-cab63cd13d34.jpg)

**Comment by belangeo** [comment]
D'avoir plus d'une fois un numéro de sortie pour le VBAP, ça ne fait pas de sens, impossible à trianguler. Je suis aussi d'avis que ça devrait être bloqué directement dans la fenêtre d'édition. D'un autre côté, un setup à 2D devrait simplement ignorer l'information d'élévation et du coup, permettre une réduction en 2D d'une pièce 3D. Je vais y jeter un oeil demain.

**Comment by belangeo** [comment]
Done!
