### ISSUE TITLE
Color Inputs par pairs

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#107]
Ajouter l'option de colorer automatiquement les entrées par pairs (stéréo) et non seulement individuellement (mono).

**Comment by belangeo** [comment]
Clic gauche: change la couleur de l'input sélectionné.

Clic droit: change la couleur de l'input sélectionné **et** de l'input suivant.

**Comment by Xon77** [comment]
Le coloriage des entrées par pairs, avec un clic droit, fonctionne bien.
