### ISSUE TITLE
Améliorations et commentaires

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#11]
Améliorations suggérées:
- Contrôler l'orientation du dôme graphique à l'aide du clic gauche plutôt que droit (comme Christophe l'a suggéré).
- Grossir la taille des numéros d'hautparleurs.
- Permettre de créer et sauvegarder des préréglages du vue du dôme graphique pour le repositionner rapidement et selon notre préférence.
- Permettre d'inverser le sens du contrôle du dôme graphique. Actuellement, le contrôle de l'orientation du graphique est l'inverse de celui du Zirkonium. Avoir le choix serait bien.
- Séparer la fenêtre du dôme graphique 3D de celle des vu-mètres serait bien (comme c'est la cas pour la fenêtre 2D.

Commentaires:
- J'aime beaucoup la vue 2D. C'est pratique et complémentaire.
- Ça fonctionne comme un charme avec Logic!
- La position des haut-parleurs semblent plus à l'intérieur du dôme graphique que celle des sources pour les couronnes supérieures, mais pas celle du bas (octophonie) où c'est plutôt l'inverse: la position des sources est plus à l'intérieure que celle des haut-parleurs. Cela semble être du au speaker setup de l'Hexa, puisque ce n'est pas le cas avec un autre speaker setup plus «arrondis» comme celui que j'ai fais pour le Il suono dipiero (conservatoire Santa Cecilia à Rome).

Questions:
- Si je comprends bien, le mode high performance diminue volontairement la charge graphique des vu-mètres pour sauver du CPU?
- Si tel est le cas, pourrais-t-on avoir la possibilité d'ajuster le temps de descente des vu-mètres? Par exemple, avoir une vue crête et une vue RMS et pouvoir modifier leur vitesse de modulation? Est-ce que ça pourrait aider à diminuer la charge CPU (tout en étant plus polyvalent)?
- Serait-ce possible d'activer la lecture du séquenceur à partir de la fenêtre du Server? Pour le travail de composition, ça l'enlèverait l'irritant de toujours devoir passer de la fenêtre du server à celle du DAW (pour démarrer la lecture), puis revenir sur la fenêtre du server pour visualiser. C'est pas grand chose mais bon...

**Comment by Xon77** [comment]
La possibilité de forcer la fenêtre du SpatServer d'être toujours en avant plan, même si un autre programme, comme le séquenceur, est sélectionné serait aussi une option intéressante (via une case à coche à cocher : always to front) ?
ce qui permettrait d'éviter l'option d'activer la lecture du séquenceur du serveur.
Tout dépend de la facilité de mise en place entre l'une de ces 2 fonctions.

**Comment by Xon77** [comment]
Concernant le mode high performance, il réduit non seulement le taux de rafraîchissement des sliders, mais retire le mode anti-aliasing en de la scène sonore. Il a un impact considérable sur le CPU, puisqu'il réduit pour moi la charge du SpatServer par 3, de 60% à moins de 20%.

**Comment by Xon77** [comment]
La possibilité d'ordonner (automatiquement ou non via un bouton) les vu-mètres des outputs selon leur nombre pourrait être aussi intéressante.

**Comment by Xon77** [comment]
Je trouve que la possibilité de pouvoir copier en mémoire une couleur de l'input (dans la fenêtre de couleurs qui s'affiche quand on clique sur le chiffre de l'input, via l'ajout de 2 boutons copy / piste) serait pratique, afin d'appliquer et coller la couleur à d'autres inputs, lorsqu'on rentre dans la boite de sélection de la couleur. Ceci permettrait d'appliquer rapidement exactement la même couleur à des groupes de pistes, lorsqu'on organise son projet. Je ne sais pas si c'est clair... c'est encore un petit détail.

**Comment by led78** [comment]
Je seconde. C'est aussi ce que je faisais dans le serveur du Zirkonium. C'était bien pratique.
