### ISSUE TITLE
Add a VBAP+HRTF spat mode.

### ISSUE THREAD

**Issue by belangeo** [GRIS-UdeM/ServerGRIS#110]
Fixed 16 channels (maybe 32?)

**Comment by Normandeau** [comment]
Cette fonction est fondamentale dans le Server. Je ne crois pas qu'on puisse lancer celui-ci avant que cette fonction soit adéquate. Ici, au stage, personne ne l'utilise, car elle n'est pas fonctionnelle, même dans le version 1.01.
Alors soit on attend, soit on lance la version actuelle en désactivant le mode HRTF.

**Comment by belangeo** [comment]
Salut Robert,

En quoi l'HRTF n'est pas fonctionnelle? Est-ce seulement pour le nombre
d'inputs possibles ou il y a un autre problème?

Olivier

2018-02-28 23:04 GMT-05:00 Robert Normandeau <notifications@github.com>:

**Comment by led78** [comment]
Je viens de tester le mode HRTF avec une seule piste stéréo (version 1.01). Pour ce qui est du problème d'interpolation, ça me semble réglé. De ce fait, le filtrage HRTF semble mieux fonctionner : les sensations d'élévation et de position arrière sont perceptibles. Il y a sûrement place à amélioration en essayant d'autre banque de réponses impulsionnelles. Il faudrait que je teste avec une pièce comprenant plusieurs sources spatialisées, pour savoir si c'est toujours aussi efficace.

Mais, je crois que la principale contrainte demeure le nombre de canaux, cela constitue une limitation probablement trop importante pour être présentable.

**Comment by Normandeau** [comment]
Autre test.
Session DP, 11 pistes stéréo (22 inputs au total dans ServerGRIS), dont 20 pistes automatisées. HRTF LOW.
Jack est surchargé, ça génère des impulsions de bruit numérique au niveau maximum de manière ponctuelle. Je ne veux vraiment pas avoir un casque d'écoute sur les oreilles. Très dangereux.
Il me semblait qu'en mode LOW on réussissait à avoir un nombre plus élevé de pistes en entrée, non?
HRTF HIGH est évidemment inutilisable.

**Comment by Normandeau** [comment]
Version 102
Très bien le nouveau mode binaural sur le plan sonore. Un peu de perte de grave, possible? À confirmer.
Cependant je suis un peu surpris de voir la configuration de hp changer lorsqu'on passe de VBAP à BINAURAL. Peut-être est-ce une question d'habitude. Par contre il y a un problème relatif à cet affichage.
Lorsqu'on passe de VBAP à BINAURAL, la configuration de HP change, par exemple de Dome32 à hrtf_vbap.
Si on passe ensuite à STEREO, c'est cette dernière configuration qui reste affichée!
Si je reviens à VBAP avec mon Dome32 et qu'ensuite je passe à STEREO, c'est Dome32 qui reste affiché.
Donc quel est le setup de hp qui est le bon pour STEREO: hrtf_vbap ou Dome32?
Confusion ici.
Ma question est: doit-on changer l'affichage pour vbap_hrtf? Est-ce que l'utilisateur veut voir ce qui se passe derrière? Si la réponse est oui, alors il faut corriger le passage d'un mode à l'autre afin d'être cohérent. Ainsi à STEREO, on doit toujours revenir à la configuration de base.
Si non, et c'est ce que je pense, on a toujours la même configuration de hp qui est affichée, quelque soit le mode de calcul à l'interne pour faire le rendu audio.
Commentaires?

**Comment by belangeo** [comment]
Oui, je préférerais aussi qu'on ne voit juste pas le setup générique pour le binaural mais comme tout est relié (les vues, la spatialisation, les messages) et dépendant du setup VBAP, c'est compliqué d'avoir un setup caché... Je vais y réfléchir encore... Pour sûr, le passage de BINAURAL à STEREO devrait aussi rammener le setup gardé en mémoire, comme pour le retour à VBAP.

**Comment by led78** [comment]
Je n'ai pas de problème à ce qu'on voit le setup VBAP employé pour le binaural, en autant que la stratégie est expliquée dans le manuel. Toutefois, afin d'être cohérent, et ce également pour tous les futurs speaker setup incluant les plus conventionnels (5.1, 7.1, 9.1, NHK, etc.), il faudrait que le mode choisit n'affiche que les hautparleurs de sortie, en plus des subs s'il y a lieu. Dans ce cas, le mode stéréo ne devrait qu'afficher que deux hautparleurs et non le setup VBAP précédent, par exemple.

En fait, j'y pense depuis quelques temps, ne serait-ce pas préférable d'avoir une paire d'hautparleurs stéréo affichée en permanence? Il y a plusieurs raison pour cela, mais elles tournent tous autour de la même problématique. Je m'explique : 
Lorsqu'on ouvre le Server, Jack prend possession de l'interface donc de toute sortie audio passant par celle-ci. Or, dans la logique où les outils GRIS se veulent intégrés au travail de composition habituel, cela restreint la pré-écoute de fichiers sons, en dehors du séquenceur. Il y a évidemment moyen de contourner le problème grâce à TotalMix, mais n'en demeure pas moins que ça créer un nouvel obstacle que l'on pourrait éviter à l'utilisateur, d'autant plus que ce n'est pas toutes les interfaces qui ont un TotalMix pour ce faire. Là où je veux en venir c'est que si l'on inclus par défaut une sortie stéréo direct qui emploi les deux hautparleurs les plus proche d'une position stéréo (frontal à +/- 30°), on aurait pas besoin d'ajouter des entrées additionnelles dans le Serveur et on aurait du son dès que l'on écoute un fichier audio à partir du Finder, par exemple, ou toute autre application que le DAW principal. Une fois le fichier audio désiré choisit, on l'importe alors dans le DAW.
En ce moment, je contourne cet obstacle en créant des entrées/sorties directes supplémentaires dans le Serveur, que j'assigne aux mêmes canaux que les hautparleurs frontaux (1-2 dans l'Hexa, 11-12 dans le B-187) dans TotalMix.

Qu'en pensez-vous?

**Comment by Normandeau** [comment]
Donc peu importe le choix qu'on fera, j'attends la prochaine version avant de compléter le manuel, car cela aura un implication directe sur celui-ci. Si c'est trop compliqué de mettre un setup caché, on le laissera apparent et on expliquera. Mais j'avoue que ce n'est pas idéal.

**Comment by Normandeau** [comment]
V103
Olivier: «Pour ce qui est de cacher le setup binaural, ça demande une grosse restructuration du logiciel. Pour l'instant, l'affichage et le calcul DSP sont trop imbriqués pour pouvoir gérer deux setups différents. Ce serait trop de changements dans la structure à ce moment-ci.»
Pas de problème, on s’habituera.
Et puis ce n'est peut-être pas une mauvaise idée finalement. Ça fait entrer peu à peu dans les mœurs l'idée du setup «standardisé» à 16 canaux pour la circulation des musiques.
