### ISSUE TITLE
Inversion des I et des O dans ServerGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#111]
Les entrées et les sorties sont inversées sans ServerGRIS! Hier je me suis aperçu de cela, parce qu'on a ici une interface avec 18 entrées et 20 sorties (Scarlett 18i20) et que ces chiffres étaient inversées dans ServerGRIS. Vérification faite aujourd'hui, et je confirme la chose. Pourriez-vous tester cela très rapidement?
Dans cette configuration j'ai 4 sorties (O) et 2 entrées (I), contrairement à ce qui apparaît:
![capture d ecran 2018-02-21 a 12 29 30](https://user-images.githubusercontent.com/8959779/36495464-46856fd4-1703-11e8-84b8-ebed56cab847.jpg)

**Comment by led78** [comment]
Je vais voir ce que ça donne dans le grand dôme. Pour vraiment tester il faut avoir un nombre d'entrée et de sortie inégal, ce qui n'est pas le cas de mon interface personnelle.

**Comment by belangeo** [comment]
Je confirme en ce qui concerne l'affichage, les valeurs sont inversées. Est-ce aussi le cas en performance. Dans cette config (2 ins - 4 outs), est-ce que tu peux envoyer du son aux sorties 3 et 4 ?

**Comment by belangeo** [comment]
Ici, avec un dongle usb qui a 1 in et 2 outs, l'affichage est inversé mais j'entend le son envoyé dans les deux sorties. Ça me semble être seulement un problème d'affichage (déjà réglé si c'est le cas) mais j'attend confirmation de votre part!

**Comment by Normandeau** [comment]
Le studio est pas mal occupé ici, je pourrai vérifier cela demain en pm seulement. Mais j'ai l'impression que c,es une inversion cosmétique.

**Comment by Normandeau** [comment]
Confirmation: les fonctions I and O sont inversées, mais seulement graphiquement. Sur le plan audio, ici, les 20 sorties sont bel et bien disponibles (et non pas seulement 18).

**Comment by belangeo** [comment]
Ok, c'est corrigé.
