### ISSUE TITLE
Limitations de l'approche multi-clients

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#112]
Bien que l'on puisse ouvrir plusieurs clients avec Jack comme interface audio et qu'ils apparaissent ensuite dans la fenêtre client du ServerGRIS, je n'arrive pas à en connecter plus d'un, soit mon DAW. Auparavant, avant que Jack soit intégré au Server, j'avais l'habitude d'utiliser Jack pour connecter des outils comme les GRM Tools, Soundgrain, Cecilia, Reaktor, etc. directement vers les sorties hautparleurs ou encore vers une entrée dans mon DAW afin d'y enregistrer directement l'audio.

Lorsque j'ouvre un autre logiciel comme ceux mentionnés ci-haut, en plus de mon DAW, il apparaît bien dans la fenêtre client du ServerGRIS. Mais, lorsque je clique sur le On/Off, le «X» persiste et rien ne se connect. Je ne peux donc plus entendre la matière sonore que je créer dans d'autres outils que mon DAW, lorsque j'utilise le ServerGRIS. Sait-on pourquoi ça ne se connect pas?

Si je connect ces logiciels directement dans l'interface audio, la synchronisation audio flanche assez rapidement puisque c'est Jack qui mène le bal. Ce n'est donc pas envisageable.

**Comment by Normandeau** [comment]
Oui j'avais constaté la même chose ici, et j'avais oublié de le mentionner. Ce qui se passe avec Reaper par exemple, c'est qu'il y a 128 canaux qui sont automatiquement alloués à celui-ci lorsqu'il se branche sur le Server. On peut modifier ce nombre, mais dès qu'on active le Server, le nombre se remet automatiquement à 128. Ce qui est embêtant parce que Reaper est limité à 64 canaux! Et de plus ça coupe l'audio.
Et comme le mentionne David, il n'est plus possible d'utiliser le Server en mode multiclient. Pourtant cela a déjà fonctionné, car je me souviens très bien d'avoir fait fonctionner DP et Reaper en même temps. D'ailleurs les images du manuel viennent de cette session.
Je suggère donc deux choses:
- que la valeur par défaut de branchement des clients soit de 32 (et non pas de 128).
- que le problème multiclient soit résolu!
Ici j'ai des gars pas mal avancé qui travaille avec SuperCollider, ProTools et Reaper en même temps, en plus du Server... Bon d'accord, c'est pas mal expérimental, mais le manuel dit que c'est possible!

**Comment by belangeo** [comment]
Je vais y jeter un oeil sur OSX demain. Sur ma machine linux, je n'ai pas de problème à avoir plus d'un client.

**Comment by belangeo** [comment]
Petit update...

Pour pouvoir connecter plus d'un client au serveur, il faut s'assurer que le serveur a assez d'inputs pour connecter tous. En donnant 256 inputs au serveur, j'ai DP, REAPER et pyo de connectés et tout roule:

DP: start=1, end=18, available=18
REAPER: start=19, end=146, available=128
Python: start=147, end=148, available=2

Maintenant, là où il semble y avoir un problème, c'est que le serveur ne semble pas accepter les changements de "start" et de "end", il reprend toujours les valeurs envoyés par le client. Ça pose problème avec REAPER qui envoit 128 canaux disponibles. Si on le place en premier (même si on utilise peu de canaux), et qu'on tient compte de la limitation du SpatGris à 99 canaux OSC, on ne peut contrôler DP, par exemple, en second.

Alors, pour l'instant, vous pouvez gérer plusieurs clients en vous assurant d'avoir assez d'inputs et en ouvrant REAPER en dernier. Pour ceux qui utilise SuperCollider, ça ne pose pas de problème de l'ouvrir en dernier puisqu'il n'y aura pas la limite au niveau OSC (comme c'est le cas avec pyo dans mon exemple). 

Je vais maintenant voir comment imposer un nombre limité de canaux par client...

**Comment by led78** [comment]
« En donnant 256 inputs au serveur, j'ai DP, REAPER et pyo de connectés et tout roule »
Ah! Je viens de comprendre pourquoi ça ne marchait pas... Autrement dit, si je veux ajouter d'autres clients en plus de DP (qui utilise 64 canaux), je dois ajouter manuellement des entrées dans le Server, même si je ne veux que sortir du son. Ça fait totalement du sens. Ça explique pourquoi ça ne voulait pas se connecter quand je cliquais sur le 'on/off'. On pourrait alors faire apparaitre un message d'avertissement disant « please add more inputs to connect client », ou quelque chose du genre.

**Comment by led78** [comment]
Tout comme Reaper, Logic Pro utilise aussi 128 canaux et c'est également le cas d'Izotope RX 6 Advanced. Or, il est commun - et c'est mon cas - d'utiliser un éditeur audio externe, comme iZotope RX, en complément d'un DAW. Ce qui veut dire que je devrais d'abord ouvrir tous les outils qui utilisent peu de canaux en premier (i.e. Soundgrain), ensuite Logic Pro, mais qu'il ne me restera plus assez de canaux pour sortir le son d'Izotope RX 6. Autrement dit, ça devient assez contraignant dès qu'on utilise un système occupant 128 canaux, voir impossible d'en utiliser deux simultanément (ex: Logic Pro ou Reaper + Izotope RX). Il faudrait vraiment débloquer cette limite et pouvoir choisir le nombre précis de canaux utilisés par client.

**Comment by belangeo** [comment]
C'est réglé maintenant. On peut modifier le "start" et le "end" des clients selon nos besoins, c'est-à-dire qu'on peut utiliser 2 canaux de REAPER même s'il y en a 128 "available".

**Comment by Normandeau** [comment]
V103
Réglé
