### ISSUE TITLE
Annuler le nommage d'une sauvegarde avant la fermeture du Server annule la sauvegarde mais pas la fermeture.

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#113]
Petit irritant potentiel, lorsque l'on quitte le Server et que l'on choisit de faire une sauvegarde avant de quitter, la fenêtre Finder apparait pour que l'on nomme et choisisse l'emplacement de la sauvegarde. Si l'on réalise à cette étape que l'on veut apporter une correction à notre projet ServerGRIS et que l'on clique sur annuler pour effectuer une correction avant de sauvegarder, le projet se ferme sans sauvegarder au lieu de revenir en arrière et annuler la fermeture.
C'est un détail, mais je pose tout de même la question : ne serait-il pas préférable d'être du côté préventif en annulant aussi la fermeture (et non la sauvegarde) afin de ne pas risquer de perdre toute modification précédente?

**Comment by Normandeau** [comment]
Version 102
Réglé.
