### ISSUE TITLE
Problème entre DP et ServerGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#116]
Version 102
Contrairement à Reaper, Logic ou Live où 128 anaux de communication sont automatiquement alloués au DAW dès leur ouverture, DP n'utilise que les canaux nécessaires. Une session de 38 pistes ouvrira 38 entrées dans ServerGRIS par exemple. Or depuis la version 102, bien que ServerGRIS soit toujours capable de détecter le nombre de canaux nécessaires en les affichant dans la colonne Available, dans la plupart des cas, il n'arrive plus à allouer le nombre de canaux réellement utilisés par DP. C'est la première version de ServerGRIS qui se comporte de la sorte. Et le nombre de canaux offerts par ServerGRIS est aléatoire.
Activer On/Off dans ServerGRIS ne fait rien à l'affaire.

Des exemples.
Ouverture de DP, aucun canal pré-alloué
![dp canaux a l ouverture](https://user-images.githubusercontent.com/8959779/37520012-ccd64d7e-28f1-11e8-967e-71fb89164ece.jpg)

DP, Session de 38 canaux: 16 sur 38
![dp 16 sur 38](https://user-images.githubusercontent.com/8959779/37520053-f54869f4-28f1-11e8-93b7-a816348e2be3.jpg)

DP, Même session de 38 canaux: 32 sur 38
![dp 32 sur 38](https://user-images.githubusercontent.com/8959779/37520068-00a884fa-28f2-11e8-8119-a8269ef9360b.jpg)

Reaper, Même session de 38 canaux: 128 sur 38
![reaper 128 38](https://user-images.githubusercontent.com/8959779/37520414-44f1501e-28f3-11e8-8032-5266f617dc10.jpg)

DP, Session de 54: 2 sur 54
![dp 2 sur 54](https://user-images.githubusercontent.com/8959779/37520082-0bb1d1b2-28f2-11e8-8b29-d40b03d4ab32.jpg)

Cette dernière est la pire. En effet, dans le cas des sessions 16/38 ou 32/38, au moins les canaux actifs jouent et les autres sont ignorés. Mais ici, dans 2/54, aucun son ne passe, ni n'est affiché. Alors on se demande quelle erreur on a fait.
Bien sûr, on peut manuellement changer la valeur de End, mais pour moi c'est une régression. Je comprends bien la cas particulier de DP, mais ça marchait très bien avant. Pourquoi ce changement maintenant?
**À corriger impérativement.**

**Comment by belangeo** [comment]
Oui, DP a un comportement différent de tous les autres en ce qu'il ne donne pas de canaux disponibles à l'ouverture... Ça change beaucoup la donne dans le ServerGris puisque celui-ci a connaissance d'un nouveau client lorsque l'application est ouverte. Après, il faut faire les choses manuellement. Je vais chercher une solution...

**Comment by Normandeau** [comment]
C'est vrai que DP a un comportement différent des autres séquenceurs, mais jusqu'à présent, donc jusqu'à la version 102, ServerGRIS affichait toujours correctement et automatiquement le nombre de canaux ouverts dans DP. Qu'est-ce qui a changé dans 1.02 qui fait que ce n'est plus le cas?

**Comment by Normandeau** [comment]
Deux nuances importantes
J'ai fait quelques essais supplémentaires à ce sujet ce matin, ce qui me permet d'ajouter deux nuances à ce bogue:

1. Première **session**
Lors de l'ouverture de la première session DP, après l'ouverture du ServerGRIS, le nombre de canaux nécessaires est toujours détecté correctement par ce dernier. Si la première session est constituée de 54 canaux, ils sont tous détectés par ServerGRIS. Même chose avec 34, ou 38.

2. **On/Off**
Si je n'active pas Jack avec le commutateur On/Off, je peux passer d'une session à l'autre et à chaque fois le nombre de canaux est détecté correctement dans ServerGRIS. Je suis ainsi passé d'une série de sessions de 34, 38 et 54 canaux respectivement, et dans n'importe quel ordre, et chaque fois ServerGRIS a été correct dans sa détection du nombre de canaux. Dès que j'active Jack cependant c'est terminé, plus aucune session n'est détectée correctement lorsque je les ouvre successivement.

Ce n'est donc que lorsqu'on active Jack que le problème se pose. J'imagine que cela aide à circonscrire le terrain de jeu. Cela étant dit, je mets une note dans le manuel pour le moment.

**Comment by belangeo** [comment]
En effet, ça aide! Merci!

**Comment by Normandeau** [comment]
Version 103
Le problème est réglé, DP et Server communiquent impeccablement.
