### ISSUE TITLE
OSC + Audio

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#117]
**Pour **votre** info.**
Je me demandais comment fabriquer un projet qui combinerait à la fois le dôme en OSC et l'audio en PanSpan, afin de permettre des trajectoires qui entrent à l'intérieur du dôme (en attendant le DBAP). En utilisant JackPilot, on peut tout simplement se servir de celui-ci comme d'un mixeur et ainsi mélanger des flux audio provenant d'une part du ServerGRIS et d'autre part directement du séquenceur. C'est possible avec le Zirkonium+JackPilot, mais avec le ServerGRIS, ça ne marche pas. Celui-ci a en effet a besoin d'une information de position afin d'envoyer le signal audio entrant vers les sorties. La matrice de Jack n'est pas accessible directement.
J'ai donc résolu assez facilement la situation. La séquence est ainsi constituée (c'est juste un modèle pour illustrer la solution):
- n'importe quel Speaker Setup qui comprend 8 hp dans le cercle de base (comme dans Hexa)
- 8 pistes mono avec 8 SpatGRIS en mode OSC 1X1, canaux 1 à 8 (ces pistes sont utilisées en mode OSC pour spatialiser dans le dôme).
- 1 piste octo (vide) avec SpatGRIS en mode OSC 8X8, canaux 9 à 16 positionnés sur les 8 sorties
- 1 piste mono en mode PanSpan 1X8, canaux audio 9 à 16
La piste octo vide ne sert qu'à insérer un SpatGRIS OSC qui active les positions 9-16 dans le ServerGRIS pour la piste suivante qui lui, envoie l'audio.
Vérification faite dans DP et Reaper. Dans Logic, la limitation d'un seul surround limite à une seule octophonie (qui doit être placée sur les canaux 1 à 8 obligatoirement), mais celle-ci fonctionne. Pas possible dans Live.
Je vais ajouter cette information dans le manuel afin d'expliquer cet usage extravagant de la combinaison SpatGRIS-ServerGRIS.

**Comment by Xon77** [comment]
Cet issue/info n'est plus d'actualité, puisque l'audio va être retiré du SpatGris et rebasculé exclusivement vers le serveur avec l'arrivée du LBAP.
