### ISSUE TITLE
Décalage de connexion dans Jack avec DP

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#118]
Depuis la dernière version, mes connexions se sont décalées dans Jack : dans ma session DP, mes sorties de subs qui sont normalement les dernières (63-64) se retrouve dans les canaux 1-2 dans les entrées du Serveur. Ainsi, toutes mes sorties sont décalées de deux. Peu importe si je redémarre le tout, que je déconnecte et reconnecte Jack dans le Serveur, on dirait que Jack à mémoriser ce branchement par défaut. La seule façon de corriger cela est d'ouvrir QJackCtl et de reconfigurer la connection manuellement. Bien que j'ai sauvegardé un réglage du bon branchement dans QJackCtl, je dois ouvrir l'application à chaque fois que je connecte Jack dans le Serveur afin de le charger. Je ne sais pas pourquoi ce changement s'est produit ni comment le renverser. Avez-vous une idée?

**Comment by led78** [comment]
Voici une image de ce qui apparait dans QJackCtl, selon le réglage que j'ai créé pour contourner le problème. Il m'apparait que c'est DP qui envoi les deux dernières sorties en premier.

![jack_mauvaisconnexion](https://user-images.githubusercontent.com/13606544/37918833-2dc51a42-30f0-11e8-9d11-6d1b255bb6b3.jpeg)

**Comment by Normandeau** [comment]
Cela m'est déjà arrivé et à Vincent également. La seule solution qu'on a trouvé, c'est d'effacer les Bundles de sortie au complet et de les refaire dans le bon ordre. Et de placer les pistes dans DP dans l'ordre correspondant aux Bundles.

Les Bundles ne peuvent pas avoir l'air de ceci:
![capture d ecran 2018-03-26 a 12 54 16](https://user-images.githubusercontent.com/8959779/37920482-f4202bd8-30f4-11e8-9739-32f7e573ed50.jpg)

Mais plutôt de ceci:
![capture d ecran 2018-03-26 a 12 54 40](https://user-images.githubusercontent.com/8959779/37920503-fe93a298-30f4-11e8-8584-85b1f06bd819.jpg)

**Comment by led78** [comment]
Pourtant je n'ai pas modifié aucune sortie depuis le début. Voici de quoi à l'air mon Bundle depuis plusieurs mois:
![jack_mauvaiseconnexion_2](https://user-images.githubusercontent.com/13606544/37920746-b3191b76-30f5-11e8-8f3d-e1818b54d935.jpeg)

**Comment by led78** [comment]
Je crois que ce qui est arrivé, c'est que j'ai déconnecté par erreur la piste des subs de Jack. Puisque c'est la seule piste qui s'y connectait, je crois que ça l'a déréglé l'ordonnance des pistes de sorties dans la session DP, indépendamment de ce qu'affiche les Bundles.

**Comment by Normandeau** [comment]
Problème spécifique à DP, notamment si on utilise les sorties auxilaires plutôt que des pistes audio. La balle est dans leur camp tellement il y a de problèmes avec les Bundle.
