### ISSUE TITLE
Images fantômes des numéros OSC silencieux

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#119]
Depuis la modification de la transparence des sources et des hp, on voit apparaître des images fantômes, dans le ServerGRIS, des pistes mises en silence dans le séquenceur.

Ici deux pistes actives ici (en rouge), les autres sont mutées (mais elles apparaissent en gris):

![capture d ecran 2018-04-03 a 13 33 35](https://user-images.githubusercontent.com/8959779/38266761-82672bdc-3747-11e8-8259-e838f648942b.jpg)

Ou encore ici: aucune piste active, toutes mutées (elles apparaissent en gris divers):
![capture d ecran 2018-04-03 a 12 50 46](https://user-images.githubusercontent.com/8959779/38266777-8b138c6c-3747-11e8-934b-1b14e8d2f4f0.jpg)

C'est bien l'audio qui détermine la présence des sources actives?
On sait par ailleurs que l'OSC est toujours envoyé au ServerGRIS, même lorsque les pistes sont mutées. Est-ce que cela qui déclenche l'activité visuelle?

**Comment by Normandeau** [comment]
Confirmation: c'est bien l'OSC qui déclenche les images fantômes. J'ai vérifié en décochant l'option Osc Active active dans les SpatGRIS et les images fantômes disparaissent en même temps. Il y a donc un coulage entre l'OSC et l'audio pour faire apparaître l'activité des sources dans le ServerGRIS.

**Comment by belangeo** [comment]
C'est réglé. Sous un certain niveau (lorsque le canal alpha est sous la barre de 0.01), la source n'est simplement plus dessinée.

**Comment by Normandeau** [comment]
V212
Les images fantômes apparaissent encore lorsqu'on sélectionne Show Numbers dans View. Dans cet exemple, la séquence roule, mais il n'y a pas de son. On voit bien certains des numéros des pistes silencieuses:

![Capture d’écran, le 2020-07-12 à 08 50 24](https://user-images.githubusercontent.com/8959779/87246713-12feb700-c41d-11ea-8689-a0bf91dc868d.jpg)

**Comment by NicolaGiannini** [comment]
V212
Je confirme. J'ai noté que dans mon cas les numéros des sources en gris ne sont visibles que si les sources sont placées sur un haut-parleur.

**Comment by Normandeau** [comment]
V214
Toujours présent.

**Comment by Normandeau** [comment]
V215
Impossible à tester, l'OSC est toujours active dans ControlGRIS. Je viens de mettre une issue.

**Comment by Normandeau** [comment]
V217
Toujours présent.

**Comment by Normandeau** [comment]
V2110
Ici, même sans avoir coché Show Numbers, on aperçoit l'ombre des sources muettes:

![Ombre des sources](https://user-images.githubusercontent.com/8959779/121240354-3a961380-c868-11eb-9386-bb7dbbabd296.jpg)

**Comment by Normandeau** [comment]
Et même très pâles, en couleur:

![Ombre des sources très pâles](https://user-images.githubusercontent.com/8959779/121243452-b9408000-c86b-11eb-9299-09c11f78ece3.jpg)

**Comment by Normandeau** [comment]
V2111
Réglé dans cette version. Incroyable, une issue qui date du 3 avril 2018!!!
