### ISSUE TITLE
How to compile ServerGris under linux

### ISSUE THREAD

**Issue by belangeo** [GRIS-UdeM/ServerGRIS#120]
We need to add a tutorial somewhere (maybe in the manual or on a wiki) about compiling the ServerGris under linux (at least for debian-based distros, but it should be very similar under fedora or arch).

**Comment by Normandeau** [comment]
Olivier: commentaire écrit le 9 avril 2018. Toujours d'actualité?

**Comment by SamuelBeland** [comment]
Les instructions de compilation dans le README sont suffisantes.
