### ISSUE TITLE
32 canaux par défaut par client (au lieu de 128)

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#122]
Réduire le nombre de canaux par défaut par client à 32, au lieu des 128 actuels.

**Comment by Normandeau** [comment]
• Ne pas oublier cela dans la prochaine version. ServerGRIS nous ramène toujours les 128 entrées par défaut ce qui est très taxant en terme de CPU si on l'oublie. 
• Et chaque fois qu'on rafraichit le On/Off du client, c'est 128 qui est ramené.
• Cette valeur n'est pas gardée en mémoire lorsqu'on sauvegarde le document Server.

**Comment by belangeo** [comment]
Je suppose que ça a rapport avec les variables "virtual input/output channels" de JackRouter. Sous linux, le ServerGris utilise bel et bien le nombre de sorties configuré dans le client. Dans les préférences Reaper, j'ai 16 ins / 16 outs et le serveur utilise 16 entrées. Si je démarre pyo avec 18 canaux, le serveur assigne ensuite les entrées 17 à 34.

Je vais faire des tests sour MacOS pour voir ce qu'il se passe.

**Comment by belangeo** [comment]
En effet, sous MacOS, à l'exception de DP qui fait à sa tête, lorsqu'on assigne JackRouter comme pilote audio à une application (testé avec Reaper et Live), c'est la valeur donnée aux "virtual inputs/outputs numbers" qui est utilisée. Est-ce que je descend à 32 (avec une note dans le manuel sur comment augmenter le nombre d'entrées/sorties virtuelles) ?

**Comment by Normandeau** [comment]
Version 202
Effectivement c'est descendu à 32. Sauf que la valeur entrée dans Inputs devient automatiquement 32 lorsqu'on active ou désactive le client. Ainsi, si j'ouvre un document avec seulement 24 entrées et que j'ouvre Reaper et que je l'active, le nombre d'entrées du server passe automatiquement à 32. Et si je les ramène à 24, et que je désactive Reaper, ça repasse à 32.
Autrement dit, la valeur entrée dans Inputs est toujours outrepassée par la valeur par défaut du client qui est de 32.
On peut toujours redescendre la valeur à 24 après avoir activé Reaper me direz-vous. Mais l'usager pourrait s'attendre que ce soit un réglage sur lequel il a un contrôle, ce qui n'est pas le cas actuellement, sauf temporairement. Car même après avoir sauvegardé et fermé le tout, à la réouverture, dès que le client est activé, le nombre d'inputs passe à 32.

**Comment by belangeo** [comment]
C'était une demande de l'un d'entre vous que le nombre d'entrées s'adapte automatiquement en fonction du canal maximum utilisé par les clients. L'idée était de ne pas louper de signaux sans comprendre pourquoi... Qu'est-ce qui est mieux?

**Comment by Normandeau** [comment]
Version 202
La valeur de 32 est problématique. Je pensais qu'on pouvait dissocier la valeur par défaut de la valeur virtuelle. Autrement dit, laisser la valeur virtuelle à 128, mais la valeur par défaut à 32. Celle-ci s'afficherait dans Available et serait modifiable jusqu'à 128.
Parce que si je comprends bien, actuellement le seul moyen d'augmenter la valeur virtuelle est d'aller ouvrir JackPilot et de changer les valeurs virtuelles de celui-ci, exact?
Est-ce qu'on veut cela? Je ne le pense pas. On ne veut pas que les utilisateurs aient à jouer dans Jack.
Si on ne peut pas dissocier la valeur par défaut de la valeur virtuelle, je préfère revenir à 128. Sinon, je crains que le nombre 32 soit perçu comme une limitation de notre système, ce qui n'est pas le cas.
Ce qui est important de saisir ici c'est la quantité de CPU demandé. Le nombre d'entrées et de sorties virtuelles de Jack ne charge pas le CPU. Par contre, le nombre d'Inputs du ServerGRIS le fait. Or comme cette valeur est déterminée par la valeur virtuelle, quand on met en marche un Client, c'est 128 Inputs qui sot automatiquement mis en œuvre, donc beaucoup de CPU. L'usager moyen n'y prêtera pas attention car cela est la valeur par défaut de notre système, mais il va surcharger inutilement le CPU de son ordi alors qu'en fait il y a peu de chances qu'il utilise réellement les 128 entrées par défaut.
Pour information, ServerGRIS seul, sans activité, sur mon ordi:
- 8 Inputs: Jack 3,1%
- 16 Inputs: Jack 4,1%
- 24 Inputs: Jack 5,01%
- 32 Inputs: Jack 6,2%
- 64 Inputs: Jack 8,5%

**Comment by Normandeau** [comment]
Version 202
La valeur de 32 est problématique. Je pensais qu'on pouvait dissocier la valeur par défaut de la valeur virtuelle. Autrement dit, laisser la valeur virtuelle à 128, mais la valeur par défaut à 32. Celle-ci s'afficherait dans Available et serait modifiable jusqu'à 128.
Parce que si je comprends bien, actuellement le seul moyen d'augmenter la valeur virtuelle est d'aller ouvrir JackPilot et de changer les valeurs virtuelles de celui-ci, exact?
Est-ce qu'on veut cela? Je ne le pense pas. On ne veut pas que les utilisateurs aient à jouer dans Jack.
Si on ne peut pas dissocier la valeur par défaut de la valeur virtuelle, je préfère revenir à 128. Sinon, je crains que le nombre 32 soit perçu comme une limitation de notre système, ce qui n'est pas le cas.
Ce qui est important de saisir ici c'est la quantité de CPU demandé. Le nombre d'entrées et de sorties virtuelles de Jack ne charge pas le CPU. Par contre, le nombre d'Inputs du ServerGRIS le fait. Or comme cette valeur est déterminée par la valeur virtuelle, quand on met en marche un Client, c'est 128 Inputs qui sont automatiquement mises en œuvre, donc beaucoup de CPU. L'usager moyen n'y prêtera pas attention car puisque cela est la valeur par défaut de notre système, il nous fait confiance en cela. Mais dans les faits, il va surcharger inutilement le CPU de son ordi alors qu'il y a peu de chances qu'il utilise réellement les 128 entrées par défaut (je le sais, je l'ai vu à maintes reprises dans mes cours de composition).
Pour information, ServerGRIS seul, sans activité, sur mon ordi:

    8 Inputs: Jack 3,1%
    16 Inputs: Jack 4,1%
    24 Inputs: Jack 5,01%
    32 Inputs: Jack 6,2%
    64 Inputs: Jack 8,5%
    128 Inputs: Jack 13,56%
    Comment puis-je avoir plus de 32 Inputs, si on est limité à 32 entrées virtuelles?

Comparaison avec Version 201 (Virtuelles: 128):

    8 Inputs: Jack 1,8%
    16 Inputs: Jack 2,4%
    24 Inputs: Jack 3,0%
    32 Inputs: Jack 3,4%
    64 Inputs: Jack 6,1%
    128 Inputs: Jack 11,3%

**Comment by Normandeau** [comment]
V203
Le nombre de canaux disponibles (Available) est toujours à 128 avec Reaper et Logic. Par contre, le fait de changer le nombre réel de canaux utilisés (différence entre Start et End) ne change plus automatiquement la valeur des Inputs lorsqu'on active le Client sauf quand le le nombre de canaux réels (par exemple 64) est supérieur au nombre de Inputs (par exemple 32). Alors là, lorsqu'on active le Client (On/Off), le nombre d'Inputs change automatiquement à la même valeur (soit ici, 64). Ce qui est tout à fait conséquent.
Excellent. Mais 32? Je ne vois nulle part cette valeur par défaut,
Réglé.
