### ISSUE TITLE
Taille de la fenêtre: possible de sauvegarder

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#123]
Est-il possible de sauvegarder la taille de la fenêtre du dernier ServerGRIS ouvert? Ce serait très utile, car sinon, chaque fois qu'on ouvre un projet, c'est avec la taille par défaut. Lorsqu'on travaille sur un projet avec beaucoup de pistes, c'est juste agaçant de devoir agrandir les fenêtres chaque fois. Car il faut ajuster indépendamment la fenêtre des h-p et celle des inputs-outputs.
Donc j'imagine que correctement formulée, la question serait plutôt: possible de sauvegarder la taille **des** fenêtres?

**Comment by belangeo** [comment]
Pas de problème!

**Comment by Xon77** [comment]
La taille des fenêtres est désormais bien sauvegardée avec le projet.
