### ISSUE TITLE
Détails graphiques: barres de défilement et fenêtre 2D

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#124]
Dans le ServerGRIS, il est possible, lorsqu'on est obligé de réduire la fenêtre de celui-ci, de naviguer avec les barres de défilement horizontales et verticales. Cependant je note ces jours-ci qu'avec une Magic Mouse ou le trackpad dans un petit écran (je viens de commander un 4k pour le 187...) que les barres de défilement **horizontales** réagissent de la même manière que l'on fasse un mouvement horizontal ou vertical et cela, peu importe où on est situé dans la fenêtre du ServerGRIS.
De l'autre côté, la barre de défilement **verticale** ne réagit que si on place le pointeur exactement sur celle-ci, ce qui correspond à environ un espace d'une largeur de 1 mm sur l'écran. Faut avoir du visou!!!
Donc il serait préférable que les barres horizontales réagissent exclusivement au mouvement horizontal et que la barre verticale réagisse exclusivement au mouvement vertical, peu importe où la souris est placée dans la fenêtre du serveur.

![capture d ecran 2018-06-02 a 09 32 02](https://user-images.githubusercontent.com/8959779/40876926-c46c50cc-6648-11e8-95d4-5a22cf07e6a3.jpg)

**Comment by Normandeau** [comment]
Si j'ouvre la fenêtre 2D, et que je la place devant le ServerGRIS quelque part en petit format (parce l'écran est petit), dès que je touche la fenêtre principale du serveur, la 2D disparait en arrière-plan. Il n'y a pas moyen de la faire revenir au premier plan, sauf si je la rappelle avec Option-D. Mais alors elle revient à son grand format d'origine à un emplacement par défaut. Si elle pouvait juste revenir à l'endroit où elle se trouvait (et où elle se trouve toujours en arrière-plan d'ailleurs), ça éviterait de devoir la replacer chaque fois.

![capture d ecran 2018-06-03 a 08 41 21](https://user-images.githubusercontent.com/8959779/40886645-f26ff21e-6709-11e8-9ffe-cba149b3d863.jpg)

**Comment by belangeo** [comment]
Scrollbars: Désolé, Juce ne nous donne pas de pouvoir sur le comportement des scrollbars. Par contre, j'ai augmenté leur taille, ce qui devrait permettre de les attraper plus facilement!

Fenêtre 2D: C'est fait. Elle conserve sa taille et sa position tant que le ServerGris est ouvert.

**Comment by Xon77** [comment]
Pour moi, la taille des scrollbars est correcte et la fenêtre 2D conserve sa taille, lorsqu'elle est rappelée avec option + D. Je laisse cependant à @Normandeau le soin de fermer cet issue, puisque le comportement des scrollbars ne peut être changé.

**Comment by Normandeau** [comment]
Bin correct!
