### ISSUE TITLE
Recording: ajouter la possibilité d'enregistrer un fichier interfolié

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#125]
Dans la perspective d'ajouter une fonction de lecture dans le ServerGRIS, il sera important d'ajouter la possibilité de faire des enregistrements en format interfolié, afin de simplifier les étapes d'enregistrement/lecture (pour le moment, l'enregistreur ne génère que des fichiers mono). Par exemple, un compositeur enregistre sa pièce en 16.2 et l'envoie ensuite à un collègue qui lit ce fichier directement dans le serveur, sans avoir à répartir les différentes pistes indépendantes.
Afin de rendre cette fonction standard, lors de la lecture d'un fichier la spatialisation des 16 canaux devrait adopter la forme du Speaker Setup par défaut, soit celle du studio Hexa (il faudrait ajouter les deux subs dans cette configuration par défaut. Je fais une autre issue à cet égard). Autrement dit, quelque soit le dispositif final utilisé lors de l'écoute, les 16 canaux d'un fichier multicanal occuperont l'espace selon le modèle Hexa.

**Comment by belangeo** [comment]
J'ai besoin d'une petite clarification ici... Est-ce qu'on parle d'une fonctionnalité du style "Export in 16:2 standard format", peut importe le setup courant ? Ou bien de la possibilité de générer un fichier multi-canaux, en tenant compte du nombre de pistes de sortie du setup ?

Dans le second cas, il suffirait seulement de faire un petit post-processing qui reprend tous les fichiers mono produits et les interfolie dans un fichier multi-canaux (probablement 100x plus vite que le temps réel).

Le premier cas (le plus important je suppose pour la diffusion des oeuvres) est un peu plus subtil. À l'activation de cette fonction, il faudrait substituer le setup courant par le defaut_speaker_setup, produire l'enregistrement, puis restituer le setup précédent.

**Comment by belangeo** [comment]
Une autre petite question! Est-ce que le modèle du studio Hexa est le modèle le plus commun ?

**Comment by led78** [comment]
«Une autre petite question! Est-ce que le modèle du studio Hexa est le modèle le plus commun ?»

Réponse: non.

En ce qui à trait au nombre d'hautparleur, c'est très variable. Mais en général ça tourne autour de 30 hautparleurs. Donc, je dirais que le dôme de 32 hautparleurs est plus représentatif de la plupart de des dômes. Pour la position relative des hautparleurs et l'ordre de chiffrage, c'est encore plus variable d'un dôme à l'autre.

**Comment by belangeo** [comment]
Je vois... C'est surtout au niveau de l'ordre de sortie que je me questionne. D'un studio à l'autre, avec une configuration par défaut, les trajectoires ne seront pas les mêmes (le problème ne se pose pas pour le binaural). Je suppose qu'il n'y a pas de configuration parfaite...

Pour ce qui est du nombre de sorties, on a déjà établit qu'on tentait d'imposer un standard à 16 HPs dans un premier temps, puis qu'on pourrait ensuite proposer un second standard à 32 HPs (ça double quand même le nombre de convolutions à effectuer pour le HRTF).

**Comment by Normandeau** [comment]
Quelques précisions.
David est chanceux de pouvoir jouer ses pièces sur des systèmes de 30 hp et plus! Mon expérience est plutôt du genre 12, 13, 16 hp... sauf quand je peux jouer à la fac ou au ZKM!
Cela dit, je rappelle un principe fondamental ici: l'idée n'est pas de jouer le format standard sur des hp, mais d'encoder et de décoder les pièces dans un format standard destiné à la circulation des œuvres multicanal pour l'écoute individuelle en format binaural. WYHWYG: what you hear is what you get.
Le format standard reste à déterminer, mais si on part à 32 hp, pour une pièce 15-20 minutes, ça commence à être lourd pour la transmission. C'est pourquoi je proposais 16+2 hp. La configuration d'Hexa n'est peut-être pas optimale mais elle serait juste plus pratique pour nous, car on pourrait aussi jouer ces pièces directement sur les hp du studio (et puis ça propage la signature du studio un peu partout dans le monde). Mais peut-être qu'un dôme de type 8-5-3 +2 subs serait mieux équilibré en terme de VBAP. Ça reste à déterminer.
Pour ce qui est des concerts, les compositeurs devront enregistrer leurs pièces en fonction de chacun des dispositifs installés dans les différentes salles de concert, bien évidemment.

**Comment by Normandeau** [comment]
Enregistrement interfolié c'est réglé. La suite de la discussion avec l'Issue #109.
