### ISSUE TITLE
Ajouter deux sorties directes pour les subs au modèle par défaut actuel

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#126]
Dans l'idée de proposer un standard de circulation des œuvres multipistes, il faut ajouter les deux subs dans la configuration par défaut. Les dômes de hp sont presque toujours constitués de petits hp qui ne contiennent que très peu de graves (les K&F du studio 187 ne descendent qu'à 70 Hz par exemple). Il est donc essentiel d'avoir une piste grave dans une version standard:

![capture d ecran 2018-06-10 a 08 47 22](https://user-images.githubusercontent.com/8959779/41201717-f1170318-6c8a-11e8-9a50-916c745609e5.jpg)

**Comment by Xon77** [comment]
2 sorties directes pour les subs ont bien été ajouté au modèle par défaut actuel de 16 HP.
