### ISSUE TITLE
Format d'enregistrement toujours wav

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#127]
Le format wav est toujours le format d'enregistrement par défaut, même si c'est AIFF qui est sélectionné dans les Preferences. Pour obtenir un fichier AIFF, il faut d'abord sélectionner WAV, puis à nouveau AIFF pour que celui-ci soit actif. Ce serait mieux si le format affiché dans les Préférences était celui de l'enregistrement.

**Comment by Xon77** [comment]
Le format d'enregistrement correspond désormais bien à celui indiqué dans les préférences.
