### ISSUE TITLE
Speaker setup generation algorithms

### ISSUE THREAD

**Issue by belangeo** [GRIS-UdeM/ServerGRIS#21]
Dans le "monde d'édition idéal de speaker setups", il serait intéressant de pouvoir générer automatiquement les coordonnées des HP et donc des configurations de dôme complexes (pouvant être éventuellement déformées) grace à quelques arguments :
•	nb de couronnes et pour chaque couronne :
•	nb de HP et élévation / couronne
•	Position de l'angle du 1er HP pour chaque couronne

A partir de ces infos, un speaker setup serait généré "de manière équidistante" et éditable pour l'adapter...

**Comment by Normandeau** [comment]
Oui!!!
Dans le mode VBAP au moins, comme on fabrique des couronnes de hp — par exemple le setup du CUBEFest est fait de 4 couronnes, respectivement de 18, 16, 12 et 8 hp — je connais donc dès le départ l'angle qui sépare chacun des hp. Donc on pourrait déjà avoir une première boite qui indique le décalage angulaire de chaque nouveau hp qu'ajoute au setup. Et une deuxième boîte qui indique le rayon de chaque nouveau hp. Comme il sont équidistants, il ne resterait plus grand chose à faire.
(Il y a ça dans le Zirkonium, sauf que c'est une valeur par défaut non ajustable (36˚, pour un total de 10hp équidistants par couronne. Qui a choisi cette valeur!?!).)
