### ISSUE TITLE
DP et Jack: inadéquation entre les canaux audio

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#27]
Il y a un fonctionnement étrange dans DP que l'on ne retrouve pas dans Logic et Reaper. Pour pouvoir utiliser une entrée de Jack dont le chiffre est élevé, par exemple les valeurs 63 et 64, il faut que toutes les valeurs intermédiaires soient actives. Autrement dit, il faut 62 canaux actifs pour que DP envoie du signal à 63-64. Sinon, les canaux 63-64 sont acheminés vers les premiers disponibles, comme ici, 43-44 (on remarquera que les pistes au-dessus de 63-64 s'arrêtent à 42).
Par ailleurs, DP ne prend pas en compte le nombre d'entrées-sorties virtuelles de Jack. Remarquez le nombre sous Available: il est de 44, correspondant aux canaux actifs. Dans Logic et Reaper, ce nombre est de 128, correspondant au nombre déterminé (manuellement par moi) dans les entrées-sorties virtuelles dans Jack.
Cela a une autre conséquence qui est la suivante: si le SpatGRIS de 63-64 est réglé sur les canaux OSC 63-64, on voit bien ceux-ci se déplacer dans la fenêtre 3D, mais comme l'audio est acheminé directement aux entrées-43-44 de Jack, il n'est plus spatialisé. C'est un peu le bordel!

Tout ceci est plus une considération de manuel, car nous n'y pouvons pas grand chose. 
C'est le même comportement dans le kit Jack-Zirkonium-Séquenceur: les 128 entrées-sorties virtuelles sont disponibles pour tous les clients, sauf DP.

![dp virtual jack](https://user-images.githubusercontent.com/8959779/28623681-bfa861a6-71e4-11e7-880d-b7ee9d4398f2.jpg)

Dans Logic:

![capture d ecran 2017-07-26 a 09 36 32](https://user-images.githubusercontent.com/8959779/28625323-dce5b624-71e9-11e7-89f4-da37b83cefed.jpg)

Dans Reaper:

![capture d ecran 2017-07-26 a 09 38 25](https://user-images.githubusercontent.com/8959779/28625337-e5cbfa1e-71e9-11e7-8b85-1f1978dcd607.jpg)

**Comment by led78** [comment]
J'ai constaté le même problème hier en ouvrant ma session DP avec le SpatServer. Mais je n'avais pas ce problème avec Zirkonium, cependant.

**Comment by led78** [comment]
Pour une raison que j'ignore, il arrive que Jack ne connecte pas les sorties du DAW consécutivement, c'est-à-dire en suivant le même ordre que les numéros de sortie de celui-ci. Moi et Robert avons observé ce phénomène précédemment, que ce soit avec Logic ou DP, on a beau redémarrer le tout et recommencer le branchement dans Jack, il y a des connections qui se croisent et on se retrouve avec des sorties mal branchée qui ne correspondent pas à du 1 pour 1. À ce moment là, nous n'avions d'autre choix que de refaire tout le branchement de A à Z manuellement, d'une sortie du DAW à son entrée correspondante dans le Zirkonium. Avoir le patchbay de Jack était utile pour constater cette erreur de branchement et la corrigé.
Or, depuis hier je constate que, peu importe la sortie que je sélectionne dans le DAW, peu importe que je ferme et réouvre le tout dans l'ordre, que je redémarre tout, le ServerGris gardait toujours le même ordre de branchement qui envoyait mes sorties 13 à 16 de DP vers les entrées 1 à 4 du Server. J'ai donc décider d'ouvrir Jack Pilot, avec le Zirkonium, pour pouvoir visualiser le branchement automatique de Jack. En ouvrant ensuite DP et en le connectant automatiquement aux entrées de DP, je constate effectivement qu'il y a erreur de branchement.
![erreur de branchement dans jack](https://user-images.githubusercontent.com/13606544/29126586-c7b87ba2-7cec-11e7-8984-541f32c99449.jpeg)

Malgré le fait que l'on veuille garder le tout le plus transparent possible, je crois qu'il devient tout de même essentielle de rendre disponible la correction manuelle des connections dans Jack via le Server si jamais le besoin se présente. Car présentement, je n'arrive pas à corriger ce problème autrement qu'en passant par Jack > Zirkonium > DP. Je ne peux donc pas travailler directement dans le ServerGRIS.
Je vais corriger la connection dans JackPilot et ensuite réessayer d'ouvrir le ServerGRIS pour voir si mes changements restent. Habituellement non, il faut toujours recharger la sauvegarde du branchement, ce que le patchbay de QJack CTL permet de faire automatiquement cependant.

**Comment by led78** [comment]
En faisant les corrections, je constate que l'erreur ne viens pas de Jack, mais bien de DP qui envoi les sorties 13 à 16 en premier. Pourquoi? Je ne le sais pas.
![erreur de branchement dans jack_02](https://user-images.githubusercontent.com/13606544/29127277-a112f30e-7cee-11e7-9a38-ad15cb8db90d.jpeg)
Ça ne semble pas lier à l'ordre des sorties affichées dans le menu Bundles de DP.
![erreur de branchement_dp](https://user-images.githubusercontent.com/13606544/29127387-e4b0b074-7cee-11e7-8dd7-32a6a57d1557.jpeg)
Quelqu'un a une idée?

**Comment by Normandeau** [comment]
Se peut-il que ces sorties soient les premières utilisées dans ta session?

Envoyé de mon phoni




Envoyé de mon phoni

**Comment by led78** [comment]
Je sais que lorsque j'ai initialement ouvert ma session DP avec le ServerGRIS, ma piste Quad correspondant aux sortie 13 à 16 recevait en entrée les bus 1 à 4 (pistes AUX 1 à 4) qui sont aussi assignées aux sorties 1 à 4. J'imagine que le problème viens de là. Mais une fois cette assignation modifiée dans DP - la piste Quad 13-16 ne reçoit plus les bus 1-4 - celui-ci les envoi quand même en premier dans Jack. C'est donc bien un problème de DP comme le dit Robert.

**Comment by Normandeau** [comment]
Dans DP Il faut que La succession de tes sorties correspondent à des valeurs consécutives en partant de 1
Tu ne peux pas inverser les sorties ni sauter des numéros 


Envoyé de mon phoni

**Comment by led78** [comment]
Puisque je ne vois pas pour l'instant comment corriger cela dans DP - toute mes sorties sont consécutives en partant de 1 d'après ce que je vois dans Bundles - pour l'instant, je vais faire les corrections dans Jack.

**Comment by Normandeau** [comment]
C'est une situation avec DP.
Mis une note dans le manuel.
