### ISSUE TITLE
Enregistreur et formats d'enregistrement des fichiers audio

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#29]
R: N’y a-t-il pas une fonction d’enregistrement dans SpatServer?
O: Cette fonction est supposé être active, il y a un petit bouton marqué
"R" à côté du menu "Mode".
R: Je viens de tester rapidement.
Huit pistes audio en entrée, 54 haut-parleurs + 4 subs, durée 5 minutes: impeccable!
Par contre, en situation plus corsée, avec 44 pistes audio, 54 haut-parleurs + 4 subs sur une durée de 15 minutes, tout semblait bien se dérouler, mais après la fin de la durée prévue d’enregistrement, soit 15 minutes, la fenêtre de sauvegarde s’est ouverte, j’ai nommé le fichier et… je ne l’ai jamais trouvé sur mon disque dur!
O: On dirait une question de taille de fichier.
58 pistes * 15 minutes * 5 Mb la minute = 4,35 Gig. Le WAV standard,
je crois pas qu'il peut faire ça. Le WAVX oui, il me semble, peut-être
le AIFF.

**Comment by Normandeau** [comment]
Tests plus avancés
44 pistes audio, 54 hp + 4 subs, 24bits/48kHz
Fichier audio résultant: wav 7,52Gb
Excellent à priori!
Excepté que les pistes suivantes, correspondants aux hp équivalents, étaient silencieuses:
- 1-2
- 4-5
- 7-8
- 10-11-12
- 14-15
-17-18-19-20
-22-23
-25-26
- 28-29
- 31-32-33-34
- 36-37
- 39-40-41
- 43-44
-46-47
- 49-50-51
- 53-54
- 56-57

**Comment by led78** [comment]
On a soulevé ce problème à quelques reprises lors de discutions formelles et informelles depuis quelques temps. C’est le problème auquel j’ai fais face l’an passé lorsqu’est venu le temps de faire un rendu de 54 sorties HP d’une pièce de 13m20 à 48kHz/24bits. Autrement dit, dans la plupart des cas, les formats WAV et AIFF ne seront pas utilisables pour enregistrer les sorties HP puisque ceux-ci ont une limite quant à la taille du fichier sauvegardé. Dans Twisted Wave, on reçoit un message d’erreur qui nous invite à sauvegarder dans un autre format que WAV ou AIFF lorsque la taille dépasse 4Go. Dans d’autres cas, l’enregistrement se poursuit, mais le fichier résultant est incomplet. Bref, il faut donc que l’enregistreur du Server offre un choix de format de fichier différent ou offre la possibilité de sauvegarder chaque sortie en fichier mono séparé, mais correctement nommé selon le HP correspondant - dans tout les cas, il faudrait que chaque piste soit identifiée selon le HP de sortie. Enregistrer les sorties séparément est, je crois, la seule façon d’utiliser les formats WAV ou AIFF (qui peuvent être nécessaires dans le cadre d’une diffusion de concert). On pourrait ensuite sauvegarder ces fichiers mono en un seul fichier TAR(?).

Voici quelques formats ayant une capacité supérieur à 4Go:
- WAV64 (lecture possible directement dans Reaper, ce qui est très pratique pour la diffusion)
- RF64
- BWF
- CAF (format Apple fonctionnant avec Sountrack Pro et Logic)
- FLAC (8 canaux max)
- ALAC (8 canaux max)
- MPEG-H (en développement pour l’audio 3D notamment)

**Comment by Normandeau** [comment]
Actuellement, la taille et le format de fichier ne semble pas en cause. Comme décrit plus tôt, j'ai enregistré deux fois avec succès une sortie 54 hp + 4 subs. Une première fois une durée de 5 minutes et une seconde fois, une durée de 15 minutes. Cette dernière comprend toutes les pistes et pèse 7,52 Gb, mais certaines pistes sont silencieuses. Et TwistedWave n'a aucun problème à ouvrir et à jouer le fichier.
Alors ce qu'il nous faut, c'est de faire des tests maintenant. 
- À partir de quelle durée cela pose-t-il un problème (disons, jusqu'à 30 minutes)?
- Y a-t-il un nombre maximal de pistes (je dirais: contentons-nous de tester à des valeurs inférieures à 64 hp pour le moment)?
Et mettre ici les résultats des tests, pas celui des discussions...

**Comment by belangeo** [comment]
Je viens de modifier le comportement de l'enregistrement pour générer des fichiers mono (avec incrément inséré dans le nom) lorsqu'un fichier .wav est sauvegardé. Le format .aif continue de générer un fichier multi-canaux, afin de pouvoir comparer les deux méthodes. Ce sera dans le prochain build vers la fin de la semaine.

**Comment by Normandeau** [comment]
La fonction d'enregistrement en fichiers mono .wav semble fonctionner. Sauf que les fichiers générés commencent à 000, et non pas à 001, comme dans piste no 1. Cela peut porter à confusion très rapidement. Il vaudrait mieux que la série de fichiers portent le no de la piste Output ce qui joindrait l'utile à l'agréable, car ce no correspond à la sortie de l'interface graphique utilisée.
Quand on a le choix des sorties sur 124 possibilités, très pratique pour s'y reconnaître!
Je ne vois pas de fonction aiff.

**Comment by belangeo** [comment]
Ok, ça commence à 1 maintenant. À moins d'erreur grossière de ma part, c'est bien le numéro de sortie de l'interface qui est utilisé pour le nom des fichiers.
Pour générer un fichier AIFF, il suffit de donner un nom de fichier avec l'extension ".aif" !

**Comment by Normandeau** [comment]
Deux choses ici:
- le format aiff se semble pas supporté:

![capture d ecran 2017-08-11 a 14 07 01](https://user-images.githubusercontent.com/8959779/29226078-ae8ed226-7e9e-11e7-9bb5-98c9a834a9d9.jpg)

Les numéros des pistes sont consécutifs (1, 2, 3, etc) et indépendants des numéros des Outputs. Il serait préférable que ce soit les numéros des outputs.

**Comment by Normandeau** [comment]
En fait l'enregistrement ne fonctionne pas vraiment. Ça enregistre des pistes, mais c'est imprévisible comme résultat. La seule chose qui est prévisible c'est qu'il manque toujours quelque chose:

68 pistes, 18 haut-parleurs, durée 2 minutes:

![capture d ecran 2017-08-11 a 16 40 10](https://user-images.githubusercontent.com/8959779/29231277-9cf444f4-7eb4-11e7-86b5-47e8338a6f4d.jpg)

Ou encore 68 pistes, 18 haut-parleurs, durée 10 minutes:

![capture d ecran 2017-08-11 a 16 48 20](https://user-images.githubusercontent.com/8959779/29231367-ef02a86c-7eb4-11e7-8c7f-2c39ee2e6f25.jpg)

**Comment by Normandeau** [comment]
Finalement j'ai dû me résoudre à utiliser le Zirkonium.
DP: 68 pistes en sorties et 18 pistes en entrées pour enregistrer;
Zirkonium: 68 pistes en entrée (je pensais que c'était limité à 64...) et 18 pistes en sorties;
Jack qui gère tout cela.
78% de CPU...

**Comment by belangeo** [comment]
La différence principale entre le Zirkonium et le ServerGRIS est que le Zirkonium enregistre directement sur le disque alors que le ServerGRIS enregistre en RAM puis sauvegarde sur le disque après le processus. J'avais des doutes concernant la quantité de RAM qui doit être allouée pour garder le tout mémoire mais manifestement il semble se passer des choses étranges de ce côté. Je vais faire une version qui écrit directement sur le disque (de toute façon, avec les disques ssd, l'accès au disque n'est plus un proble pour la performance) et on verra si ça fonctionne mieux.

**Comment by Normandeau** [comment]
**Version 006**
Session DP 44 pistes (40+4 sorties directes);
Server: 64 Inputs-58 Outputs (54+4 subs).
La nouvelle fonction d'enregistrement semble mieux fonctionner à ceci près que:
- l'enregistrement génère automatiquement 128 pistes en .wav seulement, que aiff ou wav soit sélectionné. Elles ne comprennent pas toutes de l'audio, car seules celles qui correspondent aux hp du setup en contiennent. 
- lorsque la fin de l'enregistrement arrive, la boîte Jack Run (en %) du Server flash en rouge et envoie une information à DP qui génère le signal d'overload de CPU.

Session DP 44 pistes (40+4 sorties directes);
Server: 64 Inputs-18 Outputs (16+2 subs).
- l'enregistrement génère 18 pistes en .wav seulement, que aiff ou wav soit sélectionné.

Session DP 44 pistes (40+4 sorties directes);
Server: 64 Inputs-34 Outputs (32+2 subs).
- l'enregistrement génère automatiquement 64 pistes en .wav seulement, que aiff ou wav soit sélectionné. Elles ne comprennent pas toutes de l'audio, car seules celles qui correspondent aux hp du setup en contiennent (c'est le setup du dôme 32 de la fac, donc les pistes 5-6 correspondants aux subs ont de l'audio et ensuite ça commence à 31, soit les sorties MADI de la UFX+).
- lorsque la fin de l'enregistrement arrive, la boîte Jack Run (en %) du Server flash en rouge et envoie une information à DP qui génère le signal d'overload de CPU.

PS J'ai réussi à avoir des fichiers aiff une seule fois. Depuis ce sont toujours ds fichiers wav qui s'enregistrent.

128 pistes:
![capture d ecran 2017-08-18 a 16 17 43](https://user-images.githubusercontent.com/8959779/29476234-0132e91c-8431-11e7-9391-f45a9e40520d.jpg)

**Comment by Normandeau** [comment]
**Version 006**
Session Reaper 44 pistes (40+4 sorties directes) (même session que pour DP).

Server: 64 Inputs-58 Outputs (54+4 subs).
Dispositif de Virginia Tech avec 128 numéros de hp (124 hp + 4 subs).
- l'enregistrement génère automatiquement 128 pistes en .wav seulement, que aiff ou wav soit sélectionné. Elles ne comprennent pas toutes de l'audio, car seules celles qui correspondent aux hp du setup en contiennent.
- lorsque la fin de l'enregistrement arrive, la boîte Jack Run (en %) du Server flash en rouge. Reaper ne semble pas affecté par cela.

Server: 64 Inputs-18 Outputs (16+2 subs).
- l'enregistrement génère 22 pistes en .wav seulement, que aiff ou wav soit sélectionné.
Les 22 pistes semblent correspondent aux 22 sorties de la UFX: 1 à 8 pour les 8 premiers hp, 9-12 ne sont pas utilisées (phones 1 et 2), 13-14 pour les subs et 15-22 pour les 8 autres hp. Dans le  Speaker Setup c'est comme cela que les sorties sont configurées.

Donc le Server va toujours chercher le numéro de sortie le plus élevé de la configuration et enregistre toutes les pistes jusqu'à celle-ci, peut importe que certaines sorties ne soient pas utilisées.

**Comment by belangeo** [comment]
En effet, le serveur utilise le numéro de sortie le plus élevé pour générer tous les canaux audio. Ce ne devrait pas être trop difficile de filtrer les canaux vides pour l'enregistrement. Je vais vérifier pour la question du AIFF.

**Comment by Normandeau** [comment]
**Version 007**
- Format AIFF et WAV: un ou l'autre, ça fonctionne bien.
- Numéros des pistes: ça fonctionne aussi: les canaux enregistrés sont seulement ceux qui correspondent à des haut-parleurs et leurs numéros correspondent bien à ceux du patch. Les numéros inutilisés sont ignorés par l'enregistreur (par exemple les sorties 9-10 et 11-12, qui correspondent aux sorties d'écouteurs sur la UFX).
Excellent.
