### ISSUE TITLE
Certaines fonctions doivent être ajustées avec JackPilot

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#3]
J'ai d'abord désinstallé Jack afin de valider que celui-ci s'installait avec le Server mais cela ne fonctionne pas:

![capture d ecran 2017-06-27 a 13 31 36](https://user-images.githubusercontent.com/8959779/27601389-30592e62-5b3d-11e7-8b86-4285aedd3c67.jpg)

J'ai ensuite réinstallé Jack, et là ça fonctionne. Donc le Server ne fait qu'appeler Jack, qui doit déjà être installé, c'est bien cela?
Cependant, cela conduit à une situation où il n'y a que 2 entrées et 2 sorties disponibles dans Jack. Autrement dit, les valeurs d'entrées et sorties virtuelles de Jack ont été perdues lors de la désinstallation. Comme elles ne sont pas disponibles dans le Server, il faut donc tout fermer, rouvrir Jack manuellement, régler ses Preferences, démarrer Jack pour les valider, le désactiver, le fermer et rouvrir le Server.
Question: Nicolas m'avait parlé de ce problème que certains réglages de Jack n'étaient pas disponibles à partir du Server. Cela n'a donc pas été résolu si je comprends bien?

**Comment by Normandeau** [comment]
Pour mémoire:
Version 0.0.2
Même situation qu'avec la première version.
Dois-je en conclure que l’installer de SpatServerGRIS n’installe que les librairies nécessaires au fonctionnement de Jack sous celui-ci?
Mais que Jack doit être préalablement installé?
Réponse: oui.
Je viens de réinstaller Jack, et tout fonctionne à nouveau.
À mentionner avec l'installer.
Et fournir Jack avec celui-ci.

Réponse d'Olivier:
J'ai probablement trop strippé l'installation de jack... Sur le mac mini ça fonctionne mais c'est probablement parce qu'il trouve les frameworks de jack quelque part sur la machine. Je vais retirer les frameworks de l'application elle-même et inclure dans l'installeur tout ce que l'installeur de Jack contient. Ça, ça devrait fonctionner!

**Comment by Normandeau** [comment]
17-07-21
Nouvelle version (qui aurait pu s'appeler 0.0.3): Jack est installé et tout semble fonctionner... sauf que ça plante. J'étais surpris de voir qu'on ne nous demandait pas de redémarrer l'ordi, comme avec l'installeur autonome de Jack, mais bon, j'avais mis cela sur le compte des doigts de fée d'Olivier!
Malheureusement, dès le premier changement de Speakers Setup, Server s'est planté (avec DP connecté dessus). Fermé DP, rouvert Server, rien à faire, il se plante à nouveau. Redémarrage de l'ordi, et là ça fonctionne.
Donc, il semble qu'après l'installation il est mieux de prévoir un redémarrage.
Aussi, après avoir écrit le contenu de la parenthèse, je me suis dit que ce serait bien d'avoir le no de version dans la fenêtre principale, comme dans le plugiciel. Cette information est parfois cruciale, spécialement en mode de test. Avoir cette information dans la face évite de se tromper.
PS Cela n'enlève rien aux doigts de fée d'Olivier!

**Comment by Normandeau** [comment]
Bogue important: les entrées et les sorties virtuelles ne fonctionnent toujours pas à partir du Server.
On peut placer par exemple le nombre d'Input dans le Server mais cela n'informe pas Jack.
Les entrées et sorties virtuelles disponibles dans Jack sont celles qu'on peut déterminer grâce à JackPilot. Il n'y a aucun contrôle, ni aucune modification qui est fait à partir du Server pour cela.
J'ai pu vérifier cela car j'ai fait une erreur dans JackPilot. J'ai mis 124 au lieu de 128. Et DP ne m'offrait que 124 sorties alors que le Server était réglé à 128. J'ai pensé qu'il y avait une limitation à DP. 
J'ai contrevérifié le tout avec Reaper, et cela est confirmé (quoique Reaper affiche tout ce que tu lui demandes dans faire de critique! Cependant, même s'il t'offre 128 canaux, il n'y aura que ceux disponibles dans JackPilot qui vont fonctionner).
Aussi, je me suis aperçu que Reaper était limité à 64 canaux de sorties en tout et pour tout. Je ne savais pas cela (ou alors il me manque un réglage quelque part).

**Comment by Normandeau** [comment]
Ok, j'ai tout jeté: Jack et Server. Redémarrer le Mac.
Tout réinstaller. Redémarrer le Mac.

Ouvert des projets dans DP, Logic et Reaper.
Les trois me disent que j'ai 64 ou 66 sorties (...) disponibles dans Jack, ni 128, ni 256.

**DP:**
![capture d ecran 2017-07-22 a 20 31 59](https://user-images.githubusercontent.com/8959779/28493813-ad455c40-6f1d-11e7-9515-7ec31a485b79.jpg)

**Logic:**
![capture d ecran 2017-07-22 a 20 33 15](https://user-images.githubusercontent.com/8959779/28493816-ba94a6d0-6f1d-11e7-95df-fbac7da8e4f3.jpg)

**Reaper:**
![capture d ecran 2017-07-22 a 20 34 22](https://user-images.githubusercontent.com/8959779/28493818-c3625bf4-6f1d-11e7-834b-41f5027f940e.jpg)

Pourquoi 64 ou 66?
Peut-être est-ce relié à Soundflower qui est installé sur mon système?
Comme je n'ai pas d'interface multisorties, je simule cela avec SoundFlower pour vérifier les sorties.
Si je remets les Préférences à haut-parleurs internes, je n'ai plus alors que deux canaux audio disponibles (0 pour DP?!?):

**DP:**
![capture d ecran 2017-07-22 a 20 44 56](https://user-images.githubusercontent.com/8959779/28493869-2c24e6f6-6f1f-11e7-9c5e-14f55bef5836.jpg)

**Logic:**
![capture d ecran 2017-07-22 a 20 50 35](https://user-images.githubusercontent.com/8959779/28493886-7a36e722-6f1f-11e7-8e9c-a5daab4ebe3d.jpg)

Reaper:
![capture d ecran 2017-07-22 a 20 47 02](https://user-images.githubusercontent.com/8959779/28493878-4a60a452-6f1f-11e7-988d-a5455871c454.jpg)

Je n'ai pas ouvert Jack à priori.
Lorsque je l'ouvre, voici ses préférences, qui ne correspondent à rien, mêm la Fe n'est pas la bonne:
![capture d ecran 2017-07-22 a 20 35 12](https://user-images.githubusercontent.com/8959779/28493825-e2cef722-6f1d-11e7-85e7-de0a68aa911f.jpg)
Par contre si change les Preferences de Jack à Soundflower et à 128 canaux virtuels, là je retrouve tout ce qu'il me faut dans le Server:

**DP:**
On peut remarque seul DP donne l'heure juste avec les 96 canaux. Je me suis rendu que SpatGRIS n'autorise que 96 canaux OSC. Voir une nouvelle issue sur le site de SpatGRIS:
![capture d ecran 2017-07-22 a 20 54 01](https://user-images.githubusercontent.com/8959779/28493915-0fb835e4-6f20-11e7-9478-de402407c909.jpg)

**Logic:**
![capture d ecran 2017-07-22 a 20 55 51](https://user-images.githubusercontent.com/8959779/28493925-49053aa4-6f20-11e7-8936-43ef89bbbcf4.jpg)

**Reaper:**
![capture d ecran 2017-07-22 a 20 56 25](https://user-images.githubusercontent.com/8959779/28493928-538eae88-6f20-11e7-98dd-1323c6c970c2.jpg)

**Comment by belangeo** [comment]
Ok, ça va être assez tordu d'assurer les bons settings, peu importe la machine (particulièrement le driver audio) mais je devrais trouver une solution! Pour l'instant, le plus sûr est probablement d'ouvrir les prefs de JackPilot et de s'assurer que tout est en règle.

**Comment by Normandeau** [comment]
**Version 007**
Testé cela avec Live, Reaper, Logic et DP après une réinstallation complète. Tout semble fonctionner normalement. Par défaut, il n'y a pas d'Auto-Connection avec les ports physiques et les entrées-sorties viruelles sont bien à 128. 
Je mets tout de même une note dans le manuel qui va recommander de désinstaller Jack avant d'installer le Server pour ceux qui se sont déjà servi de Jack. Et ensuite les instructions pour changer les Preferences si nécessaire.
#54

**Comment by led78** [comment]
«Et ensuite les instructions pour changer les Preferences si nécessaire»

En essayant de changer les préférences directement dans Jack Pilot j’obtient toutefois ce message à tout coup :

[cid:66BA9D2E-DBA4-4F9D-AD45-4A5B5BB39EA5@home]

Je ne sais pas si ce message signifie réellement quelque chose, puisque les changements effectués - quelqu’ils soient - semblent tout de même sauvegardés lorsque je réouvre les préférences.


Le 26 août 2017 à 11:50, Robert Normandeau <notifications@github.com<mailto:notifications@github.com>> a écrit :


Version 007
Testé cela avec Live, Reaper, Logic et DP après une réinstallation complète. Tout semble fonctionner normalement. Par défaut, il n'y a pas d'Auto-Connection avec les ports physiques et les entrées-sorties viruelles sont bien à 128.
Je mets tout de même une note dans le manuel qui va recommander de désinstaller Jack avant d'installer le Server pour ceux qui se sont déjà servi de Jack. Et ensuite les instructions pour changer les Preferences si nécessaire.
#54<https://github.com/GRIS-UdeM/ServerGRIS/issues/54>
