### ISSUE TITLE
Fenêtre Edit Speaker en avant-plan: oui mais trop!

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#31]
La fenêtre Edit Speakers est maintenant en avant-plan, merci. Cependant elle est en avant-plan de tout dans le Finder!!! Comme en ce moment elle est devant Firefox! N'y a-t-il pas moyen de la mettre en avant-plan seulement dans le Server?

**Comment by belangeo** [comment]
Pas sur... Je vais voir!
