### ISSUE TITLE
HP (non) sélectionné

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#32]
HP sélectionné
R: Lorsqu'on passe de la fenêtre Edit Speakers à la vue 3D, le hp sélectionné est toujours dé-sélectionné par ce passage d'une fenêtre à l'autre. Or souvent quand on passe de la fenêtre d'édition à la fenêtre 3D, c'est parce qu'on veut valider qu'on a bien placé le hp à la bonne place. Mais il n'est plus sélectionné...
À l'inverse, si on pouvait sélectionner un hp dans la vue 3D, qui se refléterait dans la page Edit, ce serait utile.
O C'est corrigé. À noter que pour désélectionner un HP à partir de la vue 3D, il faut cliquer dessus avec le bouton droit de la souris.

**Comment by Normandeau** [comment]
Correction: actuellement on peut déselectionner le hp dans la vue 3D avec le bouton **gauche** de la souris. Mais on ne peut pas le sélectionner.
On attend la version 004 pour valider le tout.

**Comment by Normandeau** [comment]
Ok c'est clic droit...

**Comment by Normandeau** [comment]
Cela ne fonctionne plus. On ne peut plus désélectionner un hp avec un clic ou l'autre

**Comment by belangeo** [comment]
Je n'ai pas ces deux comportements sous linux... Je vais voir sous osx ce qu'il se passe. Selon moi, on veut pouvoir désélectionner même lorsque la fenêtre est ouverte et on ne veut pas ouvrir la fenêtre lorsque l'on désélectionne un HP!

**Comment by Normandeau** [comment]
Je ne l'ai plus non plus dans la version 005. Étrange.

**Comment by Normandeau** [comment]
Si on pouvait sélectionner un hp dans la vue 3D, qui se refléterait dans la page Edit, ce serait très utile.

**Comment by Normandeau** [comment]
Penser à ajouter un mode où on peut déplacer les hp directement dans la vue 3D (comme dans le Zirkonium). C'est très utile pour construire un setup rapidement. Après on peut ajuster les valeurs de manière plus précise dans la fenêtre Edit Speakers. Cela implique un bouton de type Speaker draguable qui gèle la l'image 3D pendant le déplacement du ou des hp. Sinon, tout va bouger en même temps.

**Comment by belangeo** [comment]
"Si on pouvait sélectionner un hp dans la vue 3D, qui se refléterait dans la page Edit, ce serait très utile."

C'est déjà le cas!

**Comment by Normandeau** [comment]
Tu veux dire dans ta version de développement?
Parce que dans la version 005 que nous avons en ce moment, on ne peut pas sélectionner un hp dans la vue 3D. On peut seulement sélectionner un hp dans la fenêtre Edit Speakers, et le désélectionner dans la vue 3D avec le clic droit. D’ailleurs en vérifiant cela, je me rends compte qu’on ne peut pas désélectionner un hp dans Edit Speakers avec le clic droit. Seulement dans la vue 3D.

**Comment by belangeo** [comment]
Un clic gauche sur un HP dans la vue 3D ne le sélectionne pas?

**Comment by Normandeau** [comment]
Pas chez moi. J'ai essayé avec deux souris, une Magic Mouse d'Apple et une Revolution de Logitech. Les autres?

**Comment by Normandeau** [comment]
Version 006
Le clic gauche ne sélectionne le hp que si le Server est sur mon écran secondaire! Lorsque le Server est sur l'écran Retina de mon MacBook Pro, cela ne fonctionne pas.

**Comment by belangeo** [comment]
Je vais avoir accès à un macbook pro à partir d'aujourd'hui, je vais investiguer le problème avec les écrans rétina (on est pas les premiers à avoir des problèmes de ce genre!).

**Comment by Normandeau** [comment]
J'ai essayé de changer la résolution de l'écran Retina (j'utilise la plus fine) mais ça ne change rien.

**Comment by belangeo** [comment]
Je confirme, avec un écran rétine, on ne peut sélectionner un HP. Je vais y voir...

**Comment by Normandeau** [comment]
Version 007: Bilan des clics
**ServerGRIS sur écran Retina**
- Fenêtre 3D: clic gauche, sélectionne hp; clic droit, désélectionne hp.
- Outputs: clic gauche ou droit: sélectionne hp; impossible de désélectionner.
- Fenêtre Edit Speakers: clic gauche ou droit: sélectionne hp; impossible de désélectionner.

**ServerGRIS sur écran externe (LG, résolution 160X1050)**
- Fenêtre 3D: impossible de sélectionner un hp, que ce soit avec clic gauche ou clic droit.
Si un hp est déjà sélectionné, clic droit le désélectionne.
- Outputs: clic gauche ou droit: sélectionne hp; impossible de désélectionner.
- Fenêtre Edit Speakers: clic gauche ou droit: sélectionne hp; impossible de désélectionner.

**Comment by Normandeau** [comment]
De retour à Montréal, j'essaie les clics sur mon écran Dell 24" (3480X2160), un pseudo 4K, même résolution que Retina. J'obtiens les mêmes résultats qu'avec l'écran Retina du Mac:
- Fenêtre 3D: clic gauche, sélectionne hp; clic droit, désélectionne hp.
- Outputs: clic gauche ou droit: sélectionne hp; impossible de désélectionner.
- Fenêtre Edit Speakers: clic gauche ou droit: sélectionne hp; impossible de désélectionner.

**Comment by Normandeau** [comment]
Version 008: Bilan des clics
ServerGRIS sur écran Retina

    Fenêtre 3D, Outputs et Fenêtre Edit Speakers: clic gauche, sélectionne hp; clic droit, désélectionne hp.

ServerGRIS sur écran externe (Apple, résolution 1920X1200)

    Fenêtre 3D: impossible de sélectionner un hp, que ce soit avec clic gauche ou clic droit.
    Si un hp est déjà sélectionné, clic droit le désélectionne.
    Outputs: clic gauche: sélectionne hp; droit: désélectionne hp.
    Fenêtre Edit Speakers: clic gauche: sélectionne hp; droit: désélectionne hp.

**Comment by Normandeau** [comment]
Version 009: Bilan des clics
• ServerGRIS sur écran Retina
    Fenêtre 3D, Outputs et Fenêtre Edit Speakers: clic gauche, sélectionne hp; clic droit, désélectionne hp.

• ServerGRIS sur écran externe (Apple, résolution 1920X1200)
    Fenêtre 3D, Outputs et Fenêtre Edit Speakers: clic gauche, sélectionne hp; clic droit, désélectionne hp.

Problème résolu.
