### ISSUE TITLE
Image 3D tremblante

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#33]
On a toujours la représentation 3D qui tremble pas mal lorsqu'elle reçoit de l'OSC. Remarque rapide: c'est après 32 canaux OSC que ça se met à osciller. Et si on ajoute des Azim et Elev Span, ça empire. Essentiellement, c'est donc une question d'accumulation.
Je vous envoie un vidéo par courriel. 44 pistes, 56 hp, pas d'automation, tout est statique dans DP. En fait, la séquence est à l'arrêt dans la vidéo.
Pourriez-vous documenter cela davantage.

**Comment by belangeo** [comment]
Avec 64 canaux OSC (en provenance de pyo) avec l'azimuth, l'élévation et les deux spans qui bougent, le serveur prend 115% de CPU sur ma machine! Le problème vient de la lourdeur de la vue 3D. J'ai commencé à lire sur l'optimisation du code openGL et il existe des méthodes de dessin plus efficaces que celles utilisées présentement par le serveur. Je vais y voir...

**Comment by Normandeau** [comment]
Oui j'ai constaté la même chose et cela allait être ma prochaine session de beta testage. Pendant l'atelier hier, avec une session DP de 44 canaux, sur 58 haut-parleurs, je prenais 70% du CPU de mon nouveau Mac. Ça va, ça joue! Je n'ai pas pensé à utiliser la fonction High performance pour comparer. Le Zirkonium MK1 faisait déjà cela sur G4 en 2005, et en plus les sources étaient activées par le signal! Et ça envoyait des signaux sur les LEDs placées sur les hp...
Mon projet est de comparer cette (contre)performance, en mode High performance et ensuite de comparer la même session avec le Zirkonium MK2 et MK3 éventuellement.
À suivre.

**Comment by belangeo** [comment]
Ok, l'image tremblante est réglé et avec le même setup (64 canaux OSC avec tout qui bouge), je suis mantenant à 30% de CPU plutôt que 115% ! Il y a encore place à amélioration mais ça va me demander un peu d'étude de l'openGL "moderne".

**Comment by led78** [comment]
Je n'ai pas encore vidé la cache de mes plug-ins car je veux éviter d'avoir à réassigner chaque canaux OSC, mais j'ai toujours une image tremblante avec SpatServer 0.0.4 et SpatGris 1.01. Dans mon cas, j'ai 64 canaux de sortie, dont deux sont directs (63-64), assignés vers 32 hautparleurs (dôme de la faculté). À l'arrêt le CPU est autour de 11%. Lorsque je lance le séquenceur, ça monte à 45-50%. Je vais maintenant vidé la cache et voir si l'image tremblante cesse.

**Comment by Normandeau** [comment]
C'est corrigé dans la version de développement 005 qui n'est pas encore publiée.

**Comment by Normandeau** [comment]
Ce problème semble résolu. Ce qui est bien, car maintenant quand a une source qui oscille, cela nous permet d'identifier facilement le problème suivant: c'est qu'on a deux sources qui utilisent le même canal OSC. Par conséquent, l'image de la source oscille entre les deux valeurs.
Pour ce qui est du CPU, j'ai testé une session plutôt costaude ce matin: 72 canaux audio, 32 SpatGRIS avec automation, speaker setup de 22 hp: 80% de CPU en mode High performance 9pas de comparaison disponible avec 004).
Sinon, en comparaison avec le kit utilisé pour l'atelier à Virginia Tech, 44 canaux audio, 44 canaux OSC sans automation, 58 hp: autour de 50% en mode High performance (ou 60% en mode normal, en comparaison de 70% sur le CUBE).
