### ISSUE TITLE
Suggestion d'un nouveau nom: ServerGRIS

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#38]
Je suggère qu'on nomme le server comme ceci à l'avenir: ServerGRIS.
Le Spat est de trop selon moi. Et puis il y en a tellement des Spat! Ça nous ferait le SpatGRIS et le ServerGRIS. Pas de confusion entre les deux.

**Comment by led78** [comment]
Je suis d'accord qu'il y a trop de Spat... Comme le disait Ray Kroc, il y a trop de Burger ceci, cela Burger, tandis que « McDonald's » ça sonne bien et ça veut dire bien plus que le produit. C'est à bien y penser lorsque viendra le temps de trouver un nom officiel.

**Comment by belangeo** [comment]
+1

**Comment by belangeo** [comment]
C'est fait! J'espère vraiment que c'est la dernière fois que je change le nom d'un projet démarré avec Juce... Juste pour vous donner une idée de la pagaille, allez voir https://github.com/GRIS-UdeM/ServerGRIS/commit/80e28ae236137f664272e4c3deed0202284b0514 !
