### ISSUE TITLE
Placement des hp des sorties directes dans la vue 3D?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#39]
Une idée d'amélioration, si elle est possible relativement facilement.
À l'heure actuelle, quand on place une sortie directe dans notre speaker setup, celle-ci n'a pas de coordonnées. Enfin, on peut en écrire, mais elles n'ont aucun effet. Cela déjà est étrange comme situation. Peut-on imaginer qu'on puisse placer les hp des sorties directes quelque part dans l'espace de la vue 3D sans qu'ils ne soient pris en charge par le VBAP? Ainsi on aurait une vue globale du positionnement des hp dans le plan. Pratique pour expédier une configuration à un producteur!
Si ce n'est pas possible, je propose que pour le moment on enlève la possibilité d'entrer des valeurs pour les sorties directes afin d'éviter toute confusion.

**Comment by led78** [comment]
J’ajouterais comme détail de changer la couleur du bouton servant à désigner une sortie comme étant « directe ». Actuellement, il s’agit de la même couleur que celle du HP sélectionné (orange), ce qui rend le bouton invisible lorsque un HP est assigné comme sortie directe. C’est un détail, je sais mais bon, pendant qu’on y est…

David

Le 9 août 2017 à 14:18, Robert Normandeau <notifications@github.com<mailto:notifications@github.com>> a écrit :


Une idée d'amélioration, si elle est possible relativement facilement.
À l'heure actuelle, quand on place une sortie directe dans notre speaker setup, celle-ci n'a pas de coordonnées. Enfin, on peut en écrire, mais elles n'ont aucun effet. Cela déjà est étrange comme situation. Peut-on imaginer qu'on puisse placer les hp des sorties directes quelque part dans l'espace de la vue 3D sans qu'ils ne soient pris en charge par le VBAP? Ainsi on aurait une vue globale du positionnement des hp dans le plan. Pratique pour expédier une configuration à un producteur!
Si ce n'est pas possible, je propose que pour le moment on enlève la possibilité d'entrer des valeurs pour les sorties directes afin d'éviter toute confusion.

**Comment by belangeo** [comment]
Dans la version 0.0.5, les sorties directes apparaissent en gris foncé dans la vue 3D. La couleur de sélection et la couleur des boutons sont maintenant distinctes.
