### ISSUE TITLE
Calibration des VU mètres

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#41]
David: Si tel est le cas, pourrais-t-on avoir la possibilité d'ajuster le temps de descente des vu-mètres? Par exemple, avoir une vue crête et une vue RMS et pouvoir modifier leur vitesse de modulation?
On a discuté de cela hier et effectivement on va travailler à améliorer la performance des VU-mètres. Et ils seront calibrés. Ils deviendront ainsi un bon outil de mesure. C'est important, car quand on distribue une source sur de multiples hp, il faut que l'utilisateur comprenne bien que la somme globale de l'énergie demeure la même, ce qui se manifeste par des niveaux de sorties moindres que le niveau d'entrée. Avec des VU-mètres calibrés, il est facile d'en expliquer le concept.

**Comment by led78** [comment]
Je ne sais pas si le fait de pouvoir sélectionner une fenêtre temporelle plus grande (RMS) pour les VU-métres permettrait également d'épargner du CPU?

**Comment by Normandeau** [comment]
V013
Olivier:
Il n'y a pas de raison de ralentir la vitesse de rafraîchissement des VUs. Ils prennent déjà très peu de ressources.
