### ISSUE TITLE
Représentations 3D et 2D: sources visibles selon leur niveau d'intensité

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#42]
Je crois qu'on l'a déjà mentionné puisque c'est une fonction disponible dans le Zirkonium, mais je le note ici car je crois que c'est une amélioration importante pour faciliter le travail de composition spatiale.
Dans le Zirkonium, il est possible d'afficher uniquement les sources actives selon l'énergie reçu des sorties du séquenceur durant la lecture. Avec la quantité d'instance de SpatGris que j'ai dans ma session, j'active toujours cette fonction sans quoi je ne vois rien sur le plan graphique tant celui-ci est surchargé. C'est encore pire avec la vue 2D du ServerGris.

Je suggère deux options:
- la première, serait identique à celle du Zirkonium et n'afficherait que les sources envoyant du signal au Server à mesure que la séquence joue.
- la deuxième reprendrait la première, mais serait implémentée post-mute/solo. C'est-à-dire que si je solo quelques pistes d'entrée dans le Server, seule les pistes solo seraient visibles sur les graphiques (3D et 2D). Cette fonction serait selon moi très pratique pour la composition spatiale entre quelques sources précises avec des instances de SpatGRIS différents.

Enfin, ce serait bien si les représentations graphique des sources suivent un peu l'intensité sonore de celles-ci, au lieu de simplement apparaitre et disparaitre à partir d'un certain seuil, comme c'est actuellement le cas dans le Zirkonium MK2.

**Comment by belangeo** [comment]
C'est fait. Je vais probablement retoucher cet algorithme lorsque je vais calibrer les vu-mètres!
