### ISSUE TITLE
Les numéros des hp et des sources sont à l'envers!

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#43]
Version 005
Les numéros des hp et des sources sont à l'envers par rapport aux versions précédentes (vue de 180˚ ou de 0˚):

![numeros a l enver](https://user-images.githubusercontent.com/8959779/29174155-703a06b2-7db3-11e7-9ac5-5216bc5d6cee.jpg)

On les voit à l'endroit seulement lorsqu'on regarde le setup de côté (vue de 270˚ ou de 90˚):

![numeros a l endroit](https://user-images.githubusercontent.com/8959779/29174166-74bb5e48-7db3-11e7-8f53-2f9fd176121b.jpg)

**Comment by Normandeau** [comment]
Trèze bizarre.
Je reviens travailler dans le studio cet après midi et les chiffres apparaissent dans le bon sens. Testé sur plusieurs setups, comme ce matin...
Ai-je la berlue?

**Comment by led78** [comment]
Je travaille avec le Server 0.0.5 depuis ce matin et les chiffres apparaissent bel et bien à l’envers, comme tu le décris et c’est toujours le cas présentement.

Le 10 août 2017 à 14:18, Robert Normandeau <notifications@github.com<mailto:notifications@github.com>> a écrit :


Trèze bizarre.
Je reviens travailler dans le studio cet après midi et les chiffres apparaissent dans le bon sens. Testé sur plusieurs setups, comme ce matin...
Ai-je la berlue?

**Comment by Normandeau** [comment]
Depuis que c'est revenu une fois, ce n'est plus jamais revenu. Tous les chiffres sont toujours à l'envers...
