### ISSUE TITLE
Problème de hiérarchie dans le menu View

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#46]
Est-ce voulu? Si oui, pourquoi?

**Comment by belangeo** [comment]
Afficher avec l'alpha prend plus de CPU, ça entre un peu en contradiction avec le mode "High Perf". Je n'avais pas testé mais je suppose que le mode HP désactive le canal alpha...

**Comment by led78** [comment]
Je comprend. Dans ce cas, ce je proposerais de faire éventuellement consiste à offrir à l'utilisateur un choix entre divers modes de visualisation visant à optimiser la consommation de CPU en fonction du besoin courant :
- Mode VU = les VU-mètres sont en priorités (plus fluides), l'affichage de la spatialisation est désactivée ou ne suit plus l'amplitude (Alpha désactivé).
- Mode Spatial Actif = les VU-mètres sont désactivés (ou ralentis comme c'est le cas présentement en mode High Performance), l'affichage de la spatialisation suit l'amplitude (actif) et présente donc seulement les sources actives.
- Mode Spatial Passif = es VU-mètres sont désactivés (ou ralentis comme c'est le cas présentement en mode High Performance), l'affichage de la spatialisation ne suit pas l'amplitude (passif) et présente donc toutes les sources reçues.
- Mode Amplitude (ou Alpha) = autant les VU-mètres que la spatialisation présente un suivi d'amplitude optimal des sources. Ce mode serait donc le plus gourmand en terme de CPU et équivaudrait au mode Alpha.

Qu'en pensez-vous?

**Comment by Normandeau** [comment]
Trop de modes pour moi. Y a-t-il un véritable problème de CPU identifié ici? Et identifié clairement comme appartenant au Server? Quelqu'un a-t-il poussé sa machine dans un projet de composition à la limite de l'utilisable? Est-ce que le CPU utilisé n'est pas essentiellement le fait des DAWs? On est déjà la moitié de la demande en CPU du Zirkonium MK2 sur des projets denses.
Voir #44

**Comment by led78** [comment]
En ce moment, on a déjà trois modes non explicites : le mode par défaut, le mode high performance et le mode alpha. Ce que je suggère, c’est de tout combiner ça dans un seul menu déroulant. Leur fonction serait plus explicite pour l’utilisateur et ça ferait moins de boutons disparates.

Le CPU peut devenir un problème sur une machine moins puissante; dans une session de travail (et non de diffusion) gourmande, comprenant plusieurs instruments virtuels par exemple; et, surtout, si on ajoute éventuellement une sortie audio binaural en temps réel. Lorsque je travaillais avec le Zirkonium MKII en mode binaural, sur mon ancien ordinateur (iMac 2009), je devais impérativement désactiver les VU-mètres sans quoi l’audio se mettait à sauter des échantillons tellement c’était demandant. De plus, je crois que le Zirkonium limite le nombre d’entrées permises lorsqu’on auditionne en mode binaural afin de sauver du CPU. Je comprend qu’en ce moment, le CPU n’est pas un problème. Mais si l’on veut rendre l’outil plus accessible, ça va éventuellement prendre un mode d’écoute au casque (binaural) comme le Zirkonium. Offrir à l’utilisateur la possibilité de gérer lui-même son CPU en fonction de ses besoins me semble pratique dans ce contexte.


Le 19 août 2017 à 11:40, Robert Normandeau <notifications@github.com<mailto:notifications@github.com>> a écrit :


Trop de modes pour moi. Y a-t-il un véritable problème de CPU identifié ici? Et identifié clairement comme appartenant au Server? Quelqu'un a-t-il poussé sa machine dans un projet de composition à la limite de l'utilisable? Est-ce que le CPU utilisé n'est pas essentiellement le fait des DAWs? On est déjà la moitié de la demande en CPU du Zirkonium MK2 sur des projets denses.
Voir #44<https://github.com/GRIS-UdeM/ServerGRIS/issues/44>

**Comment by Normandeau** [comment]
Tu as un point. En fait, un menu déroulant permettrait aussi d'éviter les combinaisons absurdes, comme Alpha et High Performance. Cette combinaison donne une représentation graphique pastel... On a aussi discuté de cela avec Olivier. Lorsque le fonctionnement de base du Server sera assuré, et qu'on pourra retirer les bogues, l'interface graphique sera révisée, avec une possibilité d'avoir un look de vrai logiciel avec des menus, des préférences et des options. Je commence à rédiger le manuel mais j'attends que cette étape soit terminée avant de faire les captures d'écran.

**Comment by led78** [comment]
Suite à la suggestion faite par Olivier de faire une distinction entre les éléments sauvegardés en lien avec un projet spécifique et la sauvegarde des préférences du Server, applicables plus globalement, j'aimerais suggérer par le fait même qu'il soit possible d'assigner un projet par défaut - qui s'affiche dès l'ouverture du server. Ce choix pourrait être effectué à partir du menu déroulant ou à partir d'une fenêtre s'affichant dès que l'on ouvre un projet existant : « Set as default project ? »; « Set project as default ». Ça réduirait davantage le nombre de clique nécessaire avant de commencer à travailler sur un projet, ce qui est toujours bienvenu.

**Comment by belangeo** [comment]
Le système que j'ai commencé à mettre en place (pas terminé) est d'ouvrir sur le dernier projet ouvert, si valide, sinon on ouvre sur le projet par défaut. C'est assez courant comme façon de faire et ça évite d'ajouter une préférences de plus au logiciel.

**Comment by Normandeau** [comment]
Version 008.
Revenons au menu déroulant suggéré par David. En lieu et place de cela, on a maintenant une série d'options individuelles sous le menu View qui ne s'excluent pas les uns les autres. Ainsi on peut tout cocher en même temps.

À l'arrêt, cela donne ceci. On a comme un vestige du mode Alpha pour la source, la couleur rose-orangé est un ersatz palôt de la couleur originale:
![view tout selectrionne stop](https://user-images.githubusercontent.com/8959779/31571091-74b79798-b05a-11e7-9746-ff6c65a7d144.jpg)

En jeu, cela donne ceci, où on retrouve la couleur originale de la source, un rouge franc, avec une activité des hp:
![view tout selectrionne play](https://user-images.githubusercontent.com/8959779/31571095-99cf3964-b05a-11e7-96ca-13f20f264bdd.jpg)

Alors la question se pose: qui domine? À quoi sert le mode High Performance s'il est court-circuité par les autres?

**Comment by Normandeau** [comment]
V012
Réglé.
