### ISSUE TITLE
Activité visible des sorties: un peu pâlotte

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#47]
Cette nouvelle fonction est vraiment bien. On avait cela dans le Zirkonium 1 et c'est excellent.
Cela reste à calibrer cependant. En général, la distribution de l'énergie dans un VBAP est plutôt une opération de dilution. En effet, l'énergie de base est distribuée sur beaucoup de hp, donc les niveaux de sorties sont en général plus faible que les niveaux d'entrées. Cela a pour conséquence que l'affichage de l'activité des sorties est plutôt pâlotte en général. Il faudrait simplement recalibrer cela pour que l'activité soit plus visible.

Deux exemples pris dans les moments de pic d'activité de chacune des pièces.
44 pistes sur 54 hp:
![capture d ecran 2017-08-19 a 10 31 08](https://user-images.githubusercontent.com/8959779/29487668-64b9d816-84cb-11e7-8bfa-4dda1c7bdd6c.jpg)

64 pistes sur 16 hp:
![capture d ecran 2017-08-19 a 10 32 06](https://user-images.githubusercontent.com/8959779/29487675-7a59edf0-84cb-11e7-87f4-9cf39347903f.jpg)

**Comment by belangeo** [comment]
Je trouvais aussi que c'était un peu pâle... Une solution assez économique en CPU serait de redéfinir la courbe du canal alpha pour un plafond de, disons, -30 dB, plutôt que 0 dB. Ainsi, entre -30 et 0 dB, la couleur est à son maximum et seulement sous la barre de -30, la transparence apparait.

**Comment by Normandeau** [comment]
Bonne idée. À valider.

**Comment by belangeo** [comment]
On va essayer -40 dB pour la version 0.0.7!

**Comment by Normandeau** [comment]
**Version 007**
C'est encore un peu palotte. 
En fait, je me demande si on ne s'est pas trompé de concept. Ce qu'on veut voir comme activité, ce n'est pas celle des sources, autrement dit des Inputs. On a les VU-mètres pour cela. Et les Sources auront toujours la même activité pour un projet donné (qu'on peut aussi visualiser dans son séquenceur).
Ce qu'on veut visualiser plutôt, c'est l'activité des haut-parleurs, autrement dit celle des **Outputs**. C'est cette information qui est importante et qui va changer d'un setup de hp à un autre. Cette information visuelle va nous informer de l'activité énergétique globale de chaque hp. D'ailleurs c'est bien le titre de cette issue: «Activité visible des sorties». C'est cela qui était représenté dans la Zirkonium MK1, les hp «irradiaient» leur énergie!
Je ne m'étais pas rendu compte qu'on voyait l'activité des entrées dans la version 006.
Nous sommes bien d'accord?
Est-ce que ça représente une difficulté supplémentaire pour réaliser cela?

**Comment by led78** [comment]
Pour ma part, j'aime bien voir l'activité des sources selon leur énergie dans l'image 3D. Je trouve utile de combiner visuellement la spatialisation des sources à leur énergie dans un contexte d'une composition de l'espace simultané au montage/mixage des sources. Cela dit, je trouve aussi utile de pouvoir visualiser l'activité énergétique des hautparleurs dans un contexte de mixage, afin d'équilibrer l'énergie acoustique déployé vers l'auditoire selon la position des hautparleurs, le nombre de source et leur intensité dans une direction donnée.

**Comment by led78** [comment]
Abaisser davantage le seuil d'opacité maximal (à -70 dB?).

**Comment by Normandeau** [comment]
Réglé dans la version 008
