### ISSUE TITLE
Ordre et déplacement manuel des Speakers

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#50]
Il y a un peu de confusion ici pour moi. Cette fonction est vraiment très pratique, car elle permet de configurer très rapidement un dôme. Mais je ne suis pas certain de bien comprendre les valeurs de Zenith et Radius. 
Radius: théoriquement, la valeur de Radius dans un dôme devrait toujours être de 1, n'est-ce pas? Afin d'obtenir une demi-sphère parfaite correspondant à un dôme.
Zenith: comment cette valeur est-elle calculée. J'ai pris l'habitude d'utiliser la valeur Z à ce jour, donc le point le plus haut est 1. Ici, j'ai supposé que c'était un pourcentage, mais en entrant la valeur 100, les hp se positionnent à la valeur 80, qui a l'air d'être la valeur la pus élevée du Zenith. À quoi cela correspond-il?

![capture d ecran 2017-08-19 a 11 04 05](https://user-images.githubusercontent.com/8959779/29487904-e83dd978-84ce-11e7-9e58-0ce467b56686.jpg)

Ok, Zenith est un angle, avec la valeur maximale de 90˚, exact?
Donc Radius: 1, Azimuth: 90 et Zenith: 90 donne un hp au faîte du dôme:

![capture d ecran 2017-08-19 a 11 24 44](https://user-images.githubusercontent.com/8959779/29488043-0bc2c5c8-84d1-11e7-96f3-0774750c4d1a.jpg)

Première correction donc: empêcher dans Zenith que l'on puisse entrer des valeurs supérieures à 90. Actuellement on le peut, et cela donne des résultats assez imprévisibles. Les valeurs ne sont pas toujours acceptées d'ailleurs. Elles sont parfois ignorées par le logiciel, et parfois ajustées à d'autres valeurs (comme 80 dans l'exemple plus haut).

Pour Azimuth, le maximum devrait être de 360˚, exact? Actuellement, on peut entrer n'importe quoi comme valeur, comme 750˚ par exemple, le hp fait le tour une fois, deux fois et s'arrête à 30˚ (750 - (360 + 360) = 30). Au moins ici c'est cohérent, mais est-ce nécessaire?

**Comment by Normandeau** [comment]
J'ai retravaillé le Speaker Setup de Virginia Tech en plaçant tous les Radius à 1. Excellent. Mais je me suis trompé une couple de fois et j'ai dû refaire certains cercles de hp. Heureusement c'est possible d'intercaler un cercle à ceux déjà existants (une fonction inexistante dans le Zirkonium). Mais on ne bénéficie pas encore d'un classement des hp dans Edit Speakers (par Outputs par exemple), lorsqu'on compute la configuration, cela crée une succession de Outputs correspondant à l'ordre de création. Ce qui peut amener de la confusion, comme ici où les subs (125-126) sont au milieu de deux cercles. Il faudra songer à cela lorsqu'on implémentera les possibilités de classement afin que la fonction Compute replace les hp dans le bon ordre.

![capture d ecran 2017-08-19 a 12 12 13](https://user-images.githubusercontent.com/8959779/29488422-998bf378-84d8-11e7-9ea4-8f90cafdf4b7.jpg)

**Comment by belangeo** [comment]
- Pour un dôme parfait, oui, le radius doit être de 1. Par contre, le VBAP ne fait que placer le son sur la surface de la "sphère" définit par les haut-parleurs. Si on modifie la forme de cette sphère (dans la mesure du raisonable), le VBAP va encore fonctionner. 

- Oui, ça prend un clipping des valeurs pour assurer la cohérence.

- Présentement, "Add Ring" ajoute des haut-parleurs à la fin de la liste. On pourrait faire en sorte qu'il ajoute après le HP sélectionné. Idéalement, on voudrait aussi pouvoir glisser les lignes pour réordonner la liste.

**Comment by Normandeau** [comment]
Ajout:
- possibilité d'insérer un hp ou un groupe de hp après le hp sélectionné
- déplacement automatique des sorties directes en bas de la liste.

**Comment by Normandeau** [comment]
Copié de #20:
Suggestion pour une amélioration. Lorsqu'on clique sur l'un des paramètres de l'édition des Speakers, comme ici sur Output, un petit triangle apparait qui nous laisse croire qu'on peut classer les hp selon ce paramètre par ordre croissant ou décroissant. Mais cela ne fonctionne pas actuellement (V014). Ce serait fort utile.

![ordre des hp](https://user-images.githubusercontent.com/8959779/35360191-e9aaccac-012a-11e8-8228-f1b3c3c7a0b4.jpg)

**Comment by led78** [comment]
Petit irritant: lorsqu'on ajoute une couronne d'un coup avec la fonction "Add ring" (très pratique) les numéro d'output sont automatiquement assignés selon l'ID du hp. Or, comme c'est le cas avec le dôme Tonlabor (au symposium KLG 2018), les numéro (ID) ne concorde pas avec les numéros de sortie (DANTE). Je dois donc les attribuer correctement à la main. L'irritation vient du fait que, bien souvent, en voulant changer un numéro de sortie pour un autre, dans la colonne output, un avertissement me disant que le numéro est déjà pris apparait. Je dois donc ajouter chaque HP un par un pour éviter cela, ce qui rend la fonction "Add ring" inutile. Ce serait bien si l'avertissement nous offrait l'option d'intervertir les numéros d'output lorsqu'on tente de remplacer un numéro pour un autre déjà assigné.

**Comment by Normandeau** [comment]
Une stratégie que j'utilise pour pallier à cela est la suivante: j'ajoute un no de centaine à chaque ID de hp lors de la création des Ring, et ensuite je les renomme correctement selon les valeurs souhaitées, normalement situées sous la centaine! Mais cela serait plus facile si on pouvait bouger avec les flèches haut-bas d'un no de hp à l'autre, alors qu'actuellement on doit cliquer dans chacune des TextBox indépendamment.

**Comment by belangeo** [comment]
> L'irritation vient du fait que, bien souvent, en voulant changer un numéro de sortie pour un autre, dans la colonne output, un avertissement me disant que le numéro est déjà pris apparait. 

Une stratégie possible serait de laisser l'utilisateur faire ce qu'il veut avec les numéros de sortie et d'afficher un avertissement (s'il y a incohérence) seulement lors de la fonction Compute. Ça semble raisonnable?

> Mais cela serait plus facile si on pouvait bouger avec les flèches haut-bas d'un no de hp à l'autre, alors qu'actuellement on doit cliquer dans chacune des TextBox indépendamment.

Plutôt que des flèches, je pourrais faire une fonction clic-drag vers le haut ou le bas pour faire défiler les numéros?

**Comment by Xon77** [comment]
La possibilité d'insérer un hp ou un groupe de hp après le hp sélectionné, de les ordonner et le déplacement automatique des sorties directes en bas de la liste semble bien marcher.

Cependant, j'observe quelques petites incohérences dans le Speaker Setup : 

1. Le fait de mettre une valeur négative en azimuth, positionne le HP comme si la valeur négative était positive, mais l’orientation du speaker vers le centre est inversée (peut-être n’autoriser que des valeurs entre 0 et 360 et ne pas accepter les valeurs négatives, puisqu’elles sont mal interprétées).

2. Si j’ajoute un speaker ou une couronne de HP et souhaite le deleter après, le numéro d’ID reste avec un décalage (en fonction du nombre de HP supprimé). (Peut-être, si un HP est est supprimé, adapter le n° d’ID en fonction)

**Comment by belangeo** [comment]
Corrigé!

**Comment by Normandeau** [comment]
Pas corrigés dans la version 2.01. Ni l'un ni l'autre des deux items soulevés précédemment n'est corrigé.
La valeur négative en azimuth provoque toujours le même comportement:
Valeur positive:
![capture d ecran 2018-11-03 a 11 09 50](https://user-images.githubusercontent.com/8959779/47953841-29225780-df59-11e8-972e-394dd074206b.jpg)
Valeur négative:
![capture d ecran 2018-11-03 a 11 10 06](https://user-images.githubusercontent.com/8959779/47953847-32abbf80-df59-11e8-839a-3267979a0b20.jpg)
D'ailleurs, ça donne quoi un hp qui n'est pas orienté vers le centre? Je n'avais jamais constaté qu'on pouvait faire une telle chose!

Décalage après avoir avoir enlevé des hp: les ID ne s'ajustent pas à la nouvelle configuration:
![capture d ecran 2018-11-03 a 11 05 30](https://user-images.githubusercontent.com/8959779/47953872-73a3d400-df59-11e8-8f30-5b983d18fd43.jpg)

Je me rends compte d'ailleurs que cela génère un nouveau problème sur le plan de la sauvegarde (je vais faire une autre issue) car les changements apportés modifient le Speaker Setup en cours, même si on clique NO à la demande de sauvegarde!!!

**Comment by belangeo** [comment]
C'est changements ont été apportés après la version 2.0.1, vous ne les avez pas encore!
Pour les numéros d'HP, il ne faut pas confondre ID et OutputPatch. La vue 3D affiche le OutputPath et non l'ID. Je viens de vérifier et tout semble correct.

**Comment by Normandeau** [comment]
Version 202
Je pense que toutes les facettes de cette issue ont été corrigées ici:
- Add Ring est possible n'importe où dans l'ordre des hp comme une insertion d'un hp simple
- Insertion de HP n'importe où
- Les hp peuvent être ordonnés selon la série de listes disponibles, en ordre croissant ou décroissant
- l'avertissement des numéros de sorties utilisés en double fonctionne. Une question cependant: qu'est-ce qui se passe si on ignore l'avertissement? Je me retrouve avec deux hp qui ont la même sortie. Peut-être que c'est une caractéristique utile: lorsqu'on on joue sur un plus petit acousmonium, on peut réattribuer certains hp aux mêmes sorties. Je pense surtout au mode LBAP bien évidemment. Mais je me demande si ce n'est pas là une source potentielle d'erreur. À méditer. En tout état de cause, l'écrire clairement dans le manuel!
- Les numéros d'ID se remettent en ordre après l'ajout pu la suppression d'un hp dans la liste
- Les valeurs négatives d'Azimuth sont corrigées en valeur positive opposée

Ne resterait que cela:
«Plutôt que des flèches, je pourrais faire une fonction clic-drag vers le haut ou le bas pour faire défiler les numéros?»

**Comment by Normandeau** [comment]
Voir l'issue 143, Abandon de l'idée d'avoir des hp en double.

**Comment by Normandeau** [comment]
V203
Réglé
