### ISSUE TITLE
Stop Record ne fonctionne plus

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#51]
Le bouton Record, qui faisait aussi office de Stop record, ne fait plus cette dernière opération. Pour arrêter l'enregistrement, il faut utiliser le bouton Initialize Recording

![capture d ecran 2017-08-19 a 15 53 48](https://user-images.githubusercontent.com/8959779/29489895-5dff7e3a-84f9-11e7-85d6-38ece553aa5d.jpg)

**Comment by belangeo** [comment]
Yep, ça enregistre pour la durée demandée. Je peux rétablir la fonction "stop" en ré-appuyant sur le bouton!

**Comment by Normandeau** [comment]
Bonne idée. C'est juste que si on est parti pour 15 minutes et qu'on veut faire un changement, le réflexe (pour moi tout au moins) est de réappuyer sur R qui pourrait, comme dans l'enregistrement des trajectoires dans SpatGRIS, se changer en Cancel pendant l'enregistrement.

**Comment by Normandeau** [comment]
Version 007
R se transforme en C lorsque l'enregistrement est lancé, ce qui effectivement annule (Cancel) l'enregistrement.
