### ISSUE TITLE
On/Off, Auto connect, X All: un peu de ménage

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#53]
Il me semble qu'il y a ici des fonctions qui se dédoublent non?
Est-ce que On/Off et Auto Connect ne font pas exactement la même chose?
Auto Connect connecterait toutes les clients en même temps, c'est bien cela? Combien d'entre vous avez utilisé plusieurs clients en même temps? Faudrait tester d'ailleurs en passant...
Personnellement je n'utilise que le On/Off vis à vis du client, c'est très clair comme fonction.
X All est une sorte de Panic Button si je comprends bien? Je n'ai jamais eu à l'utiliser à ce jour... Est-il bien nécessaire? Jamais eu à utiliser une fonction comme celle-là sur le Zirkonium non plus. N'est-ce pas un aveu de faiblesse que de le laisser là?
Dans un souci d'éclaircissement de l'interface, je propose qu'on élimine Auto Connect et X All.
Votre expérience?

![on off auto connect x all](https://user-images.githubusercontent.com/8959779/29536498-05a0190e-868c-11e7-9246-fdccadd4c550.jpg)

**Comment by belangeo** [comment]
Je n'ai jamais utilisé "X All" et "Auto Connect" moi non plus et je n'ai pas eu d eproblème. J'ai fait des tests avec plusieurs clients, ça fonctionne sans problème. Je peux, dans un premier temps, cacher les deux boutons en trop, sans retirer le sfonctionnalités du code et on verra à l'usage si on doit les ré-introduire ou non.

**Comment by Normandeau** [comment]
Ok, bonne idée.
