### ISSUE TITLE
Auto-Connection avec les ports physiques dans Jack

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#54]
J’aimerais que vous testiez le Server avec Live.
Personnellement je n’y arrive pas.
En fait, je ne suis pas certain de la configuration des sorties de Live.
Actuellement, j’utilise les sorties externes, associées à Jack.
Elles sont disponibles, on peut y insérer un SpatGRIS et effectivement le signal est envoyé dans le Server comme attendu.
Cependant, la carte son reçoit deux signaux: celui qui vient du Server et qui est spatialisé.
Et la sortie directe utilisée par Live, qui est envoyée directement à la carte son.
Par exemple, si je mets une piste sur Ext. 1-2 (je suppose que ça veut dire JackRouter 1-2, car rien ne l'indique), et que je positionne le SpatGRIS sur 1-2, j’ai bien le signal qui entre dans le Server sur 1-2 et qui sort de celui-ci sur 1-2.
Normal.
Mais si je déplace le son avec SpatGRIS vers disons 7-8, j’ai bien le signal qui se déplace sur 7-8 dans le Server et seulement sur ces sorties, mais TotalMix me dit que le son reste sur 1-2 en plus de 7-8.
Et ainsi de suite avec les sorties 3-4, 5-6 et 7-8.

**Comment by Normandeau** [comment]
**Test supplémentaires**
J'ai fait un setup avec JackPilot, Zirkonium et Live. Par défaut, quant on ouvre la fenêtre de routage dans Jack dans un setup comme celui-ci, les sorties de Live sont toutes connectées sur la carte son. Et le Zirkonium aussi. Il faut refaire le routage manuellement afin que  les sorties de Live aille vers le Zirkonium et que seules les sorties de celui-ci aillent vers la carte son et ainsi ça fonctionne. Malheureusement, même en sauvant ces réglages, ils ne sont plus opérationnels lorsqu'on ouvre ensuite Server et Live. Ce dernier envoie toujours du signal directement à la carte son sans passer par le Server (Server Client à Off). Et cela passe forcément par Jack, puisque c'est la seule interface choisie dans les préférences de Live.

**Autres tests supplémentaires**
Vérification faite, non seulement Live se comporte de la sorte mais aussi Reaper et Logic!!!
Seul DP a une relation exclusive avec le Server. Ah les bons vieux mariages!!!
Alors: soit tout mon système est déréglé, et alors il faut trouver la solution. Soit tout le monde confirme ce que je dis, et alors on a un drôle de problème sur les bras.

**Préférences Système**
Actuellement on n'a pas le choix de réglér la sortie Son des Préférences Système sur la carte de son. C'est la seule manière que le Server a de se connecter dessus (via Jack). Ne pourrait-on pas ajouter une possibilité dans le Server de choisir la carte son directement? Ainsi le son du système serait assigné à n'importe quoi sauf la carte son et le Server aurait une exclusivité sur la carte son.
Après se pose la question de la synchronisation à long terme, soulevée par Nicolas, dont la solution était précisément la sélection de la carte son dans les Préférences Système. Un beau Catch 22?

**Comment by belangeo** [comment]
Je me demande si ce n'est pas seulement un oublie de s'assurer que les clients n'envoient pas de son aux sorties système... Je vais vérifier. La solution de sélectionner la carte dans le serveur est pas mal mais elle ne règle pas le problème si le serveur ne déconnecte pas le client des sorties système (ou d ece que le serveur considère comme les sorties système, ça ne fait pas de différence).

**Comment by Normandeau** [comment]
Autre vérification: j'ai testé avec des fichiers octophoniques, et le signal est bel et bien envoyé aux huit sorties du système (i.e. la carte son) autant chez Live, Reaper et Logic.

**Comment by belangeo** [comment]
Je viens tout juste de tester le ServerGRIS sur mon nouveau macbook et en effet, sans interface audio particulière, les sorties stéréo de Reaper sont envoyées au serveur ET au système...

**Comment by Normandeau** [comment]
Bingo! J'ai trouvé. Il s'agit simplement d'une préférence de JackPilot, Auto-Connection avec les ports physiques, qu'il faut désactiver. De la sorte, il n'y aucune connexion automatique dans la fenêtre de routage de JackPilot. J'ai vérifié avec Logic, Live et Reaper.
Peut-on ajouter ce réglage dans les Jack settings du Server. Ou je mets une note dans le manuel? Compte tenu de l'importance de la chose, j'aurai tendance à l'ajouter dans les Settings.

![capture d ecran 2017-08-23 a 11 39 38](https://user-images.githubusercontent.com/8959779/29625152-ee605cc2-87f8-11e7-8e91-a087b1ce9215.jpg)

**Comment by belangeo** [comment]
Je vais voir si c'est possible!

**Comment by Normandeau** [comment]
Version 007
Testé cela avec Live, Reaper, Logic et DP après une réinstallation complète. Tout semble fonctionner normalement. Par défaut, il n'y a pas d'Auto-Connection avec les ports physiques et les entrées-sorties viruelles sont bien à 128. 
Je mets tout de même une note dans le manuel qui va recommander de désinstaller Jack avant d'installer le Server pour ceux qui se sont déjà servi de Jack. Et ensuite les instrucions pour changer les Preferences si nécessaire.

**Comment by Normandeau** [comment]
David:
«Et ensuite les instructions pour changer les Preferences si nécessaire» 
En essayant de changer les préférences directement dans Jack Pilot j’obtient toutefois ce message à tout coup : 
[cid:66BA9D2E-DBA4-4F9D-AD45-4A5B5BB39EA5@home] 
Je ne sais pas si ce message signifie réellement quelque chose, puisque les changements effectués - quelqu’ils soient - semblent tout de même sauvegardés lorsque je réouvre les préférences.

**Comment by Normandeau** [comment]
J'ai un drôle de problème également depuis ce processus.
J’ai aussi un message d’erreur de JackPilot:
Mais les changements sont effectivement conservés.
Et si je regarde le document JackPilot.plist dans mes Preferences, il est bel et bien daté du bon moment.
![capture d ecran 2017-08-27 a 09 26 18](https://user-images.githubusercontent.com/8959779/29750268-831513a8-8b0a-11e7-85cb-e76f10768920.jpg)

**Comment by belangeo** [comment]
Je ne touche pas au fichier JackPilot.plist, c'est le fichier JAS.jpil qui contient les infos d'entrées/sorties virtuelles et le flag d'auto-connection. Est-ce que la data et l'heure de ce fichier est correct?

**Comment by Normandeau** [comment]
JAS.jpil date du moment de l'installation.
Si je change la fonction Auto-Connection avec JackPilot, c'est JackPilot.plist qui est mis à jour. Je reçois le message d'erreur ci-haut et la préférence n'est pas gardée!
Si je change la fonction Virtual Ins-Outs avec JackPilot, c'est JackPilot.plist qui est mis à jour. Je reçois le message d'erreur ci-haut et la préférence n'est pas gardée!
Dans les deux cas, je n'ai pas démarré Jack après avoir changé les préférences.
Si je change l'une ou l'autre de ces préférences et que je démarre Jack ensuite, alors là les préférences sont changées.
JAS.jpil ne change jamais de date.
À mettre dans le manuel?
