### ISSUE TITLE
Ajouter HRTF

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#58]
Pour mémoire, suite à la réunion du 11 septembre, ajouter le HRTF avant la date possible de sortie, le 1er novembre.

**Comment by led78** [comment]
Pour votre connaissance générale au sujet de l’HRTF, je vous transmet un lien vers la vidéo d’une conférence (GDC 14) donnée par Brian Schmidt sur l’audio 3D. Ça dure une heure, donc pour vous épargner les notions que vous connaissez probablement déjà, je vous suggère d’aller directement à la 15e minute (HRTF déficiences).

http://www.gdcvault.com/play/1020451/3D-Audio-Back-to-the


Le 12 sept. 2017 à 07:14, Robert Normandeau <notifications@github.com<mailto:notifications@github.com>> a écrit :


Pour mémoire, suite à la réunion du 11 septembre, ajouter le HRTF avant la date possible de sortie, le 1er novembre.

**Comment by Normandeau** [comment]
Olivier;
Petite question rapide... Avec le Zirkonium, vous pouvez aller jusqu'à combien de voix en entrée avec l'HRTF avant de saturer le processeur?

**Comment by Normandeau** [comment]
David:
Il me semble que c’est 26 ou 28 entrées.

**Comment by led78** [comment]
HRTF maintenant ajouté au Server; période de tests et de corrections.
