### ISSUE TITLE
Distorsion importante au centre du Server, comparaison avec le Zirkonium

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#59]
Ajouter la possibilité de recevoir des niveaux d'interpolation spatial indépendant pour chaque canal reçu dans le Server, en provenance de leur instance SpatGRIS respectif (voir issue 175 du SpatGRIS).

**Comment by led78** [comment]
Tel que discuté, je transmet ici deux extraits sonores pour lesquelles j'entends de la distorsion lorsqu'ils sont en mouvement. 
L'un de ces sons (orgue) comporte des extrêmes graves - que j'ai testé en appliquant un filtre coupe-bas extrême pour voir si cette distorsion n'était justement pas due aux infra-graves, ce qui ne semble pas être le cas - et l'autre (résonance de cloche) non. Bien entendu, ce sont deux sons assez lisses.

[Interpolation_Sons critiques.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/1306932/Interpolation_Sons.critiques.zip)

**Comment by Xon77** [comment]
Comme déjà signalé, j'entends de la distortion et du grésillement quand des sons lisses avec des extrêmes graves sont en mouvement, même lent, d'où le besoin d'un paramètre indépendant pour chaque canal.
Le problème c'est que même avec une interpolation de 1 avec le VBAP, des grésillements subsistent, pour ce son évidemment.
Voici le son en question :
[O AMBIE14.wav.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/1357645/O.AMBIE14.wav.zip)

**Comment by Normandeau** [comment]
Christophe a écrit:
Merci et Bravo Olivier,
D'après des premiers tests, la distortion VBAP a complètement disparu même avec les pires sons et une interpolation de 0... wow
Je continue à tester....

**Comment by Normandeau** [comment]
Je confirme, même avec une interpolation de 0, le signal est clair, sans ces petits artefacts dans l'aigu. Lors de mouvements extrêmement rapides (cas exceptionnels), l'interpolation vient rapidement lisser le problème.
Excellent. J'attends la confirmation des autres avant de fermer cette issue.
