### ISSUE TITLE
Problème lors de la désactivation d'un solo des outputs

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#61]
Lorsqu’on souhaite avoir un ou des solos sur les sorties, on peut appuyer de manière successive sur le bouton S. Cependant, dès que l’on en désactive un (des solos sélectionnés), les solos sont tous désactivés et ne prennent plus en compte la sélection. Il faut recliquer sur un solo pour les rendre les solos de nouveau actif.

**Comment by Normandeau** [comment]
Bien vu. Pour préciser l'action nécessaire pour retrouver la fonction Solo: il faut désactiver tous les solos pour que la fonction soit à nouveau disponible. Par exemple, si on a 4 solos sur 8 outputs, si on en enlève un, tous les outputs se mettent à fonctionner comme décrit par Christophe. Et pour retrouver la fonction Solo, il faut désactiver les trois autres Solos et réactiver un Solo.
Les Mute des Outputs ainsi que les Solo et Mute des Inputs fonctionnent normalement.
