### ISSUE TITLE
Tous les Inputs sont automatiquement affichées par défaut

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#62]
Avec la  version 008, j'ai toujours une sorte de tache à 45˚ et je me demandais bien à quoi elle correspondait. J'ai désinstallé Jack et le Server, réinstallé le Server et c'était toujours là, quelque soit le projet ou le Speaker Setup ouvert.
En réduisant le nombre d'inputs, on se rend compte que celles-ci sont maintenant automatiquement affichées dans la fenêtre 3D, même si aucun séquenceur n'est ouvert, ou aucune piste active dans celui-ci. La tache, c'est tout simplement un tapon de chiffres empilés les uns sur  les autres. Évidemment cela disparait lorsqu'on décoche l'option Show Source Level.
Est-ce que vous confirmez ceci?
Un seule entrée:
![capture d ecran 2017-10-06 a 14 19 32](https://user-images.githubusercontent.com/8959779/31299196-261186ca-aaa2-11e7-974b-99ae92560ff5.jpg)
64 entrées:
![capture d ecran 2017-10-06 a 14 13 22](https://user-images.githubusercontent.com/8959779/31299217-3bc10ce8-aaa2-11e7-87b5-f6a7c801f9f3.jpg)

**Comment by Xon77** [comment]
En effet, toutes les inputs sont affichées automatiquement à une position par défaut et sont empilés les uns sur les autres, même si aucun séquenceur n'est connecté. Ils pourraient peut-être apparaitre ou s'activer à partir du moment où ils reçoivent des données OSC ?

**Comment by led78** [comment]
Même constat.

**Comment by Normandeau** [comment]
Version 009
Problème résolu.
