### ISSUE TITLE
Les shortcuts Command+chiffre ne marchent pas sur mon clavier azerty

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#63]
Comme indiqué, je n'arrive pas à faire fonctionner les shortcuts incluant un chiffre, comme Show 2D View et les suivants. Peut-être est-ce à cause de la config de mon clavier azerty ? En tout cas avec les lettres, P+C pour colorier, je n'ai pas de problème.

**Comment by Normandeau** [comment]
Tu veux certainement dire Command+chiffre. Sur un clavier Qwerty, ça fonctionne, à une exception près. Command+2, qui ouvre bien la fenêtre 2D mais ne la referme pas, contrairement à toutes les autres fonctions qui utilisent Command.

**Comment by Xon77** [comment]
En effet, c'est la combinaison Command (ou Pomme) + chiffre qui ne fonctionne pas sur mon azerty avec une configuration standard. Je crois que les Command + chiffre sont problématiques pour les azerty car affectés d'origine à d'autres fonctions sur le Mac... Peut-être serait-il mieux d'utiliser des lettres ?

**Comment by led78** [comment]
« Command+2, qui ouvre bien la fenêtre 2D mais ne la referme pas, contrairement à toutes les autres fonctions qui utilisent Command. »
Dès qu'on ouvre la fenêtre 2D, on doit re-sélectionner la fenêtre principale avec la souris pour pouvoir à nouveau donner une commande au server. Sans quoi, le fenêtre 2D n'a que faire des fonctions Command + chiffre.
En sélectionnant à nouveau la fenêtre principale et en faisant à nouveau Command + 2 pour tenter de fermer la fenêtre 2D, celle-ci se ferme mais une nouvelle fenêtre 2D s'ouvre aussitôt : on remarque cela en déplaçant la fenêtre 2D de sa position d'origine; en réappuyant sur Command + 2, la fenêtre 2D retourne aussitôt à sa position d'origine.

**Comment by Normandeau** [comment]
Sauf pour Reaper, les autres séquenceurs que je possède (DP, Live et Logic) ont tous des équivalents clavier formés de Command + Chiffre et essentiellement sur des fonctions d'affichage. Donc ce n'est pas un problème à priori de conserver ceux-ci. Il faut juste s'assurer que cela prend en charge le clavier Azerty.

**Comment by Xon77** [comment]
Pour moi tous les shortcuts fonctionnent tous, hormis un : Skow Numbers (alt+n). Et comme @led78 l'a signalé plus haut, la 2D window (alt+d) et la Speaker Setup Edition window (alt+w) pourraient aussi fermer la fenêtre, alternativement avec l'ouverture, et laisser le focus toujours sur la fenêtre principale du server et non sur la fenêtre nouvellement créée. Je ne sais pas si c'est facile à faire, et c'est peut-être un autre issue.

**Comment by Normandeau** [comment]
Show Numbers (alt+n) fonctionne sur Qwerty.
D'accord avec l'idée de fermer les fenêtres 2D et Speaker Setup Edition avec le raccourci clavier.

**Comment by belangeo** [comment]
On ne peut ouvrir la fenêtre Speaker Setup et laisser le focus sur la fenêtre principale, ça éliminerait toute possibilité d'interaction avec la fenêtre puisque les clics de souris et les touches de clavier iraient directement à la fenêtre principale (sans passer par la fenêtre d'édition).
Pour que le même shortcut ferme la fenêtre, il faut faire une barre de menus propre à ces fenêtres. Comme c'est vraiment pénible de faire une menubar avec Juce, et qu'il y a beaucoup de morceaux importants qui ne sont pas encore implémenté, je vais donner le flag enhancement à cet issue et y voir plus tard.

**Comment by Normandeau** [comment]
À voir éventuellement mais pas une priorité.
