### ISSUE TITLE
Le seuil d'activation des HPs à -60dB. Pourquoi?

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#64]
« L'affichage de l'énergie dans la vue 3D. Seuil de -80 dB pour les sources (pratiquement un on/off) et de -60 dB pour les HPs. À vous de voir, avec un projet réel, si ce seuil est bon! »

Pour ce qui est du seuil d'activation des source à -80 dB, ça me semble bon. Je viens de tester le tout avec une pièce qui comporte des passages forts, moyens et très faibles et les sources demeurent toujours visibles. En somme, le niveau de couleur suit assez bien le niveau d'intensité sonore.

Ce n'est toutefois pas le cas des HPs, puisque le seuil est à -60 dB. Ainsi, un son clairement audible n'est pas toujours représenté par le niveau de blanc des HP. Je me demande donc pourquoi ce seuil? Est-ce parce qu'on estime qu'il y aura toujours plus d'une source émise par un même HP? Si c'est le cas, une différence de 20 dB me semble exagérée; une différence de 10 dB serait à la limite déjà amplement suffisante. 
Pour avoir une augmentation d'intensité de 3dB, il faut avoir deux sources similaires de même intensité. À moins que je ne me trompe, il faudrait donc avoir pas moins de 100 sources de même intensité dirigées vers un même HP (avec un seuil de -60 dB) pour avoir une représentation équivalente à celle d'une seule source à cette intensité (avec un seuil de -80 dB) : 
1. (-60dB) - (-80dB) = 20dB
2. 20 dB = 6,67 fois le double d'intensité (+3dB), puisque 20dB/3dB = 6,67
3. 6,67 puissance de 2 (double le nombre de source) = 101.83 sources de même intensité
4. On peut valider cette information en faisant le calcul inverse. Ex: pour 100 sources d'une intensité de 70dB SPL chacune, 70dB + 10log de 100 = 90dB SPL, soit 20 dB au dessus de 70dB SPL.

Alors que pour une différence de 10dB il faudrait 10 sources de même intensité : 
1. 10 dB = 3,34 fois le double d'intensité (+3dB), puisque 10dB/3dB = 3,34
2. 3,34 puissance de 2 (double le nombre de source) = 10,08 sources de même intensité
3. En reprenant l'exemple précédent avec 10 source d'une intensité de 70 dB SPL chacune, 70dB + 10log de 10 = 80dB SPL, soit 10 dB au dessus de 70 dB SPL.

Pour ma part, il est déjà rare que 10 sources soient à la fois de même intensité ET diffusées par un même HP (ou groupe d'HP) - sans parler du fait qu'ils puissent être en mouvement et étendues.

En testant avec une seule source stéréo étendue verticalement et horizontalement (environ 80° de span dans chaque direction et 180° d'angle entre les deux canaux) en rotation circulaire, je réalise que le HP le plus directement en axe avec l'angle et la position verticale de la source présente un bon niveau de blanc selon l'intensité, alors que tous les autres HP actifs ne sont presque pas visibles (ou pas toujours). Cela semble être lié à l'algorithme VBAP employé. En effet, le niveau du signal étendu de la source est inférieur au niveau du centroid de la source - on peut aussi le constater en regardant les VU-mètres. Cela fait en sorte que, du a son seuil de détection élevé, l'activité des HP ne représente pas l'étendu perçue adéquatement et favorise le centroid spatial de la source.

J'imagine que le tout sera éventuellement calibré en fonction des VU-mètres (vivement l'ajout d'une fenêtre temporelle plus lente - selon la valeur efficace - car la fluctuation des couleurs est présentement très rapide). Il faudra donc débattre de la façon la plus adéquate de représenter la répartition de l'énergie en fonction de l'algorithme de spatialisation et, surtout, de la perception. 

Pour le moment, je suggère d'abaisser le seuil de détection du niveau des HP à au moins -70 dB, ce qui me semble plus raisonnable. Qu'en pensez-vous?

**Comment by Normandeau** [comment]
D'accord

**Comment by led78** [comment]
Je pense qu'on est maintenant satisfait du seuil d'activation des HP, je ferme donc l'issue.
