### ISSUE TITLE
Test Sound : Choix du son

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#65]
Je m'interroge sur le choix du son pour tester l'application (ou même voir comment la spatialisation fonctionne). Actuellement, il y a une onde à 400 hz. Bien que les matériaux avec une énergie concentrée dans des zones spécifiques du spectre créent des points de localisation plus précis, ce n'est pas le cas des sinus, qui sont difficiles à localiser. Des textures (avec des fréquences élevées) changeant rapidement avec de brèves transitoires sont aussi plus faciles à localiser que des matériaux sonores (graves) statiques. 
Peut-être un bruit blanc filtré (rose ou encore davantage filtré dans le bas) avec de brèves impulsions ? ou la possibilité de choix de Test Sound ?

**Comment by led78** [comment]
Je trouve cette question pertinente. On devrait se créer un son de référence autant pour le beta testing que pour le test sound de l'application. En ce moment, le son intégré au Server sert uniquement à valider si le son passe bien dans toutes les entrées et sorties. Si on veut tester plus loin, il faut utiliser un autre son. Quelque chose comme la combinaison d'un bruit brun, une onde en dent de scie dans les médiums et un train d'impulsion.

**Comment by Normandeau** [comment]
Oui, très bonnes remarques.

**Comment by belangeo** [comment]
Ça a été mon premier commentaire quand Nicolas m'a montré le serveur... Une onde sinusoidale est vraiment le pire choix comme son test pour de la localisation! Est-ce que vous utilisez vraiment ce feature? Quand je teste le serveur, je lui envoie du son via une autre application, de toute façon ça prend un input OSC aussi. Je ne suis pas convaincu par le fait que le serveur produise du son en lui-même.

**Comment by Xon77** [comment]
En effet, la commande Test Sound n'est pas vraiment utile pour moi et pourrait être même supprimée... Mais en la testant, je m'étais fait la réflexion sur le choix du son. A voir dans quelles circonstances exactes, cette commande serait utile ?

**Comment by Normandeau** [comment]
Je ne souhaite pas que ça soit supprimé, pour une simple et très bonne raison: c'est très utile de vérifier les sorties de chaque hp en les mettant sur solo un après l'autre. Cela permet éventuellement de calibrer un dispositif également avec une valeur de référence unique. Si on travaille avec un son en entrée, il faut le positionner dans l'espace de telle sorte qu'il soit à peu près réparti également partout et c'est presque impossible de le faire, en tout cas pour calibrer le système.
Par contre, je ne crois pas qu'un sinus soit une bonne référence pour cela.

**Comment by Xon77** [comment]
Cela permettrait éventuellement de calibrer un dispositif avec une valeur de référence unique si le son généré était envoyé directement à toutes les outputs et non généré sur tous les inputs, puis spatialisés, comme c'est le cas actuellement, non ?

**Comment by belangeo** [comment]
Je suis d'accord. Si le sons test (son de référence?) est envoyé à toutes les sorties, il peut servir à faire la calibration du système. Présentement, le son est envoyé aux inputs, il faut donc qu'il passe par le spatialisateur (donc il faut recevoir de l'OSC) pour aller en sortie.
Est-ce que je le rebaptise "Reference Sound" (disons un bruit blanc à -40 dB) et je l'envoie directement aux sorties?

**Comment by Normandeau** [comment]
Oui, mais je diras plutôt un bruit rose, plus généralement utilisé lorsqu'il s'agit de calibrer des hp, car la courbe d'atténuation du bruit rose, de -3Db/octave, est plus proche de notre perception que celle du bruit blanc.

**Comment by belangeo** [comment]
Pas de problème, va pour un bruit rose.

**Comment by Normandeau** [comment]
Ça me va tout à fait.
