### ISSUE TITLE
File et Speaker Setup: une erreur de ce dernier bloque le premier.

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#66]
008
Lorsqu'on sauvegarde un fichier avec le Server (Save), celui-ci inclus le Speaker Setup utilisé (en fait, plutôt un lien vers le Speaker Setup). Or si on fait un changement dans celui-ci, sans nécessairement sauver le fichier Server à nouveau, cela mène à une série de comportements problématiques.
Le premier de ceux-ci est que le Server envoie un message d'erreur, qui annule l'ouverture du fichier Server (le document ici cité dans le message d'erreur existe bel et bien mais il a été modifié depuis la dernière ouverture du document Server):
![capture d ecran 2017-10-10 a 06 41 42](https://user-images.githubusercontent.com/8959779/31389815-0a0acc10-ad87-11e7-8387-36b3785499c0.jpg)
Alors on se dit qu'on va tout fermer et que tout va bien se passer à la prochaine ouverture. Et bien c'est pire, car comme  maintenant que le Server se souvient du dernier document ouvert, la prochaine commande d'ouverture donne ceci, un fichier vide: pas de Speaker Setup, ni de configuration du Server:
![capture d ecran 2017-10-10 a 06 44 30](https://user-images.githubusercontent.com/8959779/31389917-516a3c8a-ad87-11e7-8b76-58015cee20c6.jpg)

Je pense que la meilleure façon de remédier à ce problème est d'établir une priorité au document Server. Car à la suite de l'ouverture d'un fichier vide, comme on vient de le voir, c'est terminé. Le fichier Server que je cherche à ouvrir ne peut plus s'ouvrir. On tombe en effet dans une boucle avec le message d'erreur et rien qui s'ouvre. Pour l'utilisateur c'est vraiment paniquant, car le sentiment que cela génère est que la configuration Server/Speaker Setup est perdue.

Une autre solution, peut-être meilleure, serait de laisser les sauvegardes complètement indépendantes l'une de l'autre. Le Speaker Setup et le fichier Server se chargeraient indépendamment l'un de l'autre. Peut-être que le Server peut garder en mémoire ces derniers et les ouvrir simultanément, mais sans lien entre eux. C'est peut-être cela la bonne solution.

**Comment by Normandeau** [comment]
En plus je n'avais pas remarqué, mais cela génère un message d'erreur, qui fait que le Server est bloqué sur le plan audio:
![capture d ecran 2017-10-10 a 07 11 17](https://user-images.githubusercontent.com/8959779/31391087-6aabbaa4-ad8a-11e7-8d40-d77e73514bff.jpg)

**Comment by belangeo** [comment]
Perso, j'irais avec une seul fichier de sauvegarde dans lequel il y aurait et les paramètres du projet et le speaker setup. Est-ce qu'il y a une raison pour avoir deux fichiers indépendants?

**Comment by Normandeau** [comment]
C'est très utile d'avoir deux fichiers indépendants lors d'un concert par exemple. C'est le même Speaker Setup mais les projets changent selon les pièces du concert. On peut donc ouvrir une configuration de hp, correspondant au dispositif, et ensuite ouvrir un à un les projets des différentes œuvres au programme.
De plus c'est très pratique quand on veut illustrer concrètement le fait que le travail de spatialisation est identique, quelque soit le Speaker Setup, dans un dôme tout au moins. Mais en général, même avec le DBAP éventuellement.

**Comment by belangeo** [comment]
On a bien deux fichiers indépendants mais comme il y a une référence au speaker setup dans le fichier de projet, le speaker setup est reloadé chaque fois qu'on ouvre un projet, qu'il utilise ou non le même setup. 
Est-ce vraiment ce que l'on veut?

**Comment by Normandeau** [comment]
Compte tenu de ce que j'ai trouvé et décrit plus haut, je pense que les deux fichiers devraient rester indépendants et ne plus être liés l'un à l'autre. Par contre, lorsqu'on ouvre le Server, celui-ci pourrait se souvenir des deux derniers documents ouverts, à savoir le dernier Speaker Setup et la dernière configuration du Server.

**Comment by belangeo** [comment]
D'accord!

**Comment by Normandeau** [comment]
Réglé avec la version 009
