### ISSUE TITLE
Spans du VBAP (azimuth / elevation) : interprétation incorrecte du Server

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#67]
Je m'interroge sur la valeur max du span pour le VBAP : 
J'aurais pensé qu'un azimuth span et un élévation span à son maximum distribuerait le son équitablement et diffuserait le son sur tous les HP pour avoir un impact global sur toute la sphère.
Actuellement, le fait de mettre le span au maximum effectue toujours une certaine localisation, bien que très, très floue et le signal n'est jamais réparti sur tous les HP.
Je m'attendrais à avoir un son diffusé partout sans localisation avec des valeurs extrêmes de span.
C'est pourquoi je m'interroge sur la valeur max de span qui a été fixé ?
J'ai l’impression que la valeur max du span est réglée à une valeur minimale.

A titre de comparaison dans SuperCollider, je détermine cette valeur de diffusion du VPAB (spread) de 0 à 100.
" When 0, if the signal is panned exactly to a speaker location the signal is only on that speaker. At values higher than 0, the signal will always be on more than one speaker. This can smooth the panning effect by making localisation blur more constant."

Dans SC, une valeur de 100 diffuse le son sur tous les HP.

**Comment by Normandeau** [comment]
Je transfère ta question dans le dossier SpatGRIS, car c'est de lui que dépendent les réglages de Span. Le Server ne fait que répondre à la commande OSC. Si j'ai bien compris ta question. Voir ma réponse avec le SpatGRIS.

**Comment by Normandeau** [comment]
Les commandes Span sont générées par le SpatGRIS qui envoient des informations OSC au ServerGRIS. Session test simple, piste mono, SpatGRIS 1.01, ServerGRIS 008.

**Azimuth Span**
On voit bien ici que le Azimuth Span, lorsqu'il est poussé presque à sa limite (j'ai laissé une petite marge juste pour voir), est à 360˚:
![azimuth span max](https://user-images.githubusercontent.com/8959779/31525703-4b2a2d7a-af90-11e7-8cfa-beab0e93af47.jpg)

On peut supposer qu'avec ce réglage (Azimuth Span au max et Elevation Span à 0), le son est envoyé sur tous les hp de la couronne inférieure. Voyons à qui ça ressemble. On voit que 4 des 8 hp envoient un signal légèrement plus faible que les 4 premiers:
![azimuth span max input mono output octo](https://user-images.githubusercontent.com/8959779/31525730-665174c8-af90-11e7-9a55-1ccfb92f516c.jpg)

**Azimuth et Elevation Span**
Si on pousse les deux Spans au maximum, cela donne ceci dans le SpatGRIS:
![spans au max spatgris](https://user-images.githubusercontent.com/8959779/31525803-db8d1814-af90-11e7-8037-54b796d5d5e9.jpg)

Et dans le Server, sur un dôme de 32 hp:
![spans au max server 32 hp](https://user-images.githubusercontent.com/8959779/31525766-9c7beac4-af90-11e7-8b07-f3f69b72da74.jpg)

Pourquoi certains hp sont-ils fermés complètement? Et de façon un peu arbitraire?
Il va certainement falloir éclaircir cela.

**Comment by Normandeau** [comment]
Première série de tests exhaustifs: Session test simple, piste mono, SpatGRIS 1.01, ServerGRIS 008, Dome 32 UdeM.

Spans Max R0 0˚:
![spans max r0 0](https://user-images.githubusercontent.com/8959779/31526344-3035a70c-af94-11e7-9d8c-fa5f287e57d0.jpg)

Spans Max R2 0˚:
![spans max r2 0](https://user-images.githubusercontent.com/8959779/31526359-419365c0-af94-11e7-9b2c-ae37324969a0.jpg)

Spans Max R2 90˚:
![spans max r2 90](https://user-images.githubusercontent.com/8959779/31526363-4fd6f0b6-af94-11e7-9e69-319dfc76fb3d.jpg)

Spans Max R2 180˚:
![spans max r2 180](https://user-images.githubusercontent.com/8959779/31526381-6dc317f8-af94-11e7-802d-ed3c27ceeb8b.jpg)

Spans Max R2 270˚:
![spans max r2 270](https://user-images.githubusercontent.com/8959779/31526386-790e195a-af94-11e7-9d59-aed67112fffe.jpg)

Si la prémisse de départ est correcte et se formule ainsi: les fonctions Span, Azimuth et Elevation, permettent de diffuser une source sur l'ensemble du dôme de hp. Alors notre système est défaillant. Il nous faut maintenant déterminer ce qui est défaillant:
- Est-ce le SpatGRIS qui n'envoie pas la bonne information OSC au Server?
- Est-ce le VBAP du Server qui n'arrive pas à exprimer adéquatement les commandes reçues du SpatGRIS?

**Comment by Normandeau** [comment]
Deuxième série de tests exhaustifs: Session test simple, piste mono, SpatGRIS 1.01, Zirkonium MK2, Dome 32 UdeM.

Spans Max R0 0˚:
![spans max r0 0 zirkonium](https://user-images.githubusercontent.com/8959779/31526903-c976e7ca-af97-11e7-959c-c2a45265755d.jpg)

Spans Max R2 0˚:
![spans max r2 0 zirkonium](https://user-images.githubusercontent.com/8959779/31526919-d6ea5590-af97-11e7-81fd-b614a78fa39e.jpg)

Spans Max R2 90˚:
![spans max r2 90 zirkonium](https://user-images.githubusercontent.com/8959779/31526927-e8a0d82c-af97-11e7-882c-17599cab1cec.jpg)

Spans Max R2 180˚:
![spans max r2 180 zirkonium](https://user-images.githubusercontent.com/8959779/31526931-f45ad9ce-af97-11e7-8074-bbc47b8e90e1.jpg)

Spans Max R2 270˚:
![spans max r2 270 zirkonium](https://user-images.githubusercontent.com/8959779/31526940-0574521c-af98-11e7-9817-51b10cf45207.jpg)

C'est très loin d'être égal comme distribution ici, mais au moins il y a du son dans tous les hp tout le temps, sauf à R0, 0˚.
Sur le plan perceptif, je ne peux me prononcer car je fais ces tests chez moi, donc sur 10hp seulement. Mais à priori, j'ai le sentiment, en bougeant la source sur le pourtour du cercle que je n'ai aucune sensation de déplacement. Alors qu'avec le ServerGRIS, il y a absolument une perception de déplacement de la source, ce qui, théoriquement, ne devrait pas être le cas.
Donc à priori, et selon ces deux séries de tests, aux questions posées précédemment la réponse est:
Le VBAP du Server qui arrive pas à exprimer adéquatement les commandes reçues du SpatGRIS.
Bogue majeur.

**Comment by Normandeau** [comment]
Confirmation audio de tous les tests mentionnés dans le B-187:
- Presqu'aucune sensation de déplacement lorsque la source reste sur la couronne la plus basse avec le Zirkonium (la sensation de déplacement tient essentiellement au fait que les niveaux des hp ne sont pas égaux);
- Sensation claire de déplacement lorsque la source reste sur la couronne la plus basse avec le Server

Confirmation des mêmes comportements avec ZirkOSC3, notamment avec le Server où les «trous» de hp sont les mêmes (les haut-parleurs inactifs) qu'avec SpatGRIS.

**Comment by Normandeau** [comment]
Il semble que ça soit (partiellement) les valeurs de l'Elevation qui ne soient pas bien prises en compte. On voit ici que le paramètre Elevation n'est que partiellement pris en compte: lorsque la source est en bas, c'est à peu près la moitié inférieure de la hauteur du dôme qui est couverte. Lorsque la source est au Zénith, c'est la moitié supérieure qui est couverte.

ElevationSpan au maximum, source Zenith à 0:

![elevationspan max source zenith 0](https://user-images.githubusercontent.com/8959779/31561452-ee7b1bfc-b025-11e7-98db-7fbcb97e1953.jpg)

ElevationSpan au maximum, source Zenith à 90:

![elevationspan max source zenith 90](https://user-images.githubusercontent.com/8959779/31561471-fb6213b6-b025-11e7-8a4b-79eb1671a88f.jpg)

**Comment by Xon77** [comment]
La perception du span du VBAP me semble correct. 
Maintenant, en poussant les spans en azimuth et en élévation à fond, tous les HP sont impactés, comme on peut le voir ci-dessous : 
<img width="591" alt="span a fond" src="https://user-images.githubusercontent.com/1010040/31791440-85a1d308-b4e6-11e7-888b-4c96f155c985.png">

Cependant, il me reste une toute petite interrogation. Dans SC, en poussant le span à fond, il me semble bien que j'ai le même niveau sur tous les HP. Ils sont impactés tous de la même façon. Alors qu'ici il peut rester d'infimes différences, si l'on concentre sur le span de l'azimuth. Pourquoi ?
Ne devrait-il pas y avoir aucune localisation si le span est poussé à fond ?

Par exemple : Span azimuth à fond avec une source mono devant : 
<img width="718" alt="devant1" src="https://user-images.githubusercontent.com/1010040/31791624-2ad8c822-b4e7-11e7-91c1-9deec877af23.png">

<img width="583" alt="devant" src="https://user-images.githubusercontent.com/1010040/31791631-319f50d6-b4e7-11e7-85ce-d64db695fa6b.png">

Et Span azimuth à fond avec une source mono à gauche : 
<img width="715" alt="gauche1" src="https://user-images.githubusercontent.com/1010040/31791649-45f8175c-b4e7-11e7-9d2e-0c8cb62a14e8.png">
 
<img width="586" alt="gauche" src="https://user-images.githubusercontent.com/1010040/31791666-5835961a-b4e7-11e7-9049-479c2cc6ba75.png">

**Comment by Normandeau** [comment]
Le Span est un peu jovialiste!
En effet, l'Azimuth Span déborde maintenant dans les sorties directes. Alors que ces dernières ne devraient pas faire partie de la spatialisation VBAP (d'où leur nom: sorties directes), elles sont maintenant intégrées dans le processus de spatialisation, avec ou sans Span. Elevation Span ne semble pas en cause.

Voici à quoi ça ressemble sans Span. Ici, les sorties directes sont les sorties 13-14. Aucunes entrées ne sont actuellement assignées vers celles-ci. J'ai remarqué que les sorties directes, qui sont placées dans ce dispositif du côté positif de l'axe des Y (les deux cubes gris), n'étaient affectées que lorsque la source est elle-même placé du côté positif des Y:

![sorties directes sans span](https://user-images.githubusercontent.com/8959779/31820332-d63313c6-b56e-11e7-88ea-d73458f638c6.jpg)

Lorsque la source se déplace du côté négatif, le signal quitte les sorties directes:

![sorties directes sans span y negatif](https://user-images.githubusercontent.com/8959779/31820618-28e9773a-b570-11e7-893a-e355ab31f85a.jpg)

Avec Span, les sorties directes sont affectées par le son lorsque celui-ci est à proximité du cercle extérieur de hp:

![sorties directes avec span cercle exterieur](https://user-images.githubusercontent.com/8959779/31820801-eb627fb4-b570-11e7-8c41-96e4e62c4b94.jpg)

Mais l'effet disparaît au fur et à mesure qu'on s'approche du cercle suivant de hp (ici, les deux hp du haut), et il disparaît complètement lorsqu'il est passé au-delà:

![sorties directes avec span cercle interieur](https://user-images.githubusercontent.com/8959779/31820839-0978567c-b571-11e7-80f2-75d2447e0066.jpg)

 C'est comme si les sorties directes étaient maintenant intégrées au groupe de hp le plus proche de celles-ci.

**Comment by Normandeau** [comment]
Une précision si ça peut aider. Le comportement du signal vers les sorties directes est différent avec une source monophonique. Ici, l'Azimuth Span ne suffit pas à faire sortie le signal vers les sorties directes (ici 13-14):

![span azimuth mono](https://user-images.githubusercontent.com/8959779/31822560-2a22f8cc-b577-11e7-8f35-af92fa637a96.jpg)

Il faut mettre à contribution les deux Span pour forcer le signal vers les sorties directes:

![span azimuth elevation mono](https://user-images.githubusercontent.com/8959779/31822578-3f0c288a-b577-11e7-8d7b-615aab8a3d19.jpg)

**Comment by belangeo** [comment]
Oui, je vois le problème, je vais le corriger!

**Comment by belangeo** [comment]
Pour ce qui est des différences entre le span du server et celui de supercollider (et du zirkonium je suppose), voici ce qu'il se passe. Dans l'algo d'origine (Ville Pulki), passer 70% de span, le gain de chaque HP est considérablement augmenter et la normalisation fait en sorte que tous les HP semblent avoir à peu près le même niveau (ils sont quand même différents). Après avoir fait des tests (et tenant compte qu'on a pas une seule valeur de span mais deux), je trouvais que l'algo d'origine était un peu trop brute. Passer 70% de span (en azimuth ET en élévation), ça donnait un bump de gain audible dans la courbe de volume. J'ai donc calmé un peu l'algo pour avoir une courbe plus lisse (les mouvements rapides sont plus fluides de cette façon).

**Comment by Normandeau** [comment]
Dans mon setup maison de 10hp, je n'ai même plus besoin d'ouvrir les Spans, le signal de toutes les pistes coulent dans les deux sorties directes lorsque celles-là passent devant celles-ci. Autrement dit, les hp des sorties directes placés entre 3-1 et 2-4 (comme dans Hexa) recevaient du signal lorsque les sources passaient devant ces hp là (les pistes 17-18, assignées aux sorties directes 13-14, sont mutées):

![sorties directes pre-compute](https://user-images.githubusercontent.com/8959779/32118571-2665cc06-bb20-11e7-891b-0879a78ce8d3.jpg)

Je me suis demandé ce qui se passerait si je plaçais les subs (donc les sorties directes) à 0. J'appuie ensuite sur Compute et ça marche: plus de coulage! Je les remet à leur endroit «physique», soit à 315˚ et 45˚, j'appuie sur Compute: plus de coulage!

![sorties directes post-compute](https://user-images.githubusercontent.com/8959779/32118581-2e8495d4-bb20-11e7-93d4-5429b3d68a48.jpg)

Je sauvegarde le tout: Speaker Setup et Project. En plus je re-sauvegarde lorsque il me le demande à nouveau à la fin du processus, j'écrase donc l'ancien projet. Puis je rouvre le tout, et ça coule de nouveau dans les sorties directes. Je re-Compute le Speaker Setup et ça s'arrête.
Autrement dit, il y a quelque chose de volatil dans le processus, qui n'est pas sauvegardé après l'opération Compute.

**Comment by belangeo** [comment]
J'ai corrigé ce problème en particulier aujourd'hui (et celui des spans qui coulaient dans les sorties directes)!

**Comment by Normandeau** [comment]
Excellent!!!

**Comment by Normandeau** [comment]
Version 010
Lorsqu'on ajoute des hp supplémentaires dans un Speaker Setup après des sorties directes, celles-ci sont récupérées par le Server comme faisant partie du VBAP. Ici, les sorties directes 5-6 sont incorporées dans les Triplets et dans le système de spatialisation:

![sorties directes spatialisees](https://user-images.githubusercontent.com/8959779/32169632-c3c0da6c-bd47-11e7-9568-23ee2ebaa863.jpg)

**Comment by belangeo** [comment]
Je n'ai pas encore travaillé l'ordonnancement automatique des HPs... Pour l'instant, les sorties directes doivent les derniers HPs du setup.

**Comment by Normandeau** [comment]
V012
Les sorties directes peuvent maintenant être n'importe où dans la succession des hp sans être pris en considération par le VBAP.
