### ISSUE TITLE
Le shortcut Colorize Inputs (Cmd+C) ne fonctionne pas directement après avoir changé le nombre d'inputs

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#68]
C'est juste un très, très petit détail comparé aux autres issues : Après avoir changé le nombre d'inputs et appuyé sur enter, le nombre d'inputs se modifie normalement, mais il n'est pas possible de changer les couleurs directement via le shortcut Command+C (Les autres shortcuts semblent fonctionner). On est obligé de sélectionner ou modifier autre chose, comme le niveau de gain ou d'interpolation, pour que le focus ne soit plus sur la boite du nombre d'inputs, et qu'ainsi le shortcut Colorize Inputs fonctionne.

Peut-être juste retirer le focus de la boite Inputs après avoir appuyé sur Enter ?

**Comment by belangeo** [comment]
Yep, assez irritant comme comportement de la part des boîtes à chiffre... Je vaisy voir!

**Comment by Normandeau** [comment]
Tu fais bien de le mentionner. C'est juste, le focus de la boîte du nombre d'Inputs est le seul à ne pas être désélectionné après avoir appuyer sur Enter (Gain et Interpolation fonctionnent bien). À corriger.
