### ISSUE TITLE
Crash logique du serveur lors de l'ouverture d'un plugin Spatgris dont l'entrée n'est pas disponible sur le Servergris

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#69]
C'est un crash logique pour moi.

Exemple : 
On ouvre le ServerGRIS avec 64 entrées.
On ouvre le séquenceur (dans ce cas Reaper), met un SpatGRIS en OSC sur une piste, avec un first source ID supérieur au nombre d'entrées dans le ServerGRIS (dans ce cas 65).
On ferme la fenêtre du plugin -> crash logique puisque l'entrée n'est pas disponible dans le server.

Mais au lieu de cracher, peut-être serait-il préférable de mentionner à l'utilisateur d'augmenter le nombre d'entrées du ServerGris et de l'adapter en fonction du source ID le plus élevé parmi les plugin SpatGRIS de son projet.

Je voulais juste le signaler, même si c'est loin, loin... dans les priorités.

**Comment by belangeo** [comment]
Ça devrait être assez facile à prévenir...

**Comment by Normandeau** [comment]
Confirmé avec DP. Juste pour être précis, au moment de la fermeture de StaGRIS, c'est le Server qui crache. C'est effectivement embêtant lorsqu'on ouvre un projet avec un nombre supérieur de sorties que celles qui étaient disponibles dans le projet précédent, Server crache immédiatement.
