### ISSUE TITLE
Show Speaker Level : Couleurs

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#70]
Actuellement, la couleur des HP passe de gris à blanc en fonction du volume.
Ne serait ce pas plus visible de noir à blanc pour renforcer le contraste et avoir davantage d'échelles de valeurs ?

**Comment by belangeo** [comment]
Si on va du noir au blanc, le HP disparaît en milieu de course lorsqu'il coincide avec la couleur de background. Ça fait un peu étrange...

**Comment by Xon77** [comment]
Peut-être dans ce cas, changer la couleur de fond dans une autre couleur, par exemple en bleu aux couleurs de lUdem. A discuter ensemble...

**Comment by belangeo** [comment]
Si on donne une couleur (qui n'est pas un ton de gris) au background de la vue 3D, les sources du même ton vont se perdre dans la couleur de fond...
