### ISSUE TITLE
Amélioration graphique

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#71]
Cela me taraudait depuis le début, alors finalement je l'écris: il faut modifier l'interface graphique du Server. Ce qui est actuellement le plus gênant, c'est la largeur des VU-mètres: beaucoup trop grande. Il faut réduire de moitié au moins. Quitte à superposer les M et S de Mute et Solo et à enlever le mot «nil» en dessous de chacune des entrées. Cette case pourrait tout simplement être vide, à moins d'y placer une valeur pour une sortie directe.

**Comment by belangeo** [comment]
J'ai toujours trouvé les vu-mètres trop larges moi aussi!

**Comment by led78** [comment]
Aussi en profiter pour séparer les VU-mètres des sorties directes des autres VU-mètres (spatialisés), comme c'est le cas dans le Zirkonium. Ça aide à ne pas les confondre justement avec les niveaux des HP du dôme, notamment.

**Comment by Normandeau** [comment]
Deux choses sur les VU mètres.

**1. Valeur calibrée affichée partout.**
Finalement, ce n'est pas si mal d'avoir les valeurs en dB affichées dans tous les VU mètres! Je sais qu'on avait remis cela en question à la dernière réunion, mais c'est assez utile finalement. Qu'en pensez-vous?

**2. Largeur des VU mètres.**
Je crois qu'on devrait gagner encore du terrain sur ce plan. L'objectif serait de pouvoir afficher au moins 64 canaux sur un écran Retina. Actuellement on est limité à 54.
Suggestions:
- Placer les m et s (de Mute et Solo) l'un au dessus de l'autre (j'ai une préférence pour cet ordre, mais aucun séquenceur ne les dispose de la même manière...).
- Sorties directes: enlever l'affichage du no et le remplacer par un carré de couleur, le même qui apparait dans la fenêtre du Speaker Setup. Et lorsqu'on clique sur le carré, le no de la sortie directe apparaît.
- Ou alors réduire la taille de la police, ou changer celle-ci.
Cela sera-t-il suffisant?

Par comparaison, Zirkonium (64) vs Server (54) sur écran Retina:
![zirko vs server 64 a 54](https://user-images.githubusercontent.com/8959779/33796717-7491e9c2-dcc8-11e7-80a9-6a276a8b53b2.jpg)

**Comment by led78** [comment]
J'aime aussi beaucoup le fait que les VU-mètres soient gradués. Par contre, je trouve ça un peu chargé visuellement. Je crois qu'il serait possible d'avoir une police plus fine qui permettrait à la fois de réduire la tailler des VU-mètres alléger le poids visuel de la gradation.

À titre d'exemple, la gradation des VU-mètres dans Logic est très fine, mais tout de même bien visible.

![vu-metres_server](https://user-images.githubusercontent.com/13606544/33798184-2b1d317e-dce2-11e7-9e53-1d2f889f432e.jpeg)

**Comment by Normandeau** [comment]
V013
Olivier: Removed 5 pixels to vu-meter width
64 entrées sur mon écran rétina.
Bravo.

**Comment by led78** [comment]
Pour le plaisir, sur mon écran ultra-wide je peux maintenant voir jusqu'à 92 VU-mètres!
![nb_vu-metres_server](https://user-images.githubusercontent.com/13606544/34118125-da88e8f0-e3eb-11e7-99f6-fc1be5818251.jpeg)

**Comment by Normandeau** [comment]
C'est quoi ce p'tit écran! Sur mon 4K de 24" (résolution de 3840X2160), j'ai 138 entrées! Mais en résolution «normale» (3008X1692), j'ai 108 entrées.
Je crois que c'est confortable...
