### ISSUE TITLE
Copier-coller des couleurs des Inputs

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#72]
Christophe:

Je  trouve que la possibilité de pouvoir copier en mémoire une couleur de  l'input (dans la fenêtre de couleurs qui s'affiche quand on clique sur  le chiffre de l'input, via l'ajout de 2 boutons copy / piste) serait  pratique, afin d'appliquer et coller la couleur à d'autres inputs,  lorsqu'on rentre dans la boite de sélection de la couleur. Ceci  permettrait d'appliquer rapidement exactement la même couleur à des  groupes de pistes, lorsqu'on organise son projet. Je ne sais pas si  c'est clair... c'est encore un petit détail.

**Comment by Normandeau** [comment]
David:
Je seconde. C'est aussi ce que je faisais dans le serveur du Zirkonium. C'était bien pratique.

**Comment by Normandeau** [comment]
Je tierce

**Comment by led78** [comment]
J'ajouterais aussi la fonction de «poire à couleur» qui permet de copier une couleur externe au ServerGRIS (ex. couleur de piste dans le DAW) pour l'appliquer à l'entrée correspondante dans le ServerGRIS.

**Comment by Normandeau** [comment]
V217
La gestion des couleurs est un peu rudimentaire dans SpatGRIS2...

**Comment by MelanieFrisoli** [comment]
Tout à fait d'accord! Je m'étais dit que j'allais mettre de belles couleurs pour mes 60 pistes en input dans SpatGris mais j'ai vite abandonné la tâche. Une "poire de couleur" ce serait excellent ainsi que les commandes copy/paste.
Je me permets d'ajouter que la sélection de plusieurs pistes simultanément (avec Shift par exemple) serait pratique pour colorer plusieurs pistes d'un coup.

**Comment by Normandeau** [comment]
V2112
Serait-il possible de mettre la roue de couleur normale de MacOS ici (une issue qui date de 2017!) plutôt que le kit Juce qui est plutôt rudimentaire? Ou alors cela limitera SpatGRIS à MacOS?

![Capture d’écran, le 2021-06-27 à 15 15 44](https://user-images.githubusercontent.com/8959779/123556692-a4fcee00-d75a-11eb-95a5-d66d76a0cbc4.jpg)

**Comment by SamuelBeland** [comment]
Je ne connaissais pas l'existence du "color picker" standard de Mac avant de lire ce commentaire!

JUCE ne fourni aucune méthode simple pour l'utiliser, mais il faudrait savoir si ça peut être ajouté facilement.

Sinon, je ne sais pas trop comment on pourrait procéder pour l'application de couleur à plusieurs HP (copier + coller). Peut-être qu'en sélectionnant plusieurs speakers, la sélection de couleur pourrait s'appliquer à chacun d'entre eux?

**Comment by Normandeau** [comment]
Vraiment pas urgent pour le moment. Encore une fois, c'est utile pour nous, car on fabrique des speaker setup à la tonne, mais pour l'utilisateur moyen, ce serait plutôt l'exception.

**Comment by Normandeau** [comment]
V2114
Je pense que la fonction clic-droit fait maintenant le travail à ce sujet.
