### ISSUE TITLE
Le mode High performance non présent dans la version 0.0.9

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#73]
Le mode High Performance, disponible dans la version précédente, n'est pas présent dans la version 0.0.9 dans les menus.

**Comment by belangeo** [comment]
C'est voulu. Je l'ai caché. Dans la vue 3D, cette fonction n'a pratiquement aucun effet. Elle sert surtout à alléger les vu-mètres. Je dois d'abord revoir le code des vu-mètres et ensuite on évaluera la nécéssité de réintégrer cette fonction.
