### ISSUE TITLE
Save Speakers

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#74]
Version 009.
Le Save Speakers a été déplacé dans le menu File et se nomme désormais Export Speaker Setup.
Plusieurs choses à cet égard.
Je ne suis pas certain que c'est une bonne idée. Je préférais le Save Speaker dans la fenêtre Speaker Setup Edition (qui se nomme toujours Speaker config lorsqu'on ouvre la fenêtre...). Parce qu'après avoir fait une modification on peut facilement la perdre sans que le Server ne nous prévienne. Je viens de faire le test:
1. J'ouvre un Project.
2. J'ouvre la fenêtre Speaker Setup Edition Window (alt-w)
3. J'ajoute deux speakers dans la configuration ouverte.
4. Je ferme  la fenêtre Speaker Setup Edition Window
5. Je quitte Server, j'obtiens cette fenêtre:

![save preset](https://user-images.githubusercontent.com/8959779/31823396-0d034906-b57a-11e7-8e75-7ec730cd7767.jpg)

Je choisis Save, et il me demande si je veux remplacer le projet originel:

![replace](https://user-images.githubusercontent.com/8959779/31823442-35b1f79e-b57a-11e7-814e-2d4e757155a8.jpg)

Je confirme, et il me demande encore si je veux sauvegarder le Preset:

![save preset again](https://user-images.githubusercontent.com/8959779/31823494-55af7544-b57a-11e7-91e2-73e9a9470679.jpg)

OK!!!

Je rouvre le Server, qui affiche par défaut la dernière configuration et mon Speaker Setup ne contient pas les deux hp ajoutés. J'ai donc perdu cela.
De cela, je déduis:
- que le Save Speaker n'est pas à la bonne place et devrait retourner dans la fenêtre d'édition;
- que le mot Preset devrait être remplacé dans le processus de sauvegarde par Project.
- que la deuxième fenêtre de sauvegarde est inutile et n'est qu'un doublon sans fonction réelle, à enlever.

**Comment by Normandeau** [comment]
Un autre argument en faveur de replacement de Save Speakers dans la fenêtre d'édition de celui-ci, c'est la fonction Compute. Je l'oublie tout le temps celle-là! Il faut que j'ajoute cela dans le manuel.
Un exemple: le problème décrit dans l'issue #67 
Dans mon setup maison de 10hp, je n'avais même plus besoin d'ouvrir les Spans, le signal de toutes les pistes coulaient dans les deux sorties directes lorsque celles-là passaient devant celles-ci. Autrement dit, les hp des sorties directes placés entre 3-1 et 2-4 (comme dans Hexa) recevaient du signal lorsque les sources passaient devant ces hp là. Je me suis demandé ce qui se passerait si je plaçais les subs (donc les sorties directes) à 0. J'appuie ensuite sur Compute et ça marche: plus de coulage! Je les remet à leur endroit «physique», soit à 315˚ et 45˚, j'appuie sur Compute: plus de coulage!
Que direz-vous de cette idée: Save & Compute réunis ensemble?

**Comment by belangeo** [comment]
En fait, le problème était la façon dont un speaker setup était chargé lorsqu'on ouvre un projet. Le fait de faire un Compute réparait le tout. Ce problème est réparé. Maintenant, que diriez-vous que l'application demande de sauvegarder le setup au moment où on ferme la fenêtre d'édition (s'il y a eu des modifications)? Ça éviterait de remettre un bouton (J'ai quelque chose contre les boutons qui font un save!).

**Comment by Normandeau** [comment]
Absolument!
