### ISSUE TITLE
Speaker Setup en forme de sphère

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#77]
Bonjour,
Puisque la sphère a été ajoutée dans le menu View, je me suis demandé si on pouvait effectivement construire une sphère de hp. On peut, mais seulement en mode individuel, et encore, ce n'est pas simple. Autrement dit on peut ajouter un hp avec un Zénith d'une valeur négative, mais on ne peut pas ajouter une couronne d'un seul coup car les valeurs négatives de Zenith n'y sont pas acceptées, ni non plus les valeurs supérieures à 90. En fait, les valeurs négatives de Zenith sont «faussement» acceptées dans la mise au point d'un hp individuel, ici à -35:

![sphere z -35](https://user-images.githubusercontent.com/8959779/31889816-177f9f90-b7cf-11e7-9391-88621855813a.jpg)

En fait, dès qu'on clique ailleurs, la valeur négative est ramenée à une valeur positive complémentaire, ici donc à 325:

![sphere z 325](https://user-images.githubusercontent.com/8959779/31889904-5effef78-b7cf-11e7-917f-e21ff5a2d4b3.jpg)

Cela met en valeur que le comportement des valeurs mathématiques de Zenith est problématique dans le Server actuellement. J'avais compris que la valeur maximale était de 90˚ et que les valeurs supérieurs étaient ramenées à l’intérieur de ce maximum par soustraction. Ainsi, une valeur entrée de 135 allait être ramenée à 45 (135-90), d'accord?
Parfait, alors si je mets -45˚, ça devrait être à 45˚ sous le niveau horizontal, d'accord? Et ça l'est, sauf que ça affiche 315! Et si j'entre directement 315? Et bien ça marche!
En fait, si on entre des valeurs comprises entre 91 et 180, elles sont soustraites de 90. Au-delà de 180, la valeur de Zenith se comporte... n'importe comment! Je n'ai pas le temps de tester cela davantage (essayez les valeurs entre 270 et 360 juste pour voir...), mais pourquoi ne pas envisager la valeur de Zenith comme un cercle de 360˚, qui ferait le tour de la sphère?

**Comment by belangeo** [comment]
D'abord, plus besoin de cliquer ailleurs pour rafraichir les valeurs. Dès qu'une valeur est entrée dans une case, elle se met à jour (si besoin est) dès qu'on appuie sur Enter.

En ce qui concerne faire le tour de la sphère avec le zenith, ça ne fonctionne pas puisque passer 90 (ou -90) degrés, la valeur de zénith entre en conflit avec celle d'azimuth. Ça ferait faire un bond de 180 degrés en azimuth...

 Il n'y a pas de raison que le Server ne permette pas des setups en sphère complète (la partie en dessous) même si je suppose que c'est assez rare...! J'ai modifé la gestion du zénith pour qu'elle est comme ambitus -90 à 90. 

À noter que j'ai jamais vue un kit de réponses impulsionnelles pour le HRTF qui descendait plus bas que -40 degrés.

**Comment by Normandeau** [comment]
Sphère 40 hp

![sphere 40hp](https://user-images.githubusercontent.com/8959779/33527112-22efca02-d819-11e7-962d-3c409287939f.jpg)

Les valeurs du Zénith fonctionnent bien de -90 à +90. Cependant la sphère formée, lorsqu'on active les triplets, n'est probablement pas fonctionnelle. En effet, on peut voir que les triangulations se font souvent entre des niveaux non-consécutifs (j'en ai indiqué 2 avec des flèches), ce qui signifie en général que le signal sera erratique.
En regardant de plus près, ce sont les deux cercle de hp proche de l'horizon (Zenith 0) qui passe par dessus le cercle suivant dans la direction opposée. Autrement dit, le cercle à +10 passe directement au cercle à -30, plutôt qu'au cercle à -10. Et inversement le cercle à -10, passe au cercle de +30 plutôt qu'à +10.

![sphere trplets](https://user-images.githubusercontent.com/8959779/33527069-56fc3ea8-d818-11e7-92b5-369117a06a2f.jpg)

Pas une priorité pour le moment, à moins que cela ne soit significatif de quelque chose d'autre.

**Comment by belangeo** [comment]
On dirait bien que dans certains cas de figure, le VBAP n'arrive pas à faire sa triangulation correctement. J'ai essayé d'ajouter un cercle de zénith 0 dans le setup illustré ci-dessus et le problème persite. Pourtant j'ai fait deux sphères complètes dont la triangulation est correcte (setups joint à ce message). Un système qui serait pas mal serait de faire une analyse de la triangulation après avoir fait un Compute et d'afficher un message si VBAP n'est pas capable de gérer correctement le setup.

[setup_spheres.zip](https://github.com/GRIS-UdeM/ServerGRIS/files/1552480/setup_spheres.zip)

**Comment by Normandeau** [comment]
Voir Issue no 94
