### ISSUE TITLE
Zenith impossible à 0 lorsque Radius plus grand que 1

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#79]
Version 010, Speaker Setup
Lorsque le Radius est plus grand que 1, comme ici pour les 3 premières sorties directes, on ne peut plus mettre le Zenith à 0. Soit le chiffre qui apparaît par défaut est délirant (sortie 43), soit c'est une décimale qui ne correspond pas à celle qui a été entrée (0.1) (sorties 5-6). La seule manière de placer le Zenith à 0 est de mettre le Radius à 1 (sortie 44):

![zenith impossible a 0 lorsque radius plus grand que 1](https://user-images.githubusercontent.com/8959779/32169935-e273df30-bd48-11e7-8390-e0499598ebdf.jpg)

**Comment by belangeo** [comment]
Semble être relié à la résolution des calculs mathématiques en floats.... On est très près des valeurs demandées.

-4.83805e-06 = -0.00000483805

**Comment by Normandeau** [comment]
V012
Même constat. Peut-être très près, c'est juste pas élégant!

**Comment by belangeo** [comment]
Oui, je n'ai rien modifié... Je peux clipper les très petites valeurs pour afficher un 0 à la place.

**Comment by belangeo** [comment]
Est-ce qu'on ne devrait pas limiter azimuth et zenith à des nombres entiers dans le setup? Je ne crois pas que 0.1 degré fasse une grosse différence au niveau perceptif et ça éviterait les erreurs d'arrondi provoquées par les calculs en float.

**Comment by Normandeau** [comment]
C'est clair!!!

**Comment by belangeo** [comment]
Done!

**Comment by Normandeau** [comment]
V013
Oui cela règle le problème pour Azimuth et Zenith, mais a-t-on vraiment besoin de 5 décimales pour X, Y, et Z?

![capture d ecran 2017-12-15 a 13 54 31](https://user-images.githubusercontent.com/8959779/34056064-a423d4da-e19f-11e7-8abc-c0d31a6cf8ee.jpg)

**Comment by belangeo** [comment]
On pourrait clipper à 3 décimales à l'affichage...

**Comment by Normandeau** [comment]
Oui, et retour sur Azimuth: je crois qu'il nous faut conserver l'affichage à au moins une décimale, voire deux. On divise souvent le cercle en valeurs qui nous donne une décimale et c'est rassurant de la voir affichée correctement. Désolé du trouble...
Par exemple: 360˚ / 16 = 22.5 ou 360 / 32 = 11.25˚.

**Comment by belangeo** [comment]
Pas de problème!

**Comment by Normandeau** [comment]
Ok, 4 décimales finalement pour X, Y et Z?

**Comment by belangeo** [comment]
X/Y/Z sont recalculés lorsque l'on change azimuth/zénith et vice versa. Si on restreint trop les données pour les deux types de coordonnées, on fausse les calculs. J'y suis allé pour un compromis raisonnable!

**Comment by Normandeau** [comment]
Parfait.
