### ISSUE TITLE
Mode HRTF : changement abrupte du son lié au mouvement de la source

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#80]
J'ai effectué quelques premiers tests avec le mode d'écoute HRTF. En écoutant une pièce spatialisé dans ce mode, j'entend quelques ratés, comme des changements abruptes du spectre d'un son, et ce quelque soit l'interpolation dans le Server. En isolant un son particulièrement problématique (en mettant la piste sur solo dans le DAW), je constate que le mouvement (spatial) écrit en automation sur cette piste est très lent - cette pièce avait été écrite avec ZirkOSC2, ce qui ne devrait pas changer grand chose par rapport à SpatGRIS en mode OSC, mais reste tout de même à le tester si cela pourrait en être la cause.
Je ne suis pas certain de la façon dont l'HRTF est implémentée, mais est-ce que cela pourrait être du à un passage abrupte d'une courbe de fréquence à une autre selon le changement de position de la source? Ainsi, plus un mouvement est lent, plus l'interpolation entre deux courbes de fréquence devrait être proportionnellement lente?
Ces coupures ne surviennent pas avec le mode HRTF du Zirkonium.

**Comment by belangeo** [comment]
Mmm... J'ai essayé d'éliminer l'interpolation entre 2 filtres (ex.: moitié du filtre à 5° et moitié du filtre à 10° pour une position de 7.5°) en ajoutant des réponses impulsionnelles dans le kit. C'est probablement inévitable d'interpoler... À noter que l'interpolation du Server concerne le VBAP et non l'interpolation en deux filtres HRTF (deux concepts complètement différents). Il va y avoir du travail pour rendre l'interface intuitive en fonction du mode de spatialisation sélectionné...

**Comment by Xon77** [comment]
En spatialisant 29 canaux dans Reaper, j'observe de nombreux grésillements sonores (lors de mouvements rapides sur un son) et de fréquentes coupures sonores en mode HRTF, probablement dû à une surcharge de CPU. Le CPU à côté de Jack Run clignote en rouge et affiche des CPU très élevées. Je m'interroge donc sur la façon de rendre le HRTF. Actuellement, j'imagine que chaque source utilise des filtres HRTF, ce qui est très lourd. Mais ne serait-il pas possible et plus économique qu'un rendu (caché) en VBAP soit d'abord effectué, puis d'utiliser ce format multiphonique pour le convertir en binaural (peut-être moins précis, mais suffisant pour avoir une idée du rendu spatial) ?

**Comment by VinyMo** [comment]
J’observe les mêmes grésillements dans Dp à chaque déplacements de la source, lents ou rapides. D’autre part, les spans (AS+ES) ne fonctionnent pas. C’est apparent à l’écoute, bien qu’on voit le span s’activer dans le graphique, mais aucune différence n’apparait non plus sur un fichier enregistré.
On Nov 8, 2017, at 15:12, Christophe Lengelé <notifications@github.com<mailto:notifications@github.com>> wrote:


En spatialisant 29 canaux dans Reaper, j'observe de nombreux grésillements sonores (lors de mouvements rapides sur un son) et de fréquentes coupures sonores en mode HRTF, probablement dû à une surcharge de CPU. Le CPU à côté de Jack Run clignote en rouge et affiche des CPU très élevées. Je m'interroge donc sur la façon de rendre le HRTF. Actuellement, j'imagine que chaque source utilise des filtres HRTF, ce qui est très lourd. Mais ne serait-il pas possible et plus économique qu'un rendu (caché) en VBAP soit d'abord effectué, puis d'utiliser ce format multiphonique pour le convertir en binaural (peut-être moins précis, mais suffisant pour avoir une idée du rendu spatial) ?

**Comment by VinyMo** [comment]
Même constatation dans Reaper, aucun span.

On Nov 14, 2017, at 10:26, VinyMo <notifications@github.com<mailto:notifications@github.com>> wrote:

J’observe les mêmes grésillements dans Dp à chaque déplacements de la source, lents ou rapides. D’autre part, les spans (AS+ES) ne fonctionnent pas. C’est apparent à l’écoute, bien qu’on voit le span s’activer dans le graphique, mais aucune différence n’apparait non plus sur un fichier enregistré.
On Nov 8, 2017, at 15:12, Christophe Lengelé <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


En spatialisant 29 canaux dans Reaper, j'observe de nombreux grésillements sonores (lors de mouvements rapides sur un son) et de fréquentes coupures sonores en mode HRTF, probablement dû à une surcharge de CPU. Le CPU à côté de Jack Run clignote en rouge et affiche des CPU très élevées. Je m'interroge donc sur la façon de rendre le HRTF. Actuellement, j'imagine que chaque source utilise des filtres HRTF, ce qui est très lourd. Mais ne serait-il pas possible et plus économique qu'un rendu (caché) en VBAP soit d'abord effectué, puis d'utiliser ce format multiphonique pour le convertir en binaural (peut-être moins précis, mais suffisant pour avoir une idée du rendu spatial) ?

**Comment by belangeo** [comment]
> Mais ne serait-il pas possible et plus économique qu'un rendu (caché) en VBAP soit d'abord effectué, puis d'utiliser ce format multiphonique pour le convertir en binaural (peut-être moins précis, mais suffisant pour avoir une idée du rendu spatial) ?

Impossible, la seule façon de spatialiser plusieurs sources en 3D sur une sortie stéréo est d'effectuer une HRTF sur chacune des sources. C'est inévitablement coûteux! Je tente une nouvelle solution pour optimiser le HRTF aujourd'hui.

> D’autre part, les spans (AS+ES) ne fonctionnent pas. C’est apparent à l’écoute, bien qu’on voit le span s’activer dans le graphique, mais aucune différence n’apparait non plus sur un fichier enregistré.

Il n'y aura pas de span avec le HRTF. En gros, le span rajoute environ 16 points de spatialisation par source. En VBAP, ce n'est que du calcul d'amplitude, ce n'est donc pas un problème. En HRTF, c'est 16 filtrages HRTF de plus par source... Impensable! Le mode HRTF devrait cacher le span dans les vues 2D et 3D.

**Comment by led78** [comment]
Le problème m'apparait réglé avec la nouvelle version. Merci!
