### ISSUE TITLE
Enregistrement en mode HRTF

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#81]
Lorsqu'on est en mode HRTF, seules les sorties 1 et 2 du speaker setup sont utilisées. En fait, dans ce mode, le speaker setup devrait être considéré comme inexistant puisque l'écoute se fait au casque. Or, l'enregistrement se fait tout de même pour chaque sortie HP du speaker setup en question, bien que seules les sorties 1 et 2 contiennent de l'audio. Cela fait que, pour un speaker setup de 16 sorties par exemple, on enregistre 14 pistes pour rien et que l'on efface par la suite.
Devrait-on tout simplement se faire un speaker setup à 2 HP, juste pour l'enregistrement du mode HRTF ou pourrait-on faire comme le Zirkonium, c'est-à-dire permettre l'enregistrement simultané des sorties HP du speaker setup et d'une version HRTF dont les sorties seraient totalement indépendantes du setup en question - donc permanente, sous le capot du serveur?
Pour l'info, le Serveur en mode HRTF utilise autour de 77% de CPU durant l'enregistrement (les 16 pistes de sortie). J'imagine qu'en limitant le nombre de canaux enregistrés à 2, ça pourrait diminuer.

**Comment by belangeo** [comment]
Oui, en mode HRTF, l'enregistrement devrait contenir seulement 2 canaux!
