### ISSUE TITLE
Problème de durées inégales avec l'enregistreur

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#82]
Les pistes obtenues à la suite d'un enregistrement réalisé avec la fonction Record sont toutes de durées inégales.
J'ai effectué 4 enregistrements hier pour mon concert de Bruxelles et je me rends compte que tous les fichiers obtenus (26) sont tous de durée inégale. Et pas rien qu'un peu! Sur une durée totale de 14:47 j'ai une variation de presque 5 secondes entre la piste la plus courte et la plus longue. Sérieux bogue.

La plus courte 1:00:42:48
![01004248](https://user-images.githubusercontent.com/8959779/32406003-9e25b3ec-c146-11e7-905d-f5c5fc39427c.jpg)

La plus longue 1:00:47:28
![01004728](https://user-images.githubusercontent.com/8959779/32406019-c489794c-c146-11e7-9749-4207c1267405.jpg)

**Comment by Xon77** [comment]
Je viens de réaliser un enregistrement de 16' spatialisant 29 sources à partir du Speaker Setup par défaut de l'hexa et je n'observe aucune différence de durée entre les 16 pistes enregistrées. Cela est peut-être du à un speaker setup particulier ? Je vais tester avec d'autres speaker setups et d'autres configurations.

**Comment by Normandeau** [comment]
Avec Reaper j'imagine? Ça serait bien de confirmer avec Logic aussi.

**Comment by led78** [comment]
Je vais confirmer avec Logic, mais j'ai déjà vu ça : Robert, est-ce que ces pistes [coupées] plus courtes contiennent normalement de l'audio au-delà de ce qui a été enregistré? Il se pourrait que l'enregistrement ou le séquenceur (DP) coupe le tout contenu dont l'amplitude demeure à 0 afin de limiter la taille des fichiers. Autrement dit, s'il n'y a aucune perte de contenu, est-ce vraiment un problème et si oui, pourquoi?

**Comment by led78** [comment]
Tu enregistre directement avec DP c'est ça?

**Comment by led78** [comment]
Confirmé : il s'agit probablement d'un comportement de DP puisque les fichiers enregistrés avec le Serveur apparaissent tous de durée égale dans Logic.

Ici un enregistrement fait à partir du setup de 32 HP + 2 subs du dôme de l'udem (B-187).
![duree_logic](https://user-images.githubusercontent.com/13606544/32690741-6d8300e0-c6c9-11e7-9020-0becce7444a6.jpeg)

**Comment by led78** [comment]
Robert, pourrais-tu nous partager le fichier .xml du speaker setup que tu as utilisé pour qu'on le test? Aussi, as-tu essayé de simplement ouvrir ces même fichiers audio dans Reaper et Logic pour voir si tu observait la même chose? Ces fichiers audio affichent-ils la même taille de le finder?

**Comment by led78** [comment]
Peut-on considérer ce problème comme étant du à un paramètre de DP et fermer l'issue?

**Comment by Normandeau** [comment]
Je viens de refaire cet enregistrement et cela fonctionne maintenant. Je vais fermer cette issue pour le moment.
 À suivre.
