### ISSUE TITLE
Volume et filtre dans le Speaker Setup?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#83]
En travaillant en Europe en dehors de notre contexte actuel, je me rends compte qu'une des choses qu'il faut faire de manière assez précise avant un concert, c'est de calibrer le système de diffusion. Je n'ai pas trop pensé à cet aspect-là à ce jour, car à la fac on effectue ces réglages avec TotalMix des RME. Mais sans cela, sur d'autres interfaces, on peut se retrouver dans des situations où on n'a aucune contrôle des niveaux de sorties des hp. Donc question:

Est-il possible et facilement réalisable d'ajouter dans la fenêtre du Speaker Setup deux paramètres supplémentaires:
- volume de sortie pour calibrer le système (en fait un atténuateur qui pourrait être calibré de 0 à -20dB par exemple);
- filtre passe-haut pour enlever le grave des hp du dôme (courbe de 24 dB/octave, fréquence ajustable de 60 à 120 Hz)?

Qu'en dites-vous? Est-ce trop exigeant en terme de CPU? Je ne le crois pas puisque ce serait des réglages passifs, non?

**Comment by led78** [comment]
Pour un filtre passe-haut qui ne colore pas le signal, il faudrait utiliser un filtre non récursif (FIR). C'est plus demandant qu'un filtre récursif pour une courbe d'atténuation abrupte en terme de CPU, mais je ne crois pas que ce soit tant que ça à 24 dB/Octave. Reste que si l'on parle d'un système avec un très grand nombre de sorties HP, ça pourrait peut-être avoir un effet. Je ne sais pas. Olivier sait sûrement ça.

**Comment by belangeo** [comment]
Pour le volume, il n'y a pas de problème. Pour ce qui est du filtre passe-haut, pour générer un filtre non-récursif avec une atténuation de 24dB/octave, on parle d'une réponse impulsionnelle qui va faire dans la centaine de coefficients, ça va être beaucoup trop coûteux. Il y a un filtre IIR conçu expressément pour faire des crossovers, c'est le Linkwitz–Riley d'ordre 4 (24 dB/octave). C'est équivalent à deux biquad donc ça ne devrait pas faire une grosse différence en terme de CPU.

**Comment by Normandeau** [comment]
Alors commençons  au moins pour le réglage du Volume.
