### ISSUE TITLE
Problèmes avec les Aux dans DP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#84]
Lorsqu'on organise une session DP avec des Aux, les assignations de celles-ci vers les sorties affectés par les Bundles ne fonctionnent pas bien. Les Aux finissent par apparaître à la fin des pistes audio. Ainsi, si tu mets une piste Aux 17-18 au milieu d'un premier groupe de piste audio de 1 à 16 et suivi d'un autre groupe de pistes audio 19-24, les signaux des Aux sont envoyés au Server par 19-24 et tout le groupe 19-24 est décalé de 2 pistes vers la gauche, autrement dit réaffecté à 17-22. Alors que toutes les pistes sont affectées à 19-24. Annoying!?! Chocking, you say...
La solution c'est d'utiliser des pistes audio avec des input au lieu de pistes Aux.
Je sens que je commence à être sérieusement mûr pour une passage à Reaper... Bogue de DP, à mettre dans le manuel.

**Comment by led78** [comment]
Pour ma part, je n'ai pas pas de problème avec l'emploi de pistes Aux dans DP. Mise à part la fois au j'ai voulu remplacer 4 pistes Aux Mono, assignées chacune à une sortie Jack, pour une piste Aux Quad. À ce moment là - j'en ai déjà parlé - il y avait un décalage de branchement dans Jack où la piste Quad se retrouvait branché en premier et les autres pistes Aux par la suite. Est-ce que ça pourrait être le même genre de problème? Pour toutes les autres pistes Aux, elles ont tous été assignées au début du projet et dans l'ordre. Dans ce projet, chaque piste Aux est contient un SpatGris en insertion et est dirigée vers une sortie Jack.
