### ISSUE TITLE
Faire une simple sortie stéréo/ by-pass du HRTF

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#86]
C'est pratique si l'on veut faire une écoute sommaire en stéréo, sans filtrage HRTF, ou pour se faire une version stéréo reprenant la spatialisation d'azimuth en Mid-Side - 0° et 180° au centre [mid] et 90° et 270° respectivement sur les côtés droit et gauche [sides]).
Ça permettrait également de mixer les basses sans les pertes occasionnées par le filtrage HRTF ou encore de travailler temporairement la composition sans tenir compte de la spatialisation, afin de sauver du CPU (par rapport au mode HRTF).

**Comment by Normandeau** [comment]
V013
Gé-ni-al!
