### ISSUE TITLE
Passage du mode HRTF High à Low

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#87]
Le passage du mode HRTF High vers le mode HRTF Low fais parfois planter le serveur. On entend alors un ou quelques cliques dans les hautparleurs/écouteurs, puis le serveur plante. Je n'ai pas encore observé ce problème dans l'autre sens, c'est-à-dire en passant du mode HRTF Low à High. Le problème semble survenir de manière imprévisible, mais assez fréquemment.

**Comment by Normandeau** [comment]
Je confirme.

**Comment by belangeo** [comment]
Pouvez-vous m'envoyer le rapport de crash quand ça arrive (ou le log dans Console.app)? Je n'arrive pas à reproduire le crash sous linux. Merci!

**Comment by Xon77** [comment]
Je te l'ai envoyé sur ton courriel.

**Comment by Normandeau** [comment]
V013
Cela a l'air réglé. Testé avec 30 inputs, 32 hp. Passage entre VBAP, HRTF LOW. HRTF HIGH et Stereo, dans tous les sens.
Aucun plantage. À valider?

**Comment by Xon77** [comment]
Je n'ai observé, pour l'instant, aucun plantage avec la v. 013, en passant entre les différents modes HRTF / VAP et stéréo, avec différents types de configurations d'entrées et de sorties.
