### ISSUE TITLE
Différence de % Jack Run et de la limite de nombre d'entrée entre les modes HRTF Low et High [version 0.1.2]

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#88]
À titre informatif, j'observe une amélioration d'environ 18% de l'indicateur Jack Run lorsqu'on passe du mode HRTF High à HRTF Low.

De plus, 

En mode HRTF Low, la limite du nombre d'inputs semble être de 50 et ce malgré le fait que l'indicateur Jack Run se situe en moyenne autour de 56%. Au delà de 50 entrées, il arrive d'entendre des sauts de volume très sporadiques et de plus en plus fréquent à mesure qu'on augmente le nombre d'entrée. J'ose croire que ces sauts de volume sont provoqués par de brèves crêtes observées du % de Jack Run.

En mode HRTF High, la limite du nombre d'inputs semble être de 30 (peut-être 31), avec un % de Jack Run se situant également en moyenne autour de 56%. Au delà de 30 entrées, on entend des sauts de volume sporadiquement et de plus en plus fréquent à mesure qu'on augmente le nombre d'entrée.

Ces tests ont été effectué avec des pistes contenant tous de l'audio et des automations de mouvement assez rapides.

**Comment by Normandeau** [comment]
Le mode HDTF actuel avec ses limitations d'entrées, est pratiquement inutile pour moi. Je n'ai pas un seul projet qui contient moins de 48 canaux audio, or ça glitche pratiquement à partir de 30 comme le souligne David. Il faudra ajouter cela dans le manuel, car c'est tout de même une limite importante. Cette fonction peut-être utile pour valider des stratégies piste par piste, mais pas pour la sommes de celles-ci.
À moins que cela puisse s'améliorer substantiellement.

**Comment by belangeo** [comment]
L'HRTF est lourd par définition. HRTF LOW est pas mal ce qu'il y a de plus optimisé. Pour faire plus léger, il faut éliminer l'interpolation entre deux filtrages successifs mais là les mouvements rapides vont être bruyant!

**Comment by led78** [comment]
Est-ce qu'on pourrait lier le pot d'interpolation du Serveur à ce paramètre d'interpolation entre les filtres successifs lorsque l'un des modes HRTF est sélectionné?

**Comment by led78** [comment]
Tout de même, ça reste pratique pour démarrer un projet/la spatialisation à la maison.

**Comment by belangeo** [comment]
> Est-ce qu'on pourrait lier le pot d'interpolation du Serveur à ce paramètre d'interpolation entre les filtres successifs lorsque l'un des modes HRTF est sélectionné?

Non, ce n'est pas une interpolation du type filtre passe-bas. C'est une interpolation linéaire, sur la longueur d'une réponse impulsionnelle (x 2 en fait), entre la précédente et la courante.
