### ISSUE TITLE
Test 128X128: au-delà de la limite

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#89]
Autre test V112, DP95, MacOS10.12.6, Buffer 1024.
Je commence une série de tests d'endurance de ServerGRIS.
Test maximum: 128 entrées, 128 hp: 124 dans le dôme répartis sur 5 niveaux (64,32,18,8,4) et 4 sorties directes (si le CUBEFest était un dôme, ça ressemblerait à cela). Les opérations _Compute_ ou _Load Speaker Setup_ prennent entre 3 et 5 minutes (avec la roue de la mort qui tourne...).
Jack est à 70% au «repos».

**Reaper et DP**
(on ne peut pas faire de tests avec de multiples octos dans Logic)
• Session de 40 pistes ( 5 octos sans automation) Jack 85%
• Session de 8 pistes ( 1 octo sans automation) Span au max Jack 98%!
• Session de 16 pistes (2 octoss ans automation) Span au max Jack s'affiche en rouge. Je ne sais pas ce que ça donne sur le plan audio, car je n'ai pas 128 hp! Le signal audio semble s'interrompre sur certaines sorties.
![capture d ecran 2017-12-02 a 12 18 51](https://user-images.githubusercontent.com/8959779/33518006-df037cb6-d75b-11e7-9fe3-2ee50a3f1d8c.jpg)

**DP**
• Session de 64 pistes (32 stéréos sans automation) Jack 7%: c'est intéressant, quand Jack dépasse le 100%, il recommence en bas, donc au lieu d'afficher 107%, il affiche 7%. Dans Moniteur d'activité, cela signifie plus de 210%. Est-ce la limite théorique de Jack (Jack flash en rouge tout le temps)? Ou de mon ordi? À valider sur un MacPro.
• Session de 64 pistes (32 stéréos sans automation) mais avec un dôme de 32 hp seulement Jack 40% au repos, monte à 60% lorsque toutes les pistes jouent.

**Conclusion**
La limite de 128 hp est donc théorique (et je n'ai pas essayé encore avec les 128 entrées). Dans les faits, avec le MacBook Pro le plus récent, c'est inutilisable. Ça vaut la peine d'y réfléchir car cela signifie que l'on ne pourrait pas utiliser les 128 hp du CUBEFest (124 + 4 subs).

**Comment by led78** [comment]
Le 2 déc. 2017 à 13:13, Robert Normandeau <notifications@github.com> a écrit :

_c'est intéressant, quand Jack dépasse le 100%, il recommence en bas, donc au lieu d'afficher 107%, il affiche 7%._ 

J’ai remarqué la même chose en faisant les tests des modes HRTF hier. Par exemple, avec 80 entrées, le mode HRTF Low présente un indice Jack autour de 82%, tandis que le mode High affiche environ 0.07% avec un flash rouge très fréquent.

Je confirme que c’est la limite de Jack qui compte et non celle de l’ordinateur. Comme cela a été confirmé lors du dernier test de performance (#85) Mon Mac Pro a encore bien du CPU alors que Jack sature. Ce qui résulte néanmoins en des cliques audio et des sauts de volume rendant l’outil inutilisable au-delà de cette limite.

Mais, je pourrais toujours faire le même test avec les 128 sorties sur mon ordi, juste pour voir.
Robert, pourrais-tu m'envoyer le speaker setup en question?

**Comment by Normandeau** [comment]
Autre test V012, DP95, MacOS10.12.6, Buffer 1024.
Dome de 64 hp. 128 inputs. SpatGRIS est limité à 92 canaux OSC (rapport dans les Issues de celui-ci).
• Session de 46 pistes stéréo, avec automation. Jack au repos: 44%. En mode jeu, JackRun 65%.
Moniteur d'activité: DP 450-500%, ServerGRIS 175%. Global 85-93%. C'est intense mais ça roule.

Dome de 96 hp. 128 inputs. SpatGRIS est limité à 92 canaux OSC (rapport dans les Issues de celui-ci).
• Session de 46 pistes stéréo, avec automation. Jack au repos: 60%. En mode jeu, JackRun 99%.
Moniteur d'activité: DP 450-500%, ServerGRIS 205%. Global 85-93%. DP affiche un message d'activité trop intense et Jack overload.

**Conclusion**
La valeur maximale de hp que l'on peut utiliser en ce moment se situe quelque part entre 64 et 96. Il faudra juste être honnête avec cela au moment de la publication. On est très loin de 128.

**Comment by led78** [comment]
On pourrait spécifier cela dans la section System Requirements du manuel. En ce moment, on ne mentionne pas de système minimal ni de système recommandé - les capacités de l'ordinateur - pour maximiser la performance. À partir de nos tests, on pourrait monter une grille résumant le nombre ou le ratio d'entrées et de sorties maximales possibles - canaux spatialisées et/ou directs - en fonction de Jack et de l'OSC en mode VBAP, même chose pour les deux modes HRTF, etc. On verra si les capacités physiques de l'ordinateur et le type de DAW utilisé sont pertinents à considérer. Cela donnerait au moins un aperçu du nombre d'entrée et de sortie que les utilisateurs seraient en droit de s'attendre selon le mode utilisé.

**Comment by led78** [comment]
En essayant d'ouvrir le speaker setup de 128 sorties, le Serveur finit toujours par ne plus répondre et je dois le forcer à quitter. Je suis donc incapable de l'ouvrir. Je vais essayer de le refaire à la main, avec les coordonnées du fichier .xml

**Comment by Normandeau** [comment]
Il faut être très patient! Ça prend entre 3 et 5 minutes à ouvrir, et si tu regardes dans Moniteur d'activité, le Server a l'air planté, ce qui n'est pas le cas. Même chose quand tu le configure et que le Compute. C'est très long à faire avant que la fenêtre de sauvegarde s'ouvre. Et toutes les opérations du Server deviennent extrêmement lentes.

**Comment by led78** [comment]
Merci, ça fonctionne maintenant!

**Comment by led78** [comment]
Reprise du test de Robert (v_0.1.2) sur Mac Pro (3GHz 8 cœurs et 32 Go de mémoire), Logic Pro X, MacOS 10.12.6, Buffer 1024.
128 entrées et 128 HP (même setup que Robert): Jack à ~77% au «repos» et sans Logic d'ouvert.
Jack monte à entre 85 et 95% lorsque j'ouvre une session Logic avec 80 pistes de sorties, que Logic soit connecté ou non au Serveur.

80 entrées avec automations, 128 HP:
Jack à ~55% au «repos»
Je démarre la lecture dans Logic... Jack est +1,4% au dessus de sa limite (flashs rouges). Visuellement, Logic et le Server roulent très bien cependant. Lorsque les sources s'adonnent à passer devant les sorties HP 1 et 2, j'entend bien que l'audio clique considérablement. Ce n'est donc pas utilisable à ce niveau.
ServerGRIS est à 160-163%
Logic Pro X est à 130-140%
J'ai encore plus de 77% de CPU total de disponible sur mon Mac Pro.

64 entrées avec automations, 128 HP:
Jack à ~45% au «repos»
Je démarre la séquence... Jack est à 80-90% avec quelques pointes au dessus de 100%. À ce moment là, les sources s'adonnent à passer devant les sorties HP 1-2 et j'entend des cliques audio.
ServerGRIS est à 145-165%
Logic Pro X est toujours à 130-140%

À ce moment-ci, je réalise les tests avec une interpolation maximale (1.000). Or, si je diminue l'interpolation du ServerGRIS au minimum (0.000) cela affecte considérablement le % de Jack!
Il faudrait donc préciser cette valeur dans les comptes rendus de nos tests de performance.
As-tu noter la valeur d'interpolation lors de tes tests Robert? Car sinon, on risque d'obtenir des indicateurs différents à chaque fois.

À titre d'exemple, en reprenant le dernier test avec une interpolation minimale:
64 entrées avec automations, 128 HP; interpolation à 0:
Jack à ~45% au «repos»
Je démarre la séquence... Jack est à 47%! Lorsque les sources s'adonnent à passer devant les sorties HP 1-2, je n'entend aucun clique audio.
ServerGRIS est à 106%
Logic Pro X est toujours à 130-140%

Si je remonte à 80 entrées; interpolation à 0:
Jack toujours à ~56% au «repos»
Je démarre... Jack est à ~58% et pas de cliques audio!
ServerGRIS est à 118%
Logic Pro X est toujours à 130-140%

Cela démontre qu'il est définitivement possible d'utiliser le ServerGRIS avec 128 HP et ce avec plus de 80 entrées! Je vais donc poursuivre les tests pour aller chercher un maximum d'entrée lorsque l'interpolation est à 0.

Pour les tests futurs, il faudrait donc établir un standard de mesure des performances en tenant compte du niveau d'interpolation. Je proposerais de faire des batteries de tests comprenant trois limites de performance :
1.  selon une interpolation à 0
2. selon une interpolation à 0,5
3. selon une interpolation à 1

Qu'en dites-vous?

**Comment by belangeo** [comment]
Trois choses à noter ici:

1 - Affichage du CPU de jack passé 100%. C'est jack lui-même qui retourne une valeur qui wrap après 100%. On ne peut rien y faire. Il faudrait mentionner que lorsque jack s'allume en rouge, la valeur qui est lue est un pourcentage au-dessus de 100%.

2 - Il y a la charge de calcul au moment de la performance (le plus important). Sur ma machine, je peux faire 64 entrées / 128 sorties avec azimuth, élévation et les spans dans le tapis pour chaque entrée. Plus que ça, je suis dans le rouge. À ce niveau je peux probablement optimiser encore un peu.

3 - La charge de calcul dans la préparation du setup. À 128 sorties, tout est long. Le bouton "Compute", sauvegarder un speaker setup (Compute est automatiquement appelé) et même changer le nombre d'entrées. Ici aussi, j'espère pouvoir accélérer ces différentes étapes parce que c'est vraiment trop long!

**Comment by led78** [comment]
Je me demande si le fait d'avoir les Spans au maximum consomme autant que l'interpolation maximale du Serveur au niveau du % de Jack?

**Comment by led78** [comment]
Je soupçonne qu'une source en mouvement (avec automation) et une interpolation maximum consomme plus que des sources fixent avec un span maximal (sans automation de mouvement), mais je ne sais pas vraiment.

**Comment by belangeo** [comment]
Un VBAP de base utilise au maximum 3 HPs par source. L'interpolation fait en sorte que le signal reste un peu plus longtemps dans un HP par rapport au mouvement de la source. Il y a donc possibilité de plus de 3 HPs/source dans ce cas. Plus l'interpolation est grande, plus la quantité de HPs présents par source est grande, ce qui augmente d'autant la charge en CPU.

**Comment by led78** [comment]
Donc, si je comprend bien, ça pourrait être équivalent au span en terme de charge CPU?

**Comment by belangeo** [comment]
Dans la mesure où les deux augmentent la quantité de HPs par source, oui.

**Comment by Normandeau** [comment]
Remarque très juste en ce qui concerne l'interpolation. La première chose qu'on peut faire, c'est la diminuer la valeur par défaut. Actuellement celle-ci est de 0.330. On pourrait la laisser à 0.1?

Test, Session DP 64 pistes stéréo automatisées (128 canaux), Aucun Span, Interpolation 0.000.
Ce qui varie, c'est le SpeakerSetup:

Dome 16
Repos: JackRun 23%. Play: 32%

Dome 32
Repos: JackRun 28%, Play 44%

Dome 64
Repos: JackRun 43%, Play 64%

Dome 80
Repos: JackRun 51%, Play 88%
Interpolation augmentée de 0.100 à 0.800 Play augmente à 94%, mais joue correctement (du moins sur les 10 hp de mon studio)

Dome 96
Repos: JackRun 60% (plus que DP), Play Plus de 100% ponctuellement, donc limite atteinte.

**Conclusion**
On voit que le nombre de hp est beaucoup plus déterminant que la valeur d'interpolation. À 80 hp, même avec une interpolation de 0.800, le système roule. Mais aussitôt qu'on met 96 hp, on atteint la limite.

**Comment by Normandeau** [comment]
En discutant avec Christophe et en observant des gosses sessions rouler, on peut constater, bien que cela soit étrange, que les performances dépendent un peu de l'humeur... du Mac!
En ce moment, je roule une session DP 46 pistes stéréo, full automation, sur 15' et sur un dôme de 128 hp, sur un disque externe Thunderbolt 2, ultrarapide.
Jack chaufffe pas mal, autour de 90-98%, mais sans interruption.
Pas de span évidemment, Interpolation à 0.070.

Pas de quoi rougir!

**Comment by led78** [comment]
En effet, cela dépend du ratio pistes en entrée/pistes en sortie. On peut facilement avoir un dôme de 128HP si on a pas autant de piste en entrée. Dans le test précédent, tu arrives à avoir une limite de 96hp, mais avec 128 pistes en entrée. À l'inverse, il est donc possible d'avoir 46 pistes stéréo - donc 92 - en entrée et 128 sortie hp. Ça fait du sens, non?

**Comment by led78** [comment]
On pourrait à la limite faire des tests pour valider si la limite de piste totale (entrées et sorties) combinée ne serait pas 224 (128+96). Si c'est le cas, on pourrait l'indiquer dans le manuel à titre informatif.

**Comment by Xon77** [comment]
Test Performance Reaper 5.52 (CPU à 100/180%) :
- 8 pistes octophoniques (64 sources) en lecture VBAP
- Lecture de 128 courbes d’automation avec les positions X & Y pour chaque source 
- Interpolation du serveur par défaut de 0.33
- Prise en compte de 2 niveaux de spans

* Speaker Setup de 64 :
- lecture avec des spans au quart de leur maximum : Jack (60%) / Server (140/150%)
- lecture avec des spans au maximum : Jack (99% et +) / Server (170/190%). De brèves coupures sonores dans certains canaux peuvent apparaitre lorsque Jack dépasse les 100 % et flashe en rouge.

* Speaker Setup de 80 :
- lecture avec des spans au quart de leur maximum : Jack (70/90% avec des pics à 95%) / Server (150/160%).  Je n’ai pas observé de flash rouge dans Jack ou de coupure sonore.
- lecture avec des spans au maximum : Jack (105% et +) / Server (180/190%). De brèves coupures sonores dans certains canaux apparaissent constamment car Jack dépasse toujours les 100 % et flashe en rouge.

* Speaker Setup de 96 :
- lecture avec des spans au quart de leur maximum : Jack (80/99% et +) / Server (150/160%).
De brèves coupures sonores dans certains canaux peuvent apparaitre lorsque Jack dépasse les 100 % et flashe sen rouge.

Conclusion : 
On peut observer qu’une composition de 64 sources / 64 sorties peut être facilement réalisée avec des spans « raisonnables » sur les derniers Mac book Pro 2.9 Ghz sur Reaper. Evidemment le nombre de sorties HP peut être augmenté si les spans sont à 0. Ainsi, si les spans sont à 0, 64 sources peuvent être spatialisés sur 128 HP avec aucune coupure apparente. (En lecture : Jack à 55% et + / Server à 140/150%). L’impact des spans est donc considérable. La charge CPU d’un speaker setup de 64 HP avec avec des spans au quart de leur maximum est pratiquement la même que celle d’une config de 128 HP avec un span de 0. J’ai aussi l’impression que la limite vient essentiellement de Jack, qui coupe le son sur certains canaux lorsqu’il est au delà de 100%, car il semble travailler seulement sur un seul coeur… ?

Au fait, le nombre de pistes dans la Master Track est de 64 au max. dans Reaper pour moi. 
Quelqu’un sait comment simplement augmenter cette limite ?

**Comment by led78** [comment]
> J’ai aussi l’impression que la limite vient essentiellement de Jack, qui coupe le son sur certains canaux lorsqu’il est au delà de 100%, car il semble travailler seulement sur un seul coeur… ?

C'est aussi ce que je me disais à propos de Jack (travaillant seulement sur un seul cœur). Or, quand je regarde dans le moniteur d'activité, aucun cœur n'est à fond. Sinon, il y aurait peut-être moyen de répartir la charge sur plusieurs cœurs (multithreading) par groupe de 32 canaux par exemple. Je ne sais pas si ce que je dis fait du sens. Je sais que Logic permet de gérer le multithreading pour optimiser la répartition de la charge CPU sur plusieurs cœurs.

Pour ce qui est de Reaper, il me semble que la limite absolue du logiciel est de 64 IN, 64 OUT, mais je n'ai pas vérifier pour être sur à 100%.

**Comment by belangeo** [comment]
Jack travaille sur un seul coeur et à moins de le réécrire, ça sera toujours ainsi! Aussi, ne regardez jamais le "Moniteur d'activité", cette info ne fait pas de sens puisque l'application donne le ratio entre l'activité d'un processus et la puissance totale (tous les coeurs) de la machine. Si vous utilisez "top" dans un terminal, vous allez avoir une représentation plus juste de la charge en CPU des différents processus...

**Comment by belangeo** [comment]
En passant, j'ai optimisé la boucle de calcul du client jack et l'algorithme du VBAP. 64 ins/128 outs (tous les spans qui fonctionnent) est passé de ~105% à un peu moins de 90% sur ma machine. Une autre optimisation que j'ai mis en place est que si la valeur d'interpolation est de 0, le filtre d'interpolation (passe-bas récursif) est remplacé par une interpolation linéaire (un simple incrément). S'il y a beaucoup d'entrées et de sorties, ça fait une bonne différence.
