### ISSUE TITLE
Affichage et modifications des triplets dans Edit Speakers

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#9]
Qu'est supposé faire "Clear Triplets" dans "Edit Speakers" ?
juste par curiosité, même si la fonction n'est pas encore implémentée...

**Comment by belangeo** [comment]
C'est pour le cas ou quelqu'un veut spécifier ses propres triplets (la fonction existe à l'interne mais n'est pas encore connectée). On veut non seulement pouvoir ajouter mais aussi enlever des triplets du setup courant.

**Comment by Normandeau** [comment]
Est-ce qu'il ne serait pas utile, d'une part pour la compréhension du fonctionnement du VBAP pour les utilisateurs, d'afficher les triplets? Avec un bouton genre Show/Hide triplets? 
Et d'autre part, en ce qui concerne mon expérience avec le Zirkonium, cet affichage m'a permis de régler de nombreux problèmes de cohérence dans la fabrication d'un Speaker Setup. Les triplets m'ont permis par exemple d'identifier une relation qui s'est établie entre deux cercles de hp non consécutifs, ce qui avait pour conséquence que lorsque le son montant en hauteur, il y avait un silence au niveau du cercle qui avait été ignoré. Sans la représentation graphique, je chercherais encore le problème! Cela m'a aussi permis d'identifier un problème de tous les Speakers Setup du CUBE dans lesquels des hp fonctionnaient en permanence, sans même qu'aucun son ne les touche.

**Comment by Normandeau** [comment]
Il y a un petit bogue dans l'affichage des Triplets. Si un Speaker Setup commence sa numérotation à une valeur supérieure à 1, les triplets ne s'affichent pas.
Voyez ici avec le setup du B187. D'abord le modèle avec les connexions de la MOTU que nous avions avant (de 1 à 32). Les triplets s'affichent:

![capture d ecran 2017-10-24 a 16 23 36](https://user-images.githubusercontent.com/8959779/31966239-07b8387e-b8d8-11e7-9f4f-a4b5bdfa8a69.jpg)

Et la même disposition, mais les connexions de la UFX+ (les sorties MADI commencent à 31 et la sortie la plus basse est 5 pour le premier sub). Les triplets ne s'affichent pas:

![capture d ecran 2017-10-24 a 16 22 49](https://user-images.githubusercontent.com/8959779/31966280-2b220204-b8d8-11e7-8ae8-9f13be7ba313.jpg)

Vérification faite avec d'autres setups de hp identiques, mais avec des numérotations différentes.

**Comment by Normandeau** [comment]
Il semble y avoir d'autres bogues avec les Triplets. Ici par exemple, non seulement je ne suis pas capable de fermer leur affichage, mais en plus celui-ci ne correspond pas au positionnement des hp:

![capture d ecran 2017-10-29 a 08 59 48](https://user-images.githubusercontent.com/8959779/32143922-93d71480-bc87-11e7-83f4-c845987a0e4c.jpg)


Si je change le Speaker Setup, les triplets sot corrigés, mais je ne peux toujours pas les enlever (l'option reste toujours cochée):

![capture d ecran 2017-10-29 a 09 00 59](https://user-images.githubusercontent.com/8959779/32143936-baa0b058-bc87-11e7-85db-9538a66ca922.jpg)

Après plusieurs séries de tests d'enchaînements de Speaker Setup, j'en arrive à la conclusion... qu'il n'y en pas! Le comportemnt est erratique, tout simplement. Parfois les triplets s'affichent, parfois non. Parfois ils restent bloqués, parfois non. Parfois ils sont affichés correctement, parfois non. La seule chose qui semble constante c'est que si le numéro du premier hp est 1, ils s'affichent. Si ce numéro est au-dessus de 1, ils ne s'affichent pas.

**Comment by belangeo** [comment]
Même problème... L'affichage des triplets ne fonctionnait pas s'il y avait des trous dans l'ordre des numéros de sortie. C'est réglé.

**Comment by Normandeau** [comment]
Version 010
Les triplets incorporent les hp supplémentaires ajoutés après les sorties directes, comme on le voit ici avec les hp 5-6.

Configuration originale, où les sorties directes sont à la fin de la liste des hp:

![triplets hp avant les sorties directes](https://user-images.githubusercontent.com/8959779/32169139-9b8d6346-bd45-11e7-9e13-62b937a8ab50.jpg)

Même configuration avec ajout de 2 hp supplémentaires (27-28) à la fin de la liste. Les sorties directes 5-6 sont prises en charge par les Triplets:

![capture d ecran 2017-10-30 a 07 36 22](https://user-images.githubusercontent.com/8959779/32169074-5059563c-bd45-11e7-901a-c2b2eb21624c.jpg)

Si j'enlève les deux hp supplémentaires que je Compute, le problème se règle.
Cependant cela a des conséquences importantes sur le plan audio, voir l'issue  #67

**Comment by Normandeau** [comment]
V012
Réglé
