### ISSUE TITLE
Révision du manuel : commentaires et suggestions

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/ServerGRIS#90]
Version 1.0

Je ne vois aucune mention de l'enregistreur intégré dans le ServeurGRIS. En contrepartie, cette section me semble dépassée:
_1.3.4. Recording of the multichannel files
We strongly recommend writing the multiphonic files on audio tracks in real time by sending the signal to buses rather than using the “Freeze” or “Bounce” functions in the sequencers._

À ajouter: spécifier la différence entre le mode HRTF High et Low.

**Comment by Normandeau** [comment]
Bonne remarque pour l'enregistreur, je l'ajoute.
1.3.4. Cette section est consacrée au mode audio du SpatGRIS. Cette recommandation est donc toujours valide.

**Comment by Xon77** [comment]
La partie 1.4.4 "Warning about Jack" est répété à la fin en 6.4... Peut-être voulu ?

**Comment by Normandeau** [comment]
Merci pour les commentaires.
Edit Speakers a été remaniée déjà. Et la répétition est voulue.
En fait, il y une version corrigée du manuel qui circule déjà. J,attends une version plus ou moins finale du Server avant de la faire circuler car certains visuels seront à mettre à jour.

**Comment by Normandeau** [comment]
La version V4 circule. On se revoit en janvier.

**Comment by Normandeau** [comment]
Version V5 depuis le e2 janvier 2018.

**Comment by led78** [comment]
Je suis en train de terminer la relecture complète et commentée du manuel V5. Mais, j'aimerais tout de suite aviser que, bien qu'on en fait indirectement mention dans la section 4.11.6. du manuel, il n'y a aucune section détaillant - images à l'appuie - comment assigner chaque SpatGRIS, via l'onglet Interfaces, à son ou ses canaux audio correspondant dans le Server. C'est quand même une information cruciale qui, je crois, doit être explicitement démontrée dans le manuel dans une section dédiée (2.6, 2.7, 2.8 ou 2.9?).

**Comment by led78** [comment]
[ServerGRIS1.0_Manual V5_revision_01.pdf](https://github.com/GRIS-UdeM/ServerGRIS/files/1640658/ServerGRIS1.0_Manual.V5_revision_01.pdf)
Voici ma révision complète de la version 5 du manuel. Il faut cliquer sur l'option Commentaire pour visualiser les changements **suggérés** - et je souligne le mot suggérés.

**Comment by Normandeau** [comment]
Le manuel a été revu de fond en comble et la grande majorité des suggestions y ont été apportées. Il a également été l'objet d'une correction d'épreuve. On est prêt.
