### ISSUE TITLE
Pas de triplets en octophonie

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#91]
Pourquoi? Il me semble que ce message est nouveau.

![octophony](https://user-images.githubusercontent.com/8959779/33527381-b57afe6a-d81d-11e7-9798-90b389f82384.jpg)

![no triplets in octophony](https://user-images.githubusercontent.com/8959779/33527384-bb34bb02-d81d-11e7-9f18-7d62b9580893.jpg)

**Comment by belangeo** [comment]
Parce qu'il n'y a pas de triplets en octophonie (seulement en 3D). C'est plus ou moins de la pan standard. La fonction pour dessiner les triplets devrait simplement être grisée lorsqu'il n'y a pas 3 dimensions.

**Comment by Normandeau** [comment]
Ok bonne idée de les mettre en grisé. Et d'enlever le message d'erreur...

**Comment by Normandeau** [comment]
V013
Olivier: «Les issues #91 et #94 me turlupinent particulièrement...»
Qu'il n'y ait pas de Triplets en 2D, on peut le mettre dans le manuel.
Par contre, ce serait bien d'enlever le message d'erreur. 
Ah je comprends, celui-ci est nécessaire pour avertir l'utilisateur des problèmes de triplets en général, n'est-ce pas, comme dans l'issue no 94?
Je peux très bien ajouter cette nuance dans le manuel au sujet du message d'erreur. La notion de triplet y est expliqué en détail.

**Comment by belangeo** [comment]
Oui, l'idée est de griser la fonction dans le menu, de cacher les triplets s'ils sont déjà affichés et d'enlever le message d'erreur (puisqu'il ne sert plus).

**Comment by Normandeau** [comment]
Ok, le menu est en grisé pour l'octophonie, pas de triplets.
