### ISSUE TITLE
Orientation du dôme par défaut

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#92]
Pourrait-on changer l'orientation du dôme par défaut?
Actuellement, celui-ci s'ouvre avec le X à droite:

![dome x droite](https://user-images.githubusercontent.com/8959779/33528382-70615d50-d82d-11e7-8a9e-b4670dad5c04.jpg)

Personnellement, je suis toujours en train de le replacer comme dans la vraie vie, avec le X au fond:

![dome x fond](https://user-images.githubusercontent.com/8959779/33528391-92bbb594-d82d-11e7-9680-757466656967.jpg)

Qu'en dites-vous?

**Comment by led78** [comment]
Oui, ce changement serait bienvenue et ne devrait pas être trop difficile. Je l'avais souligné il y a quelques temps (#60 ) et cela semble avoir été oublié.

**Comment by Normandeau** [comment]
V013
Fait.
