### ISSUE TITLE
Afficher un message d'avertissement si le VBAP n'est pas capable de trianguler correctement la configuration de HPs demandée.

### ISSUE THREAD

**Issue by belangeo** [GRIS-UdeM/ServerGRIS#94]
Tout est dans le titre!

**Comment by Normandeau** [comment]
V014
Pas encore implémenté.
Bon j'ai un peu exagéré, mais je voulais juste vérifier si je recevrais un message d'erreur, ce qui n'a pas été la cas. Je vais corriger le manuel. À ajouter éventuellement.

![triplets defectueux](https://user-images.githubusercontent.com/8959779/35358888-2a1f7ce2-0126-11e8-8201-7eca45eea299.jpg)

**Comment by belangeo** [comment]
En fait, c'est bien implémenté, mais seulement pour le cas où le VBAP n'arrive pas du tout à trianguler (un setup qui ne fait pas de sens). Dans ce cas-ci, il y arrive mais fait des erreurs, c'est beaucoup plus difficile à attraper. Pour un cas comme celui-ci, il serait possible de détecter lorsqu'une connexion passe par-dessus un niveau... Il y a probablement d'autres cas de figure...

**Comment by Normandeau** [comment]
Oui c'est bien ce que je pensais. J'ai mis un gros «Warning» dans le manuel à cet égard. Le passage d'un niveau à un autre qui ne lui est pas contigu est la situation la plus fréquente qu'il m'est arrivé de trouver. Erreur humaine...
