### ISSUE TITLE
Affichage incohérent en orange des pop up menus sélectionnant les direct output channels en bas des Inputs

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#95]
Il suffit de cliquer sur différents pop up menus des entrées en dessous de ms pour mettre le background en orange aléatoirement sans raison, alors qu'aucune sortie directe n'est sélectionnée. Minuscule Bug graphique...

**Comment by Normandeau** [comment]
Ça m'a pris mal de temps pour arriver à comprendre et à reproduire ce que tu décris ici. En fait, la sélection en jaune se produit effectivement de temps à autre, mais sans aucune incidence sur une des fonctions du Server, contrairement aux sorties qui correspondent aux hp. Il suffit de cliquer ailleurs pour que ça disparaisse.
Est-ce que c'était là avant?

**Comment by Xon77** [comment]
C'est juste un minuscule bug graphique, sans incidence sur les fonctions du Server.
Je ne sais pas si cela était là avant... j'ai essayé de réinstaller la version 0.1.2 par la suite pour vérifier certaines choses. Mais la version 0.1.3 apparaît constamment.
