### ISSUE TITLE
Taille de police des menus File & View (0.1.3)

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/ServerGRIS#96]
Il me semble que la taille de police de certains éléments, dont File et de View a été réduite (avec les vumètres...)
File & View dans les menus me paraissent plus petits qu'avant... ainsi que la taille de Save / Cancel / Exit, lorsque l'on souhaite quitter l'application.

De plus, le Quit n'apparaît plus dans le menu File.

**Comment by belangeo** [comment]
La taille de police ne devrait pas affecter autre chose que les vu-mètres... Je vais vérifier. Le Quit n'est pas dans le menu File mais bien dans le menu ServerGris (à la MacOS), non?

**Comment by Xon77** [comment]
Tout à fait, tu as raison.

**Comment by Normandeau** [comment]
Comparaison:

012:
![taille de polices v012](https://user-images.githubusercontent.com/8959779/34058753-433d6040-e1aa-11e7-932e-177d60f7a296.jpg)

013
On voit que File et View ont rapetissés. Bientôt ça va être aussi petit que dans DP!
![taille des polices v013](https://user-images.githubusercontent.com/8959779/34058763-4e0e43a4-e1aa-11e7-8ce3-6e2496644449.jpg)

Menu Quit dans ServerGis
