### ISSUE TITLE
Compiler le ServerGris sous VisualStudio

### ISSUE THREAD

**Issue by belangeo** [GRIS-UdeM/ServerGRIS#97]
Version Windows!

**Comment by Normandeau** [comment]
Oh oh oh! Un beau cadeau de Noël! Et ça marche? Mais qui va tester cela?

**Comment by theRedMercury** [comment]
Je peux toujours essayer de compiler sur ma machine ;)

**Comment by belangeo** [comment]
Salut Nicolas! Content de voir que tu suis toujours le projet! J'ai galéré un peu aujourd'hui avec Windows... J'ai pas trouvé d'installeur pour visual studio 2015!!! As-tu déjà compilé des projets Juce avec VS 2017? Il n'y a pas d'exporter pour VS 2017 mais peut-être que l'exporter pour VS 2015 fonctionne avec 2017. Sinon, comment on fait pour trouver un vieux Visual Studio?

Robert, j'ai une machine windows 10 que je garde vierge (sans outils de développement). Elle servira de machine pour tester.

**Comment by theRedMercury** [comment]
Hello, oui je vois souvent passer les mails des issues du projet, c'est chouette de voir qu'il continue à vivre :)
J'ai  une tour avec Windows 10 et VS2017 installés, je peux toujours essayer, au pire j'installe Windows vs 2015.
Le truc qui m'inquiète le plus c'est Jack sur Windows, je ne sais pas si ça va passer, à voir...
Je suis un peu occupé avec cette fin d'année, mais en janvier j'aurais plus de temps pour essayer cela, je vous tiens au jus.
J'espère que tout ce passe bien à Montréal chez vous :D

**Comment by belangeo** [comment]
J'ai installé Jack sur mon Windows 7 aujourd'hui, ça roule bien (après avoir sélectionné le bon driver évidemment)!

Bon temps des fêtes!

**Comment by belangeo** [comment]
Bon, j'ai fait un setup windows avec Juce, Jack et Visual Studio 2015 (ça prend des heures à installer ce bidule). Mais je quitte pour 10 jours (voir la mama en Floride), alors je commencerai à travailler le build Windows à mon retour!

**Comment by Normandeau** [comment]
Bonnes vacances en Floride.
On se revoit en janvier.
Salutations à Nicolas!

**Comment by theRedMercury** [comment]
J'ai essayé de compiler une version VS2017 générée avec le ProJucer 5.2.0, mais il y a plein d'erreurs concernant Jack, je n'ai pas encore pris la peine de regarder dans les détails.
En espérant que tu as plus de chance avec la version VS2015.
Bon voyage :)

**Comment by Normandeau** [comment]
Ah, Windows et la Floride! Pas facile de faire un choix! 
Merci Nicolas, Passe un bon temps des fêtes. Ici il y a David qui rame au max, mais grâce à ServerGRIS, ça «lui fait plus facile». Et on a même un manuel! Ce qui, convenons-en, est la partie la plus difficile...

**Comment by theRedMercury** [comment]
Bonne année :)

Mauvaise nouvelle : 
[https://github.com/GRIS-UdeM/ServerGRIS/tree/windows]
J'ai réussi à compiler le ServerGris sur Windows, mais j'ai un problème avec Jack quand je le lance : 

Exception thrown at 0x0000000069A2F26B (libjack64.dll) in ServerGRIS.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFC01B58.

Il va falloir creuser pour savoir quel est le problème.

**Comment by theRedMercury** [comment]
![image](https://user-images.githubusercontent.com/6116482/34698155-f1e240cc-f4d6-11e7-8526-84a29a356318.png)

Enfin il se lance sur Windows 10.

Mais il y a encore beaucoup de contraintes : 
Il ne fonctionne actuellement que sur Jack 32 Bits (donc la compilation du ServerGris aussi en 32)
Il faut démarrer le server Jack via Jack Control (JackQt)
Et il faut vérifier si les séquenceurs audio arrivent à se connecter sur le ServerGris.

Mais bon, on arrive quand même à le démarrer sur Windows 10 64 bits

**Comment by belangeo** [comment]
Super! 

> Il ne fonctionne actuellement que sur Jack 32 Bits (donc la compilation du ServerGris aussi en 32)

Le 32-bit, c'est pas un problème, ma chaîne de développement est en 32-bit!

> Il faut démarrer le server Jack via Jack Control (JackQt)

Au pire, on cache le tout avec un .bat script. Puis on cache le .bat avec l'icône du ServerGris!

**Comment by SamuelBeland** [comment]
Réglé depuis 2.1.4
