### ISSUE TITLE
Pourquoi les ~ après Inputs et Outputs

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/ServerGRIS#99]
Est-ce que ça sert à quelque chose?

![mutes et solos](https://user-images.githubusercontent.com/8959779/34188567-1e3ffae2-e505-11e7-9d1f-27e754046c91.jpg)

**Comment by belangeo** [comment]
C'est pas un artefact du Zirkonium? Et du même coup de MaxMSP qui utilise le ~ pour indiquer les objets qui gèrent des signaux audio? Ça devrait partir selon moi!
